package com.mercon.entities;


// Generated Nov 4, 2014 2:16:20 PM by Hibernate Tools 3.4.0.CR1

/**
 * VbuildDrawTag generated by hbm2java
 */
public class VbuildDrawTag implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3627309770985402585L;
	private VbuildDrawTagId id;

	public VbuildDrawTag() {
	}

	public VbuildDrawTag(VbuildDrawTagId id) {
		this.id = id;
	}

	public VbuildDrawTagId getId() {
		return this.id;
	}

	public void setId(VbuildDrawTagId id) {
		this.id = id;
	}

	
}
