package com.mercon.entities;

// Generated Nov 6, 2014 5:20:31 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * VbuildDrawId generated by hbm2java
 */
public class VbuildDrawId implements java.io.Serializable {

	private int cargoNum;
	private int equipmentNum;
	private int buildDrawNum;
	private int obligationDetailNum;
	private int obligationNum;
	private short buildDrawInd;
	private short buildDrawTypeInd;
	private String buildDrawType;
	private int strategyNum;
	private Integer locationNum;
	private String locationCd;
	private int transferNum;
	private Date transferStartDt;
	private Date transferEndDt;
	private BigDecimal transferPrice;
	private short transferAtInd;
	private short transferPriceStatusInd;
	private String cmdtyCd;
	private Double buildDrawQty;
	private BigDecimal openQty;
	private BigDecimal netQty;
	private BigDecimal cargoQty;
	private BigDecimal packagingQty;
	private BigDecimal baseVol;
	private BigDecimal baseMass;
	private Short filledInd;
	private BigDecimal weightedAvg;
	private BigDecimal perUnitCost;
	private Date effectiveDt;
	private short importInd;
	private short importTypeInd;
	private BigDecimal mtmPrice;
	private BigDecimal interestCost;
	private BigDecimal insuranceCost;
	private BigDecimal PLValue;
	private short priceLockedInd;
	private BigDecimal gainLossFactor;
	private BigDecimal transferCost;
	private BigDecimal commodityCost;
	private int tradeNum;
	private String comments;
	private int conversionDtlNum;
	private Date lastModifyDt;
	private int modifyPersonNum;
	private String lastModifyBy;
	private Date deliveryDt;
	private Date titleTransferDt;
	
	private List<VopsTransferUdf> transferUdf;

	public VbuildDrawId() {
	}

	public VbuildDrawId(int cargoNum, int equipmentNum, int buildDrawNum,
			int obligationDetailNum, int obligationNum, short buildDrawInd,
			short buildDrawTypeInd, String buildDrawType, int strategyNum,
			String locationCd, int transferNum, BigDecimal transferPrice,
			short transferAtInd, short transferPriceStatusInd,
			BigDecimal netQty, BigDecimal cargoQty, BigDecimal packagingQty,
			BigDecimal weightedAvg, BigDecimal perUnitCost, short importInd,
			short importTypeInd, BigDecimal mtmPrice, BigDecimal interestCost,
			BigDecimal insuranceCost, BigDecimal PLValue, short priceLockedInd,
			BigDecimal gainLossFactor, BigDecimal transferCost,
			BigDecimal commodityCost, int tradeNum, String comments,
			int conversionDtlNum, Date lastModifyDt, int modifyPersonNum,
			String lastModifyBy, Date deliveryDt, Date titleTransferDt) {
		this.cargoNum = cargoNum;
		this.equipmentNum = equipmentNum;
		this.buildDrawNum = buildDrawNum;
		this.obligationDetailNum = obligationDetailNum;
		this.obligationNum = obligationNum;
		this.buildDrawInd = buildDrawInd;
		this.buildDrawTypeInd = buildDrawTypeInd;
		this.buildDrawType = buildDrawType;
		this.strategyNum = strategyNum;
		this.locationCd = locationCd;
		this.transferNum = transferNum;
		this.transferPrice = transferPrice;
		this.transferAtInd = transferAtInd;
		this.transferPriceStatusInd = transferPriceStatusInd;
		this.netQty = netQty;
		this.cargoQty = cargoQty;
		this.packagingQty = packagingQty;
		this.weightedAvg = weightedAvg;
		this.perUnitCost = perUnitCost;
		this.importInd = importInd;
		this.importTypeInd = importTypeInd;
		this.mtmPrice = mtmPrice;
		this.interestCost = interestCost;
		this.insuranceCost = insuranceCost;
		this.PLValue = PLValue;
		this.priceLockedInd = priceLockedInd;
		this.gainLossFactor = gainLossFactor;
		this.transferCost = transferCost;
		this.commodityCost = commodityCost;
		this.tradeNum = tradeNum;
		this.comments = comments;
		this.conversionDtlNum = conversionDtlNum;
		this.lastModifyDt = lastModifyDt;
		this.modifyPersonNum = modifyPersonNum;
		this.lastModifyBy = lastModifyBy;
		this.deliveryDt = deliveryDt;
		this.titleTransferDt = titleTransferDt;
	}

	public VbuildDrawId(int cargoNum, int equipmentNum, int buildDrawNum,
			int obligationDetailNum, int obligationNum, short buildDrawInd,
			short buildDrawTypeInd, String buildDrawType, int strategyNum,
			Integer locationNum, String locationCd, int transferNum,
			Date transferStartDt, Date transferEndDt, BigDecimal transferPrice,
			short transferAtInd, short transferPriceStatusInd, String cmdtyCd,
			Double buildDrawQty, BigDecimal openQty, BigDecimal netQty,
			BigDecimal cargoQty, BigDecimal packagingQty, BigDecimal baseVol,
			BigDecimal baseMass, Short filledInd, BigDecimal weightedAvg,
			BigDecimal perUnitCost, Date effectiveDt, short importInd,
			short importTypeInd, BigDecimal mtmPrice, BigDecimal interestCost,
			BigDecimal insuranceCost, BigDecimal PLValue, short priceLockedInd,
			BigDecimal gainLossFactor, BigDecimal transferCost,
			BigDecimal commodityCost, int tradeNum, String comments,
			int conversionDtlNum, Date lastModifyDt, int modifyPersonNum,
			String lastModifyBy, Date deliveryDt, Date titleTransferDt) {
		this.cargoNum = cargoNum;
		this.equipmentNum = equipmentNum;
		this.buildDrawNum = buildDrawNum;
		this.obligationDetailNum = obligationDetailNum;
		this.obligationNum = obligationNum;
		this.buildDrawInd = buildDrawInd;
		this.buildDrawTypeInd = buildDrawTypeInd;
		this.buildDrawType = buildDrawType;
		this.strategyNum = strategyNum;
		this.locationNum = locationNum;
		this.locationCd = locationCd;
		this.transferNum = transferNum;
		this.transferStartDt = transferStartDt;
		this.transferEndDt = transferEndDt;
		this.transferPrice = transferPrice;
		this.transferAtInd = transferAtInd;
		this.transferPriceStatusInd = transferPriceStatusInd;
		this.cmdtyCd = cmdtyCd;
		this.buildDrawQty = buildDrawQty;
		this.openQty = openQty;
		this.netQty = netQty;
		this.cargoQty = cargoQty;
		this.packagingQty = packagingQty;
		this.baseVol = baseVol;
		this.baseMass = baseMass;
		this.filledInd = filledInd;
		this.weightedAvg = weightedAvg;
		this.perUnitCost = perUnitCost;
		this.effectiveDt = effectiveDt;
		this.importInd = importInd;
		this.importTypeInd = importTypeInd;
		this.mtmPrice = mtmPrice;
		this.interestCost = interestCost;
		this.insuranceCost = insuranceCost;
		this.PLValue = PLValue;
		this.priceLockedInd = priceLockedInd;
		this.gainLossFactor = gainLossFactor;
		this.transferCost = transferCost;
		this.commodityCost = commodityCost;
		this.tradeNum = tradeNum;
		this.comments = comments;
		this.conversionDtlNum = conversionDtlNum;
		this.lastModifyDt = lastModifyDt;
		this.modifyPersonNum = modifyPersonNum;
		this.lastModifyBy = lastModifyBy;
		this.deliveryDt = deliveryDt;
		this.titleTransferDt = titleTransferDt;
	}

	public int getCargoNum() {
		return this.cargoNum;
	}

	public void setCargoNum(int cargoNum) {
		this.cargoNum = cargoNum;
	}

	public int getEquipmentNum() {
		return this.equipmentNum;
	}

	public void setEquipmentNum(int equipmentNum) {
		this.equipmentNum = equipmentNum;
	}

	public int getBuildDrawNum() {
		return this.buildDrawNum;
	}

	public void setBuildDrawNum(int buildDrawNum) {
		this.buildDrawNum = buildDrawNum;
	}

	public int getObligationDetailNum() {
		return this.obligationDetailNum;
	}

	public void setObligationDetailNum(int obligationDetailNum) {
		this.obligationDetailNum = obligationDetailNum;
	}

	public int getObligationNum() {
		return this.obligationNum;
	}

	public void setObligationNum(int obligationNum) {
		this.obligationNum = obligationNum;
	}

	public short getBuildDrawInd() {
		return this.buildDrawInd;
	}

	public void setBuildDrawInd(short buildDrawInd) {
		this.buildDrawInd = buildDrawInd;
	}

	public short getBuildDrawTypeInd() {
		return this.buildDrawTypeInd;
	}

	public void setBuildDrawTypeInd(short buildDrawTypeInd) {
		this.buildDrawTypeInd = buildDrawTypeInd;
	}

	public String getBuildDrawType() {
		return this.buildDrawType;
	}

	public void setBuildDrawType(String buildDrawType) {
		this.buildDrawType = buildDrawType;
	}

	public int getStrategyNum() {
		return this.strategyNum;
	}

	public void setStrategyNum(int strategyNum) {
		this.strategyNum = strategyNum;
	}

	public Integer getLocationNum() {
		return this.locationNum;
	}

	public void setLocationNum(Integer locationNum) {
		this.locationNum = locationNum;
	}

	public String getLocationCd() {
		return this.locationCd;
	}

	public void setLocationCd(String locationCd) {
		this.locationCd = locationCd;
	}

	public int getTransferNum() {
		return this.transferNum;
	}

	public void setTransferNum(int transferNum) {
		this.transferNum = transferNum;
	}

	public Date getTransferStartDt() {
		return this.transferStartDt;
	}

	public void setTransferStartDt(Date transferStartDt) {
		this.transferStartDt = transferStartDt;
	}

	public Date getTransferEndDt() {
		return this.transferEndDt;
	}

	public void setTransferEndDt(Date transferEndDt) {
		this.transferEndDt = transferEndDt;
	}

	public BigDecimal getTransferPrice() {
		return this.transferPrice;
	}

	public void setTransferPrice(BigDecimal transferPrice) {
		this.transferPrice = transferPrice;
	}

	public short getTransferAtInd() {
		return this.transferAtInd;
	}

	public void setTransferAtInd(short transferAtInd) {
		this.transferAtInd = transferAtInd;
	}

	public short getTransferPriceStatusInd() {
		return this.transferPriceStatusInd;
	}

	public void setTransferPriceStatusInd(short transferPriceStatusInd) {
		this.transferPriceStatusInd = transferPriceStatusInd;
	}

	public String getCmdtyCd() {
		return this.cmdtyCd;
	}

	public void setCmdtyCd(String cmdtyCd) {
		this.cmdtyCd = cmdtyCd;
	}

	public Double getBuildDrawQty() {
		return this.buildDrawQty;
	}

	public void setBuildDrawQty(Double buildDrawQty) {
		this.buildDrawQty = buildDrawQty;
	}

	public BigDecimal getOpenQty() {
		return this.openQty;
	}

	public void setOpenQty(BigDecimal openQty) {
		this.openQty = openQty;
	}

	public BigDecimal getNetQty() {
		return this.netQty;
	}

	public void setNetQty(BigDecimal netQty) {
		this.netQty = netQty;
	}

	public BigDecimal getCargoQty() {
		return this.cargoQty;
	}

	public void setCargoQty(BigDecimal cargoQty) {
		this.cargoQty = cargoQty;
	}

	public BigDecimal getPackagingQty() {
		return this.packagingQty;
	}

	public void setPackagingQty(BigDecimal packagingQty) {
		this.packagingQty = packagingQty;
	}

	public BigDecimal getBaseVol() {
		return this.baseVol;
	}

	public void setBaseVol(BigDecimal baseVol) {
		this.baseVol = baseVol;
	}

	public BigDecimal getBaseMass() {
		return this.baseMass;
	}

	public void setBaseMass(BigDecimal baseMass) {
		this.baseMass = baseMass;
	}

	public Short getFilledInd() {
		return this.filledInd;
	}

	public void setFilledInd(Short filledInd) {
		this.filledInd = filledInd;
	}

	public BigDecimal getWeightedAvg() {
		return this.weightedAvg;
	}

	public void setWeightedAvg(BigDecimal weightedAvg) {
		this.weightedAvg = weightedAvg;
	}

	public BigDecimal getPerUnitCost() {
		return this.perUnitCost;
	}

	public void setPerUnitCost(BigDecimal perUnitCost) {
		this.perUnitCost = perUnitCost;
	}

	public Date getEffectiveDt() {
		return this.effectiveDt;
	}

	public void setEffectiveDt(Date effectiveDt) {
		this.effectiveDt = effectiveDt;
	}

	public short getImportInd() {
		return this.importInd;
	}

	public void setImportInd(short importInd) {
		this.importInd = importInd;
	}

	public short getImportTypeInd() {
		return this.importTypeInd;
	}

	public void setImportTypeInd(short importTypeInd) {
		this.importTypeInd = importTypeInd;
	}

	public BigDecimal getMtmPrice() {
		return this.mtmPrice;
	}

	public void setMtmPrice(BigDecimal mtmPrice) {
		this.mtmPrice = mtmPrice;
	}

	public BigDecimal getInterestCost() {
		return this.interestCost;
	}

	public void setInterestCost(BigDecimal interestCost) {
		this.interestCost = interestCost;
	}

	public BigDecimal getInsuranceCost() {
		return this.insuranceCost;
	}

	public void setInsuranceCost(BigDecimal insuranceCost) {
		this.insuranceCost = insuranceCost;
	}

	public BigDecimal getPLValue() {
		return this.PLValue;
	}

	public void setPLValue(BigDecimal PLValue) {
		this.PLValue = PLValue;
	}

	public short getPriceLockedInd() {
		return this.priceLockedInd;
	}

	public void setPriceLockedInd(short priceLockedInd) {
		this.priceLockedInd = priceLockedInd;
	}

	public BigDecimal getGainLossFactor() {
		return this.gainLossFactor;
	}

	public void setGainLossFactor(BigDecimal gainLossFactor) {
		this.gainLossFactor = gainLossFactor;
	}

	public BigDecimal getTransferCost() {
		return this.transferCost;
	}

	public void setTransferCost(BigDecimal transferCost) {
		this.transferCost = transferCost;
	}

	public BigDecimal getCommodityCost() {
		return this.commodityCost;
	}

	public void setCommodityCost(BigDecimal commodityCost) {
		this.commodityCost = commodityCost;
	}

	public int getTradeNum() {
		return this.tradeNum;
	}

	public void setTradeNum(int tradeNum) {
		this.tradeNum = tradeNum;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public int getConversionDtlNum() {
		return this.conversionDtlNum;
	}

	public void setConversionDtlNum(int conversionDtlNum) {
		this.conversionDtlNum = conversionDtlNum;
	}

	public Date getLastModifyDt() {
		return this.lastModifyDt;
	}

	public void setLastModifyDt(Date lastModifyDt) {
		this.lastModifyDt = lastModifyDt;
	}

	public int getModifyPersonNum() {
		return this.modifyPersonNum;
	}

	public void setModifyPersonNum(int modifyPersonNum) {
		this.modifyPersonNum = modifyPersonNum;
	}

	public String getLastModifyBy() {
		return this.lastModifyBy;
	}

	public void setLastModifyBy(String lastModifyBy) {
		this.lastModifyBy = lastModifyBy;
	}

	public Date getDeliveryDt() {
		return this.deliveryDt;
	}

	public void setDeliveryDt(Date deliveryDt) {
		this.deliveryDt = deliveryDt;
	}

	public Date getTitleTransferDt() {
		return this.titleTransferDt;
	}

	public void setTitleTransferDt(Date titleTransferDt) {
		this.titleTransferDt = titleTransferDt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VbuildDrawId))
			return false;
		VbuildDrawId castOther = (VbuildDrawId) other;

		return (this.getCargoNum() == castOther.getCargoNum())
				&& (this.getEquipmentNum() == castOther.getEquipmentNum())
				&& (this.getBuildDrawNum() == castOther.getBuildDrawNum())
				&& (this.getObligationDetailNum() == castOther
						.getObligationDetailNum())
				&& (this.getObligationNum() == castOther.getObligationNum())
				&& (this.getBuildDrawInd() == castOther.getBuildDrawInd())
				&& (this.getBuildDrawTypeInd() == castOther
						.getBuildDrawTypeInd())
				&& ((this.getBuildDrawType() == castOther.getBuildDrawType()) || (this
						.getBuildDrawType() != null
						&& castOther.getBuildDrawType() != null && this
						.getBuildDrawType()
						.equals(castOther.getBuildDrawType())))
				&& (this.getStrategyNum() == castOther.getStrategyNum())
				&& ((this.getLocationNum() == castOther.getLocationNum()) || (this
						.getLocationNum() != null
						&& castOther.getLocationNum() != null && this
						.getLocationNum().equals(castOther.getLocationNum())))
				&& ((this.getLocationCd() == castOther.getLocationCd()) || (this
						.getLocationCd() != null
						&& castOther.getLocationCd() != null && this
						.getLocationCd().equals(castOther.getLocationCd())))
				&& (this.getTransferNum() == castOther.getTransferNum())
				&& ((this.getTransferStartDt() == castOther
						.getTransferStartDt()) || (this.getTransferStartDt() != null
						&& castOther.getTransferStartDt() != null && this
						.getTransferStartDt().equals(
								castOther.getTransferStartDt())))
				&& ((this.getTransferEndDt() == castOther.getTransferEndDt()) || (this
						.getTransferEndDt() != null
						&& castOther.getTransferEndDt() != null && this
						.getTransferEndDt()
						.equals(castOther.getTransferEndDt())))
				&& ((this.getTransferPrice() == castOther.getTransferPrice()) || (this
						.getTransferPrice() != null
						&& castOther.getTransferPrice() != null && this
						.getTransferPrice()
						.equals(castOther.getTransferPrice())))
				&& (this.getTransferAtInd() == castOther.getTransferAtInd())
				&& (this.getTransferPriceStatusInd() == castOther
						.getTransferPriceStatusInd())
				&& ((this.getCmdtyCd() == castOther.getCmdtyCd()) || (this
						.getCmdtyCd() != null && castOther.getCmdtyCd() != null && this
						.getCmdtyCd().equals(castOther.getCmdtyCd())))
				&& ((this.getBuildDrawQty() == castOther.getBuildDrawQty()) || (this
						.getBuildDrawQty() != null
						&& castOther.getBuildDrawQty() != null && this
						.getBuildDrawQty().equals(castOther.getBuildDrawQty())))
				&& ((this.getOpenQty() == castOther.getOpenQty()) || (this
						.getOpenQty() != null && castOther.getOpenQty() != null && this
						.getOpenQty().equals(castOther.getOpenQty())))
				&& ((this.getNetQty() == castOther.getNetQty()) || (this
						.getNetQty() != null && castOther.getNetQty() != null && this
						.getNetQty().equals(castOther.getNetQty())))
				&& ((this.getCargoQty() == castOther.getCargoQty()) || (this
						.getCargoQty() != null
						&& castOther.getCargoQty() != null && this
						.getCargoQty().equals(castOther.getCargoQty())))
				&& ((this.getPackagingQty() == castOther.getPackagingQty()) || (this
						.getPackagingQty() != null
						&& castOther.getPackagingQty() != null && this
						.getPackagingQty().equals(castOther.getPackagingQty())))
				&& ((this.getBaseVol() == castOther.getBaseVol()) || (this
						.getBaseVol() != null && castOther.getBaseVol() != null && this
						.getBaseVol().equals(castOther.getBaseVol())))
				&& ((this.getBaseMass() == castOther.getBaseMass()) || (this
						.getBaseMass() != null
						&& castOther.getBaseMass() != null && this
						.getBaseMass().equals(castOther.getBaseMass())))
				&& ((this.getFilledInd() == castOther.getFilledInd()) || (this
						.getFilledInd() != null
						&& castOther.getFilledInd() != null && this
						.getFilledInd().equals(castOther.getFilledInd())))
				&& ((this.getWeightedAvg() == castOther.getWeightedAvg()) || (this
						.getWeightedAvg() != null
						&& castOther.getWeightedAvg() != null && this
						.getWeightedAvg().equals(castOther.getWeightedAvg())))
				&& ((this.getPerUnitCost() == castOther.getPerUnitCost()) || (this
						.getPerUnitCost() != null
						&& castOther.getPerUnitCost() != null && this
						.getPerUnitCost().equals(castOther.getPerUnitCost())))
				&& ((this.getEffectiveDt() == castOther.getEffectiveDt()) || (this
						.getEffectiveDt() != null
						&& castOther.getEffectiveDt() != null && this
						.getEffectiveDt().equals(castOther.getEffectiveDt())))
				&& (this.getImportInd() == castOther.getImportInd())
				&& (this.getImportTypeInd() == castOther.getImportTypeInd())
				&& ((this.getMtmPrice() == castOther.getMtmPrice()) || (this
						.getMtmPrice() != null
						&& castOther.getMtmPrice() != null && this
						.getMtmPrice().equals(castOther.getMtmPrice())))
				&& ((this.getInterestCost() == castOther.getInterestCost()) || (this
						.getInterestCost() != null
						&& castOther.getInterestCost() != null && this
						.getInterestCost().equals(castOther.getInterestCost())))
				&& ((this.getInsuranceCost() == castOther.getInsuranceCost()) || (this
						.getInsuranceCost() != null
						&& castOther.getInsuranceCost() != null && this
						.getInsuranceCost()
						.equals(castOther.getInsuranceCost())))
				&& ((this.getPLValue() == castOther.getPLValue()) || (this
						.getPLValue() != null && castOther.getPLValue() != null && this
						.getPLValue().equals(castOther.getPLValue())))
				&& (this.getPriceLockedInd() == castOther.getPriceLockedInd())
				&& ((this.getGainLossFactor() == castOther.getGainLossFactor()) || (this
						.getGainLossFactor() != null
						&& castOther.getGainLossFactor() != null && this
						.getGainLossFactor().equals(
								castOther.getGainLossFactor())))
				&& ((this.getTransferCost() == castOther.getTransferCost()) || (this
						.getTransferCost() != null
						&& castOther.getTransferCost() != null && this
						.getTransferCost().equals(castOther.getTransferCost())))
				&& ((this.getCommodityCost() == castOther.getCommodityCost()) || (this
						.getCommodityCost() != null
						&& castOther.getCommodityCost() != null && this
						.getCommodityCost()
						.equals(castOther.getCommodityCost())))
				&& (this.getTradeNum() == castOther.getTradeNum())
				&& ((this.getComments() == castOther.getComments()) || (this
						.getComments() != null
						&& castOther.getComments() != null && this
						.getComments().equals(castOther.getComments())))
				&& (this.getConversionDtlNum() == castOther
						.getConversionDtlNum())
				&& ((this.getLastModifyDt() == castOther.getLastModifyDt()) || (this
						.getLastModifyDt() != null
						&& castOther.getLastModifyDt() != null && this
						.getLastModifyDt().equals(castOther.getLastModifyDt())))
				&& (this.getModifyPersonNum() == castOther.getModifyPersonNum())
				&& ((this.getLastModifyBy() == castOther.getLastModifyBy()) || (this
						.getLastModifyBy() != null
						&& castOther.getLastModifyBy() != null && this
						.getLastModifyBy().equals(castOther.getLastModifyBy())))
				&& ((this.getDeliveryDt() == castOther.getDeliveryDt()) || (this
						.getDeliveryDt() != null
						&& castOther.getDeliveryDt() != null && this
						.getDeliveryDt().equals(castOther.getDeliveryDt())))
				&& ((this.getTitleTransferDt() == castOther
						.getTitleTransferDt()) || (this.getTitleTransferDt() != null
						&& castOther.getTitleTransferDt() != null && this
						.getTitleTransferDt().equals(
								castOther.getTitleTransferDt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCargoNum();
		result = 37 * result + this.getEquipmentNum();
		result = 37 * result + this.getBuildDrawNum();
		result = 37 * result + this.getObligationDetailNum();
		result = 37 * result + this.getObligationNum();
		result = 37 * result + this.getBuildDrawInd();
		result = 37 * result + this.getBuildDrawTypeInd();
		result = 37
				* result
				+ (getBuildDrawType() == null ? 0 : this.getBuildDrawType()
						.hashCode());
		result = 37 * result + this.getStrategyNum();
		result = 37
				* result
				+ (getLocationNum() == null ? 0 : this.getLocationNum()
						.hashCode());
		result = 37
				* result
				+ (getLocationCd() == null ? 0 : this.getLocationCd()
						.hashCode());
		result = 37 * result + this.getTransferNum();
		result = 37
				* result
				+ (getTransferStartDt() == null ? 0 : this.getTransferStartDt()
						.hashCode());
		result = 37
				* result
				+ (getTransferEndDt() == null ? 0 : this.getTransferEndDt()
						.hashCode());
		result = 37
				* result
				+ (getTransferPrice() == null ? 0 : this.getTransferPrice()
						.hashCode());
		result = 37 * result + this.getTransferAtInd();
		result = 37 * result + this.getTransferPriceStatusInd();
		result = 37 * result
				+ (getCmdtyCd() == null ? 0 : this.getCmdtyCd().hashCode());
		result = 37
				* result
				+ (getBuildDrawQty() == null ? 0 : this.getBuildDrawQty()
						.hashCode());
		result = 37 * result
				+ (getOpenQty() == null ? 0 : this.getOpenQty().hashCode());
		result = 37 * result
				+ (getNetQty() == null ? 0 : this.getNetQty().hashCode());
		result = 37 * result
				+ (getCargoQty() == null ? 0 : this.getCargoQty().hashCode());
		result = 37
				* result
				+ (getPackagingQty() == null ? 0 : this.getPackagingQty()
						.hashCode());
		result = 37 * result
				+ (getBaseVol() == null ? 0 : this.getBaseVol().hashCode());
		result = 37 * result
				+ (getBaseMass() == null ? 0 : this.getBaseMass().hashCode());
		result = 37 * result
				+ (getFilledInd() == null ? 0 : this.getFilledInd().hashCode());
		result = 37
				* result
				+ (getWeightedAvg() == null ? 0 : this.getWeightedAvg()
						.hashCode());
		result = 37
				* result
				+ (getPerUnitCost() == null ? 0 : this.getPerUnitCost()
						.hashCode());
		result = 37
				* result
				+ (getEffectiveDt() == null ? 0 : this.getEffectiveDt()
						.hashCode());
		result = 37 * result + this.getImportInd();
		result = 37 * result + this.getImportTypeInd();
		result = 37 * result
				+ (getMtmPrice() == null ? 0 : this.getMtmPrice().hashCode());
		result = 37
				* result
				+ (getInterestCost() == null ? 0 : this.getInterestCost()
						.hashCode());
		result = 37
				* result
				+ (getInsuranceCost() == null ? 0 : this.getInsuranceCost()
						.hashCode());
		result = 37 * result
				+ (getPLValue() == null ? 0 : this.getPLValue().hashCode());
		result = 37 * result + this.getPriceLockedInd();
		result = 37
				* result
				+ (getGainLossFactor() == null ? 0 : this.getGainLossFactor()
						.hashCode());
		result = 37
				* result
				+ (getTransferCost() == null ? 0 : this.getTransferCost()
						.hashCode());
		result = 37
				* result
				+ (getCommodityCost() == null ? 0 : this.getCommodityCost()
						.hashCode());
		result = 37 * result + this.getTradeNum();
		result = 37 * result
				+ (getComments() == null ? 0 : this.getComments().hashCode());
		result = 37 * result + this.getConversionDtlNum();
		result = 37
				* result
				+ (getLastModifyDt() == null ? 0 : this.getLastModifyDt()
						.hashCode());
		result = 37 * result + this.getModifyPersonNum();
		result = 37
				* result
				+ (getLastModifyBy() == null ? 0 : this.getLastModifyBy()
						.hashCode());
		result = 37
				* result
				+ (getDeliveryDt() == null ? 0 : this.getDeliveryDt()
						.hashCode());
		result = 37
				* result
				+ (getTitleTransferDt() == null ? 0 : this.getTitleTransferDt()
						.hashCode());
		return result;
	}

	public List<VopsTransferUdf> getTransferUdf() {
		return transferUdf;
	}

	public void setTransferUdf(List<VopsTransferUdf> transferUdf) {
		this.transferUdf = transferUdf;
	}

}
