package com.mercon.entities;

// Generated 09-17-2012 01:19:03 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * VdimStrategyId generated by hbm2java
 */
public class VdimStrategyId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int numStrategy;
	private String codProcessGroup;
	private String nameStrategy;
	private String typStrategy;;
	private short statStrategy;
	private short isTradeable;
	private short statIndicator;
	private Date dtLastModify;
	private int numLastModifyPerson;

	public VdimStrategyId() {
	}

	public VdimStrategyId(int numStrategy, String codProcessGroup,
			String nameStrategy, String typStrategy, short statStrategy,
			short isTradeable, short statIndicator, Date dtLastModify,
			int numLastModifyPerson) {
		this.numStrategy = numStrategy;
		this.codProcessGroup = codProcessGroup;
		this.nameStrategy = nameStrategy;
		this.typStrategy = typStrategy;
		this.statStrategy = statStrategy;
		this.isTradeable = isTradeable;
		this.statIndicator = statIndicator;
		this.dtLastModify = dtLastModify;
		this.numLastModifyPerson = numLastModifyPerson;
	}

	public int getNumStrategy() {
		return this.numStrategy;
	}

	public void setNumStrategy(int numStrategy) {
		this.numStrategy = numStrategy;
	}

	public String getCodProcessGroup() {
		return this.codProcessGroup;
	}

	public void setCodProcessGroup(String codProcessGroup) {
		this.codProcessGroup = codProcessGroup;
	}

	public String getNameStrategy() {
		return this.nameStrategy;
	}

	public void setNameStrategy(String nameStrategy) {
		this.nameStrategy = nameStrategy;
	}

	public String getTypStrategy() {
		return this.typStrategy;
	}

	public void setTypStrategy(String typStrategy) {
		this.typStrategy = typStrategy;
	}

	public short getStatStrategy() {
		return this.statStrategy;
	}

	public void setStatStrategy(short statStrategy) {
		this.statStrategy = statStrategy;
	}

	public short getIsTradeable() {
		return this.isTradeable;
	}

	public void setIsTradeable(short isTradeable) {
		this.isTradeable = isTradeable;
	}

	public short getStatIndicator() {
		return this.statIndicator;
	}

	public void setStatIndicator(short statIndicator) {
		this.statIndicator = statIndicator;
	}

	public Date getDtLastModify() {
		return this.dtLastModify;
	}

	public void setDtLastModify(Date dtLastModify) {
		this.dtLastModify = dtLastModify;
	}

	public int getNumLastModifyPerson() {
		return this.numLastModifyPerson;
	}

	public void setNumLastModifyPerson(int numLastModifyPerson) {
		this.numLastModifyPerson = numLastModifyPerson;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VdimStrategyId))
			return false;
		VdimStrategyId castOther = (VdimStrategyId) other;

		return (this.getNumStrategy() == castOther.getNumStrategy())
				&& ((this.getCodProcessGroup() == castOther
						.getCodProcessGroup()) || (this.getCodProcessGroup() != null
						&& castOther.getCodProcessGroup() != null && this
						.getCodProcessGroup().equals(
								castOther.getCodProcessGroup())))
				&& ((this.getNameStrategy() == castOther.getNameStrategy()) || (this
						.getNameStrategy() != null
						&& castOther.getNameStrategy() != null && this
						.getNameStrategy().equals(castOther.getNameStrategy())))
				&& ((this.getTypStrategy() == castOther.getTypStrategy()) || (this
						.getTypStrategy() != null
						&& castOther.getTypStrategy() != null && this
						.getTypStrategy().equals(castOther.getTypStrategy())))
				&& (this.getStatStrategy() == castOther.getStatStrategy())
				&& (this.getIsTradeable() == castOther.getIsTradeable())
				&& (this.getStatIndicator() == castOther.getStatIndicator())
				&& ((this.getDtLastModify() == castOther.getDtLastModify()) || (this
						.getDtLastModify() != null
						&& castOther.getDtLastModify() != null && this
						.getDtLastModify().equals(castOther.getDtLastModify())))
				&& (this.getNumLastModifyPerson() == castOther
						.getNumLastModifyPerson());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumStrategy();
		result = 37
				* result
				+ (getCodProcessGroup() == null ? 0 : this.getCodProcessGroup()
						.hashCode());
		result = 37
				* result
				+ (getNameStrategy() == null ? 0 : this.getNameStrategy()
						.hashCode());
		result = 37
				* result
				+ (getTypStrategy() == null ? 0 : this.getTypStrategy()
						.hashCode());
		result = 37 * result + this.getStatStrategy();
		result = 37 * result + this.getIsTradeable();
		result = 37
				* result
				+ (getDtLastModify() == null ? 0 : this.getDtLastModify()
						.hashCode());
		result = 37 * result + this.getNumLastModifyPerson();
		return result;
	}

}
