package com.mercon.entities;

// Generated 09-24-2012 03:30:27 PM by Hibernate Tools 4.0.0

/**
 * VdimUnitOfMeasure generated by hbm2java
 */
public class VdimUnitOfMeasure implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private VdimUnitOfMeasureId id;

	public VdimUnitOfMeasure() {
	}

	public VdimUnitOfMeasure(VdimUnitOfMeasureId id) {
		this.id = id;
	}

	public VdimUnitOfMeasureId getId() {
		return this.id;
	}

	public void setId(VdimUnitOfMeasureId id) {
		this.id = id;
	}

}
