package com.mercon.entities;

// Generated Jul 29, 2013 11:20:55 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * VdimCompanyId generated by hbm2java
 */
public class VdimCompanyId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int numCompany;
	private Integer numParentCompany;
	private String codCompany;
	private String nameCompany;
	private String nameCompanyLegal;
	private short codCompanyType;
	private short statCompany;
	private Date dtLastModify;
	private int numLastModifyPerson;
	private short restrictedInd;
	private String glCd;

	public VdimCompanyId() {
	}

	public VdimCompanyId(int numCompany, String codCompany,
			short codCompanyType, short statCompany, Date dtLastModify,
			int numLastModifyPerson, short restrictedInd) {
		this.numCompany = numCompany;
		this.codCompany = codCompany;
		this.codCompanyType = codCompanyType;
		this.statCompany = statCompany;
		this.dtLastModify = dtLastModify;
		this.numLastModifyPerson = numLastModifyPerson;
		this.restrictedInd = restrictedInd;
	}

	public VdimCompanyId(int numCompany, Integer numParentCompany,
			String codCompany, String nameCompany, String nameCompanyLegal,
			short codCompanyType, short statCompany, Date dtLastModify,
			int numLastModifyPerson, short restrictedInd) {
		this.numCompany = numCompany;
		this.numParentCompany = numParentCompany;
		this.codCompany = codCompany;
		this.nameCompany = nameCompany;
		this.nameCompanyLegal = nameCompanyLegal;
		this.codCompanyType = codCompanyType;
		this.statCompany = statCompany;
		this.dtLastModify = dtLastModify;
		this.numLastModifyPerson = numLastModifyPerson;
		this.restrictedInd = restrictedInd;
	}

	public int getNumCompany() {
		return this.numCompany;
	}

	public void setNumCompany(int numCompany) {
		this.numCompany = numCompany;
	}

	public Integer getNumParentCompany() {
		return this.numParentCompany;
	}

	public void setNumParentCompany(Integer numParentCompany) {
		this.numParentCompany = numParentCompany;
	}

	public String getCodCompany() {
		return this.codCompany;
	}

	public void setCodCompany(String codCompany) {
		this.codCompany = codCompany;
	}

	public String getNameCompany() {
		return this.nameCompany;
	}

	public void setNameCompany(String nameCompany) {
		this.nameCompany = nameCompany;
	}

	public String getNameCompanyLegal() {
		return this.nameCompanyLegal;
	}

	public void setNameCompanyLegal(String nameCompanyLegal) {
		this.nameCompanyLegal = nameCompanyLegal;
	}

	public short getCodCompanyType() {
		return this.codCompanyType;
	}

	public void setCodCompanyType(short codCompanyType) {
		this.codCompanyType = codCompanyType;
	}

	public short getStatCompany() {
		return this.statCompany;
	}

	public void setStatCompany(short statCompany) {
		this.statCompany = statCompany;
	}

	public Date getDtLastModify() {
		return this.dtLastModify;
	}

	public void setDtLastModify(Date dtLastModify) {
		this.dtLastModify = dtLastModify;
	}

	public int getNumLastModifyPerson() {
		return this.numLastModifyPerson;
	}

	public void setNumLastModifyPerson(int numLastModifyPerson) {
		this.numLastModifyPerson = numLastModifyPerson;
	}

	public short getRestrictedInd() {
		return this.restrictedInd;
	}

	public void setRestrictedInd(short restrictedInd) {
		this.restrictedInd = restrictedInd;
	}
	
	public String getGlCd() {
		return glCd;
	}

	public void setGlCd(String glCd) {
		this.glCd = glCd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VdimCompanyId))
			return false;
		VdimCompanyId castOther = (VdimCompanyId) other;

		return (this.getNumCompany() == castOther.getNumCompany())
				&& ((this.getNumParentCompany() == castOther
						.getNumParentCompany()) || (this.getNumParentCompany() != null
						&& castOther.getNumParentCompany() != null && this
						.getNumParentCompany().equals(
								castOther.getNumParentCompany())))
				&& ((this.getCodCompany() == castOther.getCodCompany()) || (this
						.getCodCompany() != null
						&& castOther.getCodCompany() != null && this
						.getCodCompany().equals(castOther.getCodCompany())))
				&& ((this.getNameCompany() == castOther.getNameCompany()) || (this
						.getNameCompany() != null
						&& castOther.getNameCompany() != null && this
						.getNameCompany().equals(castOther.getNameCompany())))
				&& ((this.getNameCompanyLegal() == castOther
						.getNameCompanyLegal()) || (this.getNameCompanyLegal() != null
						&& castOther.getNameCompanyLegal() != null && this
						.getNameCompanyLegal().equals(
								castOther.getNameCompanyLegal())))
				&& (this.getCodCompanyType() == castOther.getCodCompanyType())
				&& (this.getStatCompany() == castOther.getStatCompany())
				&& ((this.getDtLastModify() == castOther.getDtLastModify()) || (this
						.getDtLastModify() != null
						&& castOther.getDtLastModify() != null && this
						.getDtLastModify().equals(castOther.getDtLastModify())))
				&& (this.getNumLastModifyPerson() == castOther
						.getNumLastModifyPerson())
				&& (this.getRestrictedInd() == castOther.getRestrictedInd());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumCompany();
		result = 37
				* result
				+ (getNumParentCompany() == null ? 0 : this
						.getNumParentCompany().hashCode());
		result = 37
				* result
				+ (getCodCompany() == null ? 0 : this.getCodCompany()
						.hashCode());
		result = 37
				* result
				+ (getNameCompany() == null ? 0 : this.getNameCompany()
						.hashCode());
		result = 37
				* result
				+ (getNameCompanyLegal() == null ? 0 : this
						.getNameCompanyLegal().hashCode());
		result = 37 * result + this.getCodCompanyType();
		result = 37 * result + this.getStatCompany();
		result = 37
				* result
				+ (getDtLastModify() == null ? 0 : this.getDtLastModify()
						.hashCode());
		result = 37 * result + this.getNumLastModifyPerson();
		result = 37 * result + this.getRestrictedInd();
		return result;
	}

}
