package com.mercon.entities;

// Generated Feb 3, 2014 9:23:28 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * VdimCommodityStrategyId generated by hbm2java
 */
public class VdimCommodityStrategyId implements java.io.Serializable {

	/**
	 * Serial ID
	 */
	private static final long serialVersionUID = -3096945217765779257L;

	private String codCommodity;
	private int mtmFwdCurveNum;
	private int strategyNum;
	private BigDecimal uomConversionRate;
	private String fromUomCd;
	private String toUomCd;
	private int locationNum;
	private int indexQuote;
	private String quoteUomCd;
	private String quoteCurrCd;

	public VdimCommodityStrategyId() {
	}

	public VdimCommodityStrategyId(String codCommodity, int mtmFwdCurveNum,
			int strategyNum, BigDecimal uomConversionRate, int locationNum,
			int indexQuote, String quoteUomCd, String quoteCurrCd) {
		this.codCommodity = codCommodity;
		this.mtmFwdCurveNum = mtmFwdCurveNum;
		this.strategyNum = strategyNum;
		this.uomConversionRate = uomConversionRate;
		this.locationNum = locationNum;
		this.indexQuote = indexQuote;
		this.quoteUomCd = quoteUomCd;
		this.quoteCurrCd = quoteCurrCd;
	}

	public VdimCommodityStrategyId(String codCommodity, int mtmFwdCurveNum,
			int strategyNum, BigDecimal uomConversionRate, String fromUomCd,
			String toUomCd, int locationNum, int indexQuote, String quoteUomCd,
			String quoteCurrCd) {
		this.codCommodity = codCommodity;
		this.mtmFwdCurveNum = mtmFwdCurveNum;
		this.strategyNum = strategyNum;
		this.uomConversionRate = uomConversionRate;
		this.fromUomCd = fromUomCd;
		this.toUomCd = toUomCd;
		this.locationNum = locationNum;
		this.indexQuote = indexQuote;
		this.quoteUomCd = quoteUomCd;
		this.quoteCurrCd = quoteCurrCd;
	}

	public String getCodCommodity() {
		return this.codCommodity;
	}

	public void setCodCommodity(String codCommodity) {
		this.codCommodity = codCommodity;
	}

	public int getMtmFwdCurveNum() {
		return this.mtmFwdCurveNum;
	}

	public void setMtmFwdCurveNum(int mtmFwdCurveNum) {
		this.mtmFwdCurveNum = mtmFwdCurveNum;
	}

	public int getStrategyNum() {
		return this.strategyNum;
	}

	public void setStrategyNum(int strategyNum) {
		this.strategyNum = strategyNum;
	}

	public BigDecimal getUomConversionRate() {
		return this.uomConversionRate;
	}

	public void setUomConversionRate(BigDecimal uomConversionRate) {
		this.uomConversionRate = uomConversionRate;
	}

	public String getFromUomCd() {
		return this.fromUomCd;
	}

	public void setFromUomCd(String fromUomCd) {
		this.fromUomCd = fromUomCd;
	}

	public String getToUomCd() {
		return this.toUomCd;
	}

	public void setToUomCd(String toUomCd) {
		this.toUomCd = toUomCd;
	}

	public int getLocationNum() {
		return this.locationNum;
	}

	public void setLocationNum(int locationNum) {
		this.locationNum = locationNum;
	}

	public int getIndexQuote() {
		return this.indexQuote;
	}

	public void setIndexQuote(int indexQuote) {
		this.indexQuote = indexQuote;
	}

	public String getQuoteUomCd() {
		return this.quoteUomCd;
	}

	public void setQuoteUomCd(String quoteUomCd) {
		this.quoteUomCd = quoteUomCd;
	}

	public String getQuoteCurrCd() {
		return this.quoteCurrCd;
	}

	public void setQuoteCurrCd(String quoteCurrCd) {
		this.quoteCurrCd = quoteCurrCd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VdimCommodityStrategyId))
			return false;
		VdimCommodityStrategyId castOther = (VdimCommodityStrategyId) other;

		return ((this.getCodCommodity() == castOther.getCodCommodity()) || (this
				.getCodCommodity() != null
				&& castOther.getCodCommodity() != null && this
				.getCodCommodity().equals(castOther.getCodCommodity())))
				&& (this.getMtmFwdCurveNum() == castOther.getMtmFwdCurveNum())
				&& (this.getStrategyNum() == castOther.getStrategyNum())
				&& ((this.getUomConversionRate() == castOther
						.getUomConversionRate()) || (this
						.getUomConversionRate() != null
						&& castOther.getUomConversionRate() != null && this
						.getUomConversionRate().equals(
								castOther.getUomConversionRate())))
				&& ((this.getFromUomCd() == castOther.getFromUomCd()) || (this
						.getFromUomCd() != null
						&& castOther.getFromUomCd() != null && this
						.getFromUomCd().equals(castOther.getFromUomCd())))
				&& ((this.getToUomCd() == castOther.getToUomCd()) || (this
						.getToUomCd() != null && castOther.getToUomCd() != null && this
						.getToUomCd().equals(castOther.getToUomCd())))
				&& (this.getLocationNum() == castOther.getLocationNum())
				&& (this.getIndexQuote() == castOther.getIndexQuote())
				&& ((this.getQuoteUomCd() == castOther.getQuoteUomCd()) || (this
						.getQuoteUomCd() != null
						&& castOther.getQuoteUomCd() != null && this
						.getQuoteUomCd().equals(castOther.getQuoteUomCd())))
				&& ((this.getQuoteCurrCd() == castOther.getQuoteCurrCd()) || (this
						.getQuoteCurrCd() != null
						&& castOther.getQuoteCurrCd() != null && this
						.getQuoteCurrCd().equals(castOther.getQuoteCurrCd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodCommodity() == null ? 0 : this.getCodCommodity()
						.hashCode());
		result = 37 * result + this.getMtmFwdCurveNum();
		result = 37 * result + this.getStrategyNum();
		result = 37
				* result
				+ (getUomConversionRate() == null ? 0 : this
						.getUomConversionRate().hashCode());
		result = 37 * result
				+ (getFromUomCd() == null ? 0 : this.getFromUomCd().hashCode());
		result = 37 * result
				+ (getToUomCd() == null ? 0 : this.getToUomCd().hashCode());
		result = 37 * result + this.getLocationNum();
		result = 37 * result + this.getIndexQuote();
		result = 37
				* result
				+ (getQuoteUomCd() == null ? 0 : this.getQuoteUomCd()
						.hashCode());
		result = 37
				* result
				+ (getQuoteCurrCd() == null ? 0 : this.getQuoteCurrCd()
						.hashCode());
		return result;
	}

}
