package com.mercon.entities;

// Generated 01-03-2013 04:45:01 PM by Hibernate Tools 4.0.0

/**
 * VdimMktQuoteDefinition generated by hbm2java
 */
public class VdimMktQuoteDefinition implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private VdimMktQuoteDefinitionId id;

	public VdimMktQuoteDefinition() {
	}

	public VdimMktQuoteDefinition(VdimMktQuoteDefinitionId id) {
		this.id = id;
	}

	public VdimMktQuoteDefinitionId getId() {
		return this.id;
	}

	public void setId(VdimMktQuoteDefinitionId id) {
		this.id = id;
	}

}
