package com.mercon.entities;

// Generated 20-nov-2013 17:31:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * VdimCommodityId generated by hbm2java
 */
public class VdimCommodityId implements java.io.Serializable {

	/**
	 * Serial ID
	 */
	private static final long serialVersionUID = 908111455371022453L;
	
	private String codCommodity;
	private String nameCommodity;
	private short isTradeable;
	private short codCommodityClass;
	private String refExternal;
	private short indStatus;
	private Date dtLastModify;
	private int numLastModifyPerson;
	private String descLegalDescription;
	private String codUomdefault;
	private int group1num;
	private String group1;
	private int group2num;
	private String group2;

	public VdimCommodityId() {
	}

	public VdimCommodityId(String codCommodity, short isTradeable,
			short codCommodityClass, short indStatus, Date dtLastModify,
			int numLastModifyPerson, String codUomdefault, int group1num,
			String group1, int group2num, String group2) {
		this.codCommodity = codCommodity;
		this.isTradeable = isTradeable;
		this.codCommodityClass = codCommodityClass;
		this.indStatus = indStatus;
		this.dtLastModify = dtLastModify;
		this.numLastModifyPerson = numLastModifyPerson;
		this.codUomdefault = codUomdefault;
		this.group1num = group1num;
		this.group1 = group1;
		this.group2num = group2num;
		this.group2 = group2;
	}

	public VdimCommodityId(String codCommodity, String nameCommodity,
			short isTradeable, short codCommodityClass, String refExternal,
			short indStatus, Date dtLastModify, int numLastModifyPerson,
			String descLegalDescription, String codUomdefault, int group1num,
			String group1, int group2num, String group2) {
		this.codCommodity = codCommodity;
		this.nameCommodity = nameCommodity;
		this.isTradeable = isTradeable;
		this.codCommodityClass = codCommodityClass;
		this.refExternal = refExternal;
		this.indStatus = indStatus;
		this.dtLastModify = dtLastModify;
		this.numLastModifyPerson = numLastModifyPerson;
		this.descLegalDescription = descLegalDescription;
		this.codUomdefault = codUomdefault;
		this.group1num = group1num;
		this.group1 = group1;
		this.group2num = group2num;
		this.group2 = group2;
	}

	public String getCodCommodity() {
		return this.codCommodity;
	}

	public void setCodCommodity(String codCommodity) {
		this.codCommodity = codCommodity;
	}

	public String getNameCommodity() {
		return this.nameCommodity;
	}

	public void setNameCommodity(String nameCommodity) {
		this.nameCommodity = nameCommodity;
	}

	public short getIsTradeable() {
		return this.isTradeable;
	}

	public void setIsTradeable(short isTradeable) {
		this.isTradeable = isTradeable;
	}

	public short getCodCommodityClass() {
		return this.codCommodityClass;
	}

	public void setCodCommodityClass(short codCommodityClass) {
		this.codCommodityClass = codCommodityClass;
	}

	public String getRefExternal() {
		return this.refExternal;
	}

	public void setRefExternal(String refExternal) {
		this.refExternal = refExternal;
	}

	public short getIndStatus() {
		return this.indStatus;
	}

	public void setIndStatus(short indStatus) {
		this.indStatus = indStatus;
	}

	public Date getDtLastModify() {
		return this.dtLastModify;
	}

	public void setDtLastModify(Date dtLastModify) {
		this.dtLastModify = dtLastModify;
	}

	public int getNumLastModifyPerson() {
		return this.numLastModifyPerson;
	}

	public void setNumLastModifyPerson(int numLastModifyPerson) {
		this.numLastModifyPerson = numLastModifyPerson;
	}

	public String getDescLegalDescription() {
		return this.descLegalDescription;
	}

	public void setDescLegalDescription(String descLegalDescription) {
		this.descLegalDescription = descLegalDescription;
	}

	public String getCodUomdefault() {
		return this.codUomdefault;
	}

	public void setCodUomdefault(String codUomdefault) {
		this.codUomdefault = codUomdefault;
	}

	public int getGroup1num() {
		return this.group1num;
	}

	public void setGroup1num(int group1num) {
		this.group1num = group1num;
	}

	public String getGroup1() {
		return this.group1;
	}

	public void setGroup1(String group1) {
		this.group1 = group1;
	}

	public int getGroup2num() {
		return this.group2num;
	}

	public void setGroup2num(int group2num) {
		this.group2num = group2num;
	}

	public String getGroup2() {
		return this.group2;
	}

	public void setGroup2(String group2) {
		this.group2 = group2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VdimCommodityId))
			return false;
		VdimCommodityId castOther = (VdimCommodityId) other;

		return ((this.getCodCommodity() == castOther.getCodCommodity()) || (this
				.getCodCommodity() != null
				&& castOther.getCodCommodity() != null && this
				.getCodCommodity().equals(castOther.getCodCommodity())))
				&& ((this.getNameCommodity() == castOther.getNameCommodity()) || (this
						.getNameCommodity() != null
						&& castOther.getNameCommodity() != null && this
						.getNameCommodity()
						.equals(castOther.getNameCommodity())))
				&& (this.getIsTradeable() == castOther.getIsTradeable())
				&& (this.getCodCommodityClass() == castOther
						.getCodCommodityClass())
				&& ((this.getRefExternal() == castOther.getRefExternal()) || (this
						.getRefExternal() != null
						&& castOther.getRefExternal() != null && this
						.getRefExternal().equals(castOther.getRefExternal())))
				&& (this.getIndStatus() == castOther.getIndStatus())
				&& ((this.getDtLastModify() == castOther.getDtLastModify()) || (this
						.getDtLastModify() != null
						&& castOther.getDtLastModify() != null && this
						.getDtLastModify().equals(castOther.getDtLastModify())))
				&& (this.getNumLastModifyPerson() == castOther
						.getNumLastModifyPerson())
				&& ((this.getDescLegalDescription() == castOther
						.getDescLegalDescription()) || (this
						.getDescLegalDescription() != null
						&& castOther.getDescLegalDescription() != null && this
						.getDescLegalDescription().equals(
								castOther.getDescLegalDescription())))
				&& ((this.getCodUomdefault() == castOther.getCodUomdefault()) || (this
						.getCodUomdefault() != null
						&& castOther.getCodUomdefault() != null && this
						.getCodUomdefault()
						.equals(castOther.getCodUomdefault())))
				&& (this.getGroup1num() == castOther.getGroup1num())
				&& ((this.getGroup1() == castOther.getGroup1()) || (this
						.getGroup1() != null && castOther.getGroup1() != null && this
						.getGroup1().equals(castOther.getGroup1())))
				&& (this.getGroup2num() == castOther.getGroup2num())
				&& ((this.getGroup2() == castOther.getGroup2()) || (this
						.getGroup2() != null && castOther.getGroup2() != null && this
						.getGroup2().equals(castOther.getGroup2())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodCommodity() == null ? 0 : this.getCodCommodity()
						.hashCode());
		result = 37
				* result
				+ (getNameCommodity() == null ? 0 : this.getNameCommodity()
						.hashCode());
		result = 37 * result + this.getIsTradeable();
		result = 37 * result + this.getCodCommodityClass();
		result = 37
				* result
				+ (getRefExternal() == null ? 0 : this.getRefExternal()
						.hashCode());
		result = 37 * result + this.getIndStatus();
		result = 37
				* result
				+ (getDtLastModify() == null ? 0 : this.getDtLastModify()
						.hashCode());
		result = 37 * result + this.getNumLastModifyPerson();
		result = 37
				* result
				+ (getDescLegalDescription() == null ? 0 : this
						.getDescLegalDescription().hashCode());
		result = 37
				* result
				+ (getCodUomdefault() == null ? 0 : this.getCodUomdefault()
						.hashCode());
		result = 37 * result + this.getGroup1num();
		result = 37 * result
				+ (getGroup1() == null ? 0 : this.getGroup1().hashCode());
		result = 37 * result + this.getGroup2num();
		result = 37 * result
				+ (getGroup2() == null ? 0 : this.getGroup2().hashCode());
		return result;
	}

}
