package com.mercon.entities;

// Generated Jul 29, 2013 11:52:05 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * VdimStorageId generated by hbm2java
 */
public class VdimStorageId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int numEquipment;
	private Integer numMot;
	private String codStorage;
	private String nameStorage;
	private Integer numLocation;
	private short indStatus;
	private Date dtLastModify;
	private int numLastModifyPerson;
	private String theirRef;
	private String ourRef;

	public VdimStorageId() {
	}

	public VdimStorageId(int numEquipment, String codStorage, short indStatus,
			Date dtLastModify, int numLastModifyPerson, String theirRef,
			String ourRef) {
		this.numEquipment = numEquipment;
		this.codStorage = codStorage;
		this.indStatus = indStatus;
		this.dtLastModify = dtLastModify;
		this.numLastModifyPerson = numLastModifyPerson;
		this.theirRef = theirRef;
		this.ourRef = ourRef;
	}

	public VdimStorageId(int numEquipment, Integer numMot, String codStorage,
			String nameStorage, Integer numLocation, short indStatus,
			Date dtLastModify, int numLastModifyPerson, String theirRef,
			String ourRef) {
		this.numEquipment = numEquipment;
		this.numMot = numMot;
		this.codStorage = codStorage;
		this.nameStorage = nameStorage;
		this.numLocation = numLocation;
		this.indStatus = indStatus;
		this.dtLastModify = dtLastModify;
		this.numLastModifyPerson = numLastModifyPerson;
		this.theirRef = theirRef;
		this.ourRef = ourRef;
	}

	public int getNumEquipment() {
		return this.numEquipment;
	}

	public void setNumEquipment(int numEquipment) {
		this.numEquipment = numEquipment;
	}

	public Integer getNumMot() {
		return this.numMot;
	}

	public void setNumMot(Integer numMot) {
		this.numMot = numMot;
	}

	public String getCodStorage() {
		return this.codStorage;
	}

	public void setCodStorage(String codStorage) {
		this.codStorage = codStorage;
	}

	public String getNameStorage() {
		return this.nameStorage;
	}

	public void setNameStorage(String nameStorage) {
		this.nameStorage = nameStorage;
	}

	public Integer getNumLocation() {
		return this.numLocation;
	}

	public void setNumLocation(Integer numLocation) {
		this.numLocation = numLocation;
	}

	public short getIndStatus() {
		return this.indStatus;
	}

	public void setIndStatus(short indStatus) {
		this.indStatus = indStatus;
	}

	public Date getDtLastModify() {
		return this.dtLastModify;
	}

	public void setDtLastModify(Date dtLastModify) {
		this.dtLastModify = dtLastModify;
	}

	public int getNumLastModifyPerson() {
		return this.numLastModifyPerson;
	}

	public void setNumLastModifyPerson(int numLastModifyPerson) {
		this.numLastModifyPerson = numLastModifyPerson;
	}

	public String getTheirRef() {
		return this.theirRef;
	}

	public void setTheirRef(String theirRef) {
		this.theirRef = theirRef;
	}

	public String getOurRef() {
		return this.ourRef;
	}

	public void setOurRef(String ourRef) {
		this.ourRef = ourRef;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VdimStorageId))
			return false;
		VdimStorageId castOther = (VdimStorageId) other;

		return (this.getNumEquipment() == castOther.getNumEquipment())
				&& ((this.getNumMot() == castOther.getNumMot()) || (this
						.getNumMot() != null && castOther.getNumMot() != null && this
						.getNumMot().equals(castOther.getNumMot())))
				&& ((this.getCodStorage() == castOther.getCodStorage()) || (this
						.getCodStorage() != null
						&& castOther.getCodStorage() != null && this
						.getCodStorage().equals(castOther.getCodStorage())))
				&& ((this.getNameStorage() == castOther.getNameStorage()) || (this
						.getNameStorage() != null
						&& castOther.getNameStorage() != null && this
						.getNameStorage().equals(castOther.getNameStorage())))
				&& ((this.getNumLocation() == castOther.getNumLocation()) || (this
						.getNumLocation() != null
						&& castOther.getNumLocation() != null && this
						.getNumLocation().equals(castOther.getNumLocation())))
				&& (this.getIndStatus() == castOther.getIndStatus())
				&& ((this.getDtLastModify() == castOther.getDtLastModify()) || (this
						.getDtLastModify() != null
						&& castOther.getDtLastModify() != null && this
						.getDtLastModify().equals(castOther.getDtLastModify())))
				&& (this.getNumLastModifyPerson() == castOther
						.getNumLastModifyPerson())
				&& ((this.getTheirRef() == castOther.getTheirRef()) || (this
						.getTheirRef() != null
						&& castOther.getTheirRef() != null && this
						.getTheirRef().equals(castOther.getTheirRef())))
				&& ((this.getOurRef() == castOther.getOurRef()) || (this
						.getOurRef() != null && castOther.getOurRef() != null && this
						.getOurRef().equals(castOther.getOurRef())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumEquipment();
		result = 37 * result
				+ (getNumMot() == null ? 0 : this.getNumMot().hashCode());
		result = 37
				* result
				+ (getCodStorage() == null ? 0 : this.getCodStorage()
						.hashCode());
		result = 37
				* result
				+ (getNameStorage() == null ? 0 : this.getNameStorage()
						.hashCode());
		result = 37
				* result
				+ (getNumLocation() == null ? 0 : this.getNumLocation()
						.hashCode());
		result = 37 * result + this.getIndStatus();
		result = 37
				* result
				+ (getDtLastModify() == null ? 0 : this.getDtLastModify()
						.hashCode());
		result = 37 * result + this.getNumLastModifyPerson();
		result = 37 * result
				+ (getTheirRef() == null ? 0 : this.getTheirRef().hashCode());
		result = 37 * result
				+ (getOurRef() == null ? 0 : this.getOurRef().hashCode());
		return result;
	}

}
