package com.mercon.entities;

// Generated 09-24-2012 03:30:27 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * VdimCurrencyId generated by hbm2java
 */
public class VdimCurrencyId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String codcurr;
	private String namecurr;
	private short indstatus;
	private Date dtlastmodiify;
	private int nummodifyperson;
	private int numlock;

	public VdimCurrencyId() {
	}

	public VdimCurrencyId(String codcurr, short indstatus, Date dtlastmodiify,
			int nummodifyperson, int numlock) {
		this.codcurr = codcurr;
		this.indstatus = indstatus;
		this.dtlastmodiify = dtlastmodiify;
		this.nummodifyperson = nummodifyperson;
		this.numlock = numlock;
	}

	public VdimCurrencyId(String codcurr, String namecurr, short indstatus,
			Date dtlastmodiify, int nummodifyperson, int numlock) {
		this.codcurr = codcurr;
		this.namecurr = namecurr;
		this.indstatus = indstatus;
		this.dtlastmodiify = dtlastmodiify;
		this.nummodifyperson = nummodifyperson;
		this.numlock = numlock;
	}

	public String getCodcurr() {
		return this.codcurr;
	}

	public void setCodcurr(String codcurr) {
		this.codcurr = codcurr;
	}

	public String getNamecurr() {
		return this.namecurr;
	}

	public void setNamecurr(String namecurr) {
		this.namecurr = namecurr;
	}

	public short getIndstatus() {
		return this.indstatus;
	}

	public void setIndstatus(short indstatus) {
		this.indstatus = indstatus;
	}

	public Date getDtlastmodiify() {
		return this.dtlastmodiify;
	}

	public void setDtlastmodiify(Date dtlastmodiify) {
		this.dtlastmodiify = dtlastmodiify;
	}

	public int getNummodifyperson() {
		return this.nummodifyperson;
	}

	public void setNummodifyperson(int nummodifyperson) {
		this.nummodifyperson = nummodifyperson;
	}

	public int getNumlock() {
		return this.numlock;
	}

	public void setNumlock(int numlock) {
		this.numlock = numlock;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VdimCurrencyId))
			return false;
		VdimCurrencyId castOther = (VdimCurrencyId) other;

		return ((this.getCodcurr() == castOther.getCodcurr()) || (this
				.getCodcurr() != null && castOther.getCodcurr() != null && this
				.getCodcurr().equals(castOther.getCodcurr())))
				&& ((this.getNamecurr() == castOther.getNamecurr()) || (this
						.getNamecurr() != null
						&& castOther.getNamecurr() != null && this
						.getNamecurr().equals(castOther.getNamecurr())))
				&& (this.getIndstatus() == castOther.getIndstatus())
				&& ((this.getDtlastmodiify() == castOther.getDtlastmodiify()) || (this
						.getDtlastmodiify() != null
						&& castOther.getDtlastmodiify() != null && this
						.getDtlastmodiify()
						.equals(castOther.getDtlastmodiify())))
				&& (this.getNummodifyperson() == castOther.getNummodifyperson())
				&& (this.getNumlock() == castOther.getNumlock());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodcurr() == null ? 0 : this.getCodcurr().hashCode());
		result = 37 * result
				+ (getNamecurr() == null ? 0 : this.getNamecurr().hashCode());
		result = 37 * result + this.getIndstatus();
		result = 37
				* result
				+ (getDtlastmodiify() == null ? 0 : this.getDtlastmodiify()
						.hashCode());
		result = 37 * result + this.getNummodifyperson();
		result = 37 * result + this.getNumlock();
		return result;
	}

}
