package com.mercon.entities;

// Generated Feb 3, 2014 9:23:28 AM by Hibernate Tools 3.4.0.CR1

/**
 * VdimCommodityStrategy generated by hbm2java
 */
public class VdimCommodityStrategy implements java.io.Serializable {

	/**
	 * Serial ID
	 */
	private static final long serialVersionUID = -7878124118601637837L;

	private VdimCommodityStrategyId id;

	public VdimCommodityStrategy() {
	}

	public VdimCommodityStrategy(VdimCommodityStrategyId id) {
		this.id = id;
	}

	public VdimCommodityStrategyId getId() {
		return this.id;
	}

	public void setId(VdimCommodityStrategyId id) {
		this.id = id;
	}

}
