package com.mercon.entities;

// Generated 09-24-2012 03:30:27 PM by Hibernate Tools 4.0.0

/**
 * VdimCurrency generated by hbm2java
 */
public class VdimCurrency implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private VdimCurrencyId id;

	public VdimCurrency() {
	}

	public VdimCurrency(VdimCurrencyId id) {
		this.id = id;
	}

	public VdimCurrencyId getId() {
		return this.id;
	}

	public void setId(VdimCurrencyId id) {
		this.id = id;
	}

}
