package com.mercon.entities;

// Generated Jul 29, 2013 11:52:05 AM by Hibernate Tools 3.4.0.CR1

/**
 * VdimStorage generated by hbm2java
 */
public class VdimStorage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private VdimStorageId id;

	public VdimStorage() {
	}

	public VdimStorage(VdimStorageId id) {
		this.id = id;
	}

	public VdimStorageId getId() {
		return this.id;
	}

	public void setId(VdimStorageId id) {
		this.id = id;
	}

}
