package com.mercon.entities;

// Generated Aug 5, 2013 10:22:16 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.validation.constraints.Digits;

/**
 * VdimCargoId generated by hbm2java
 */
public class VdimCargoId implements java.io.Serializable {

	/**
	 * Serial ID
	 */
	private static final long serialVersionUID = -8591924250642348871L;
	
	private Integer numCompany;
	private int numEquipment;
	private int numCargo;
	private String nameCargo;
	private short typCargo;
	private short typCargoValuation;
	private int numStategy;
	private VdimStrategyId numStrategy;
	private Integer numMtmcurve;
	private VdimMktQuoteDefinitionId mtmCurveNum;
	private int numBuildDraw;
	private String codStorageType;
	private String codCommodity;
	private VdimCommodityId commodityCod;
	private String codQtyUom;
	private VdimUnitOfMeasureId qtyUomCod;
	private String codPrcCur;
	private VdimCurrencyId currPriceCod;
	private String codPrcUom;
	private VdimUnitOfMeasureId prcUomCod;
	private String refExternal;
	private Date dtLastModify;
	private int numLastModifyPerson;
	private short statusInd;
	@Digits(integer = 15, fraction = 2)
	private BigDecimal capacity;

	public VdimCargoId() { }

	public Integer getNumCompany() {
		return this.numCompany;
	}

	public void setNumCompany(Integer numCompany) {
		this.numCompany = numCompany;
	}

	public int getNumEquipment() {
		return this.numEquipment;
	}

	public void setNumEquipment(int numEquipment) {
		this.numEquipment = numEquipment;
	}

	public int getNumCargo() {
		return this.numCargo;
	}

	public void setNumCargo(int numCargo) {
		this.numCargo = numCargo;
	}

	public String getNameCargo() {
		return this.nameCargo;
	}

	public void setNameCargo(String nameCargo) {
		this.nameCargo = nameCargo;
	}

	public short getTypCargo() {
		return this.typCargo;
	}

	public void setTypCargo(short typCargo) {
		this.typCargo = typCargo;
	}

	public short getTypCargoValuation() {
		return this.typCargoValuation;
	}

	public void setTypCargoValuation(short typCargoValuation) {
		this.typCargoValuation = typCargoValuation;
	}
	
	public int getNumStategy() {
		return numStategy;
	}

	public void setNumStategy(int numStategy) {
		this.numStategy = numStategy;
	}

	public VdimStrategyId getNumStrategy() {
		return this.numStrategy;
	}

	public void setNumStrategy(VdimStrategyId numStrategy) {
		this.numStrategy = numStrategy;
	}

	public Integer getNumMtmcurve() {
		return this.numMtmcurve;
	}

	public void setNumMtmcurve(Integer numMtmcurve) {
		this.numMtmcurve = numMtmcurve;
	}	
	
	public VdimMktQuoteDefinitionId getMtmCurveNum() {
		return mtmCurveNum;
	}

	public void setMtmCurveNum(VdimMktQuoteDefinitionId mtmCurveNum) {
		this.mtmCurveNum = mtmCurveNum;
	}

	public int getNumBuildDraw() {
		return this.numBuildDraw;
	}

	public void setNumBuildDraw(int numBuildDraw) {
		this.numBuildDraw = numBuildDraw;
	}

	public String getCodStorageType() {
		return this.codStorageType;
	}

	public void setCodStorageType(String codStorageType) {
		this.codStorageType = codStorageType;
	}

	public String getCodCommodity() {
		return codCommodity;
	}

	public void setCodCommodity(String codCommodity) {
		this.codCommodity = codCommodity;
	}

	public VdimCommodityId getCommodityCod() {
		return commodityCod;
	}

	public void setCommodityCod(VdimCommodityId commodityCod) {
		this.commodityCod = commodityCod;
	}

	public String getCodQtyUom() {
		return codQtyUom;
	}

	public void setCodQtyUom(String codQtyUom) {
		this.codQtyUom = codQtyUom;
	}

	public VdimUnitOfMeasureId getQtyUomCod() {
		return qtyUomCod;
	}

	public void setQtyUomCod(VdimUnitOfMeasureId qtyUomCod) {
		this.qtyUomCod = qtyUomCod;
	}

	public String getCodPrcCur() {
		return codPrcCur;
	}

	public void setCodPrcCur(String codPrcCur) {
		this.codPrcCur = codPrcCur;
	}

	public VdimCurrencyId getCurrPriceCod() {
		return currPriceCod;
	}

	public void setCurrPriceCod(VdimCurrencyId currPriceCod) {
		this.currPriceCod = currPriceCod;
	}

	public String getCodPrcUom() {
		return codPrcUom;
	}

	public void setCodPrcUom(String codPrcUom) {
		this.codPrcUom = codPrcUom;
	}

	public VdimUnitOfMeasureId getPrcUomCod() {
		return prcUomCod;
	}

	public void setPrcUomCod(VdimUnitOfMeasureId prcUomCod) {
		this.prcUomCod = prcUomCod;
	}

	public String getRefExternal() {
		return this.refExternal;
	}

	public void setRefExternal(String refExternal) {
		this.refExternal = refExternal;
	}

	public Date getDtLastModify() {
		return this.dtLastModify;
	}

	public void setDtLastModify(Date dtLastModify) {
		this.dtLastModify = dtLastModify;
	}

	public int getNumLastModifyPerson() {
		return this.numLastModifyPerson;
	}

	public void setNumLastModifyPerson(int numLastModifyPerson) {
		this.numLastModifyPerson = numLastModifyPerson;
	}

	public short getStatusInd() {
		return this.statusInd;
	}

	public void setStatusInd(short statusInd) {
		this.statusInd = statusInd;
	}
	
	public BigDecimal getCapacity() {
		return capacity;
	}

	public void setCapacity(BigDecimal capacity) {
		this.capacity = capacity;
	}

}
