package com.mercon.entities;

// Generated Aug 7, 2014 12:10:45 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.faces.event.ActionEvent;
import javax.persistence.Transient;

import com.mercon.beans.ItineraryBean;
import com.mercon.util.DefaultConstants;

/**
 * VdimTransferId generated by hbm2java
 */
public class VdimTransferId implements java.io.Serializable {

	/**
	 * Serial ID
	 */
	private static final long serialVersionUID = 5671571177623176510L;
	
	private ItineraryBean itinerary;
	
	private int numTransfer;
	private short indLoadDischarge;
	private VgenIndicatorId loadDischargeObj;
	private short indFromType;
	private VgenIndicatorId fromTypeObj;
	private int numFromItinerary;
	private int numFromEquipment;
	private int numFromCargo;
	private BigDecimal qtyFrom;
	private String codFromUom;
	private short indToType;
	private VgenIndicatorId toTypeObj;
	private int numToItinerary;
	private int numToEquipment;
	private int numToCargo;
	private BigDecimal qtyTo;
	private String codToUom;
	private Integer numLocation;
	private VdimLocationId locationObj;
	private BigDecimal factUomConv;
	private short indUomConvFactor;
	private BigDecimal qtyGainLoss;
	private int numBuild;
	private int numDraw;
	private int numAdjustmentBd;
	private BigDecimal prcTransfer;
	private String codTransferPriceCurr;
	private String codTransferPriceUom;
	private short indTransferPriceStatus;
	private Date dtTransferComm;
	private Date dtTransferComp;
	private short indTransferAt;
	private VgenIndicatorId transferAtObj;
	private BigDecimal qtyTradeSched;
	private BigDecimal qtyTradeInvoice;
	private String codTradeInvoiceUom;
	private short indDeliveryStatus;
	private Date dtApplication;
	private Date dtEffective;
	private Integer numObligation;
	private String refExternal;
	private BigDecimal qtyFromPackaging;
	private BigDecimal qtyToPackaging;
	private String uomFromPackaging;
	private String uomToPackaging;
	private Date dtFromCargoReset;
	private Date dtToCargoReset;
	private Date dtFinalizaed;
	private int numTxlTransfer;
	private Short indImportType;
	private int numNote;
	private Date dtLastModify;
	private int numModifyPerson;
	private int numLock;
	private int numLiftingStrategy;
	private String codVenture;
	private short indHasAttachment;
	private int numOperatorPerson;
	private int numTransferLink;
	private short indTransferLinkType;
	private short indCustomsDutyStatus;
	private short indFromCustomsDutyStatus;
	private short indToCustomsDutyStatus;
	private String codBlNum;
	private Date dtBl;
	private Short indDeliveryActiveStatus;
	private Date dtLiquidate;
	private Short indMotType;
	private int numReceiptLocation;
	private int numDeliveryLocation;
	private int numInventory;
	private int numBatch;
	private String idBatchLevel;
	private String idFromBatch;
	private String idToBatch;
	private Date dtDelivery;
	private short indDeliveryDtMtm;
	private String comments;
	private short indTransferSplit;
	private int numParentTransfer;
	private int numCompany;
	private int numPath;
	private short indAddTariffCost;
	private Short indTransferState;
	private Integer numToStrategy;
	private Integer numFromStrategy;

	private List<VbuildDrawTagId> tagLst = new ArrayList<VbuildDrawTagId>();
	private VbuildDrawTagId buildDrawTagId;

	@Transient
	private String locationIdentifier;
	
	@Transient
	private BigDecimal tagQty;
	
	@Transient
	private BigDecimal tagAllocQty;
	
	public VdimTransferId() {
	}

	public VdimTransferId(int numTransfer, short indFromType,
			int numFromItinerary, int numFromEquipment, int numFromCargo,
			short indToType, int numToItinerary, int numToEquipment,
			int numToCargo, short indUomConvFactor, BigDecimal qtyGainLoss,
			int numBuild, int numDraw, int numAdjustmentBd,
			BigDecimal prcTransfer, String codTransferPriceCurr,
			String codTransferPriceUom, short indTransferPriceStatus,
			short indTransferAt, BigDecimal qtyTradeInvoice,
			short indDeliveryStatus, String refExternal,
			BigDecimal qtyFromPackaging, BigDecimal qtyToPackaging,
			String uomFromPackaging, String uomToPackaging,
			Date dtFromCargoReset, Date dtToCargoReset, Date dtFinalizaed,
			int numTxlTransfer, int numNote, Date dtLastModify,
			int numModifyPerson, int numLock, int numLiftingStrategy,
			String codVenture, short indHasAttachment, int numOperatorPerson,
			int numTransferLink, short indTransferLinkType,
			short indCustomsDutyStatus, short indFromCustomsDutyStatus,
			short indToCustomsDutyStatus, String codBlNum, Date dtLiquidate,
			int numReceiptLocation, int numDeliveryLocation, int numInventory,
			int numBatch, String idBatchLevel, String idFromBatch,
			String idToBatch, Date dtDelivery, short indDeliveryDtMtm,
			String comments, short indTransferSplit, int numParentTransfer,
			int numCompany, int numPath, short indAddTariffCost) {
		this.numTransfer = numTransfer;
		this.indFromType = indFromType;
		this.numFromItinerary = numFromItinerary;
		this.numFromEquipment = numFromEquipment;
		this.numFromCargo = numFromCargo;
		this.indToType = indToType;
		this.numToItinerary = numToItinerary;
		this.numToEquipment = numToEquipment;
		this.numToCargo = numToCargo;
		this.indUomConvFactor = indUomConvFactor;
		this.qtyGainLoss = qtyGainLoss;
		this.numBuild = numBuild;
		this.numDraw = numDraw;
		this.numAdjustmentBd = numAdjustmentBd;
		this.prcTransfer = prcTransfer;
		this.codTransferPriceCurr = codTransferPriceCurr;
		this.codTransferPriceUom = codTransferPriceUom;
		this.indTransferPriceStatus = indTransferPriceStatus;
		this.indTransferAt = indTransferAt;
		this.qtyTradeInvoice = qtyTradeInvoice;
		this.indDeliveryStatus = indDeliveryStatus;
		this.refExternal = refExternal;
		this.qtyFromPackaging = qtyFromPackaging;
		this.qtyToPackaging = qtyToPackaging;
		this.uomFromPackaging = uomFromPackaging;
		this.uomToPackaging = uomToPackaging;
		this.dtFromCargoReset = dtFromCargoReset;
		this.dtToCargoReset = dtToCargoReset;
		this.dtFinalizaed = dtFinalizaed;
		this.numTxlTransfer = numTxlTransfer;
		this.numNote = numNote;
		this.dtLastModify = dtLastModify;
		this.numModifyPerson = numModifyPerson;
		this.numLock = numLock;
		this.numLiftingStrategy = numLiftingStrategy;
		this.codVenture = codVenture;
		this.indHasAttachment = indHasAttachment;
		this.numOperatorPerson = numOperatorPerson;
		this.numTransferLink = numTransferLink;
		this.indTransferLinkType = indTransferLinkType;
		this.indCustomsDutyStatus = indCustomsDutyStatus;
		this.indFromCustomsDutyStatus = indFromCustomsDutyStatus;
		this.indToCustomsDutyStatus = indToCustomsDutyStatus;
		this.codBlNum = codBlNum;
		this.dtLiquidate = dtLiquidate;
		this.numReceiptLocation = numReceiptLocation;
		this.numDeliveryLocation = numDeliveryLocation;
		this.numInventory = numInventory;
		this.numBatch = numBatch;
		this.idBatchLevel = idBatchLevel;
		this.idFromBatch = idFromBatch;
		this.idToBatch = idToBatch;
		this.dtDelivery = dtDelivery;
		this.indDeliveryDtMtm = indDeliveryDtMtm;
		this.comments = comments;
		this.indTransferSplit = indTransferSplit;
		this.numParentTransfer = numParentTransfer;
		this.numCompany = numCompany;
		this.numPath = numPath;
		this.indAddTariffCost = indAddTariffCost;
	}

	public VdimTransferId(int numTransfer, short indFromType,
			int numFromItinerary, int numFromEquipment, int numFromCargo,
			BigDecimal qtyFrom, String codFromUom, short indToType,
			int numToItinerary, int numToEquipment, int numToCargo,
			BigDecimal qtyTo, String codToUom, Integer numLocation,
			BigDecimal factUomConv, short indUomConvFactor,
			BigDecimal qtyGainLoss, int numBuild, int numDraw,
			int numAdjustmentBd, BigDecimal prcTransfer,
			String codTransferPriceCurr, String codTransferPriceUom,
			short indTransferPriceStatus, Date dtTransferComm,
			Date dtTransferComp, short indTransferAt, BigDecimal qtyTradeSched,
			BigDecimal qtyTradeInvoice, String codTradeInvoiceUom,
			short indDeliveryStatus, Date dtApplication, Date dtEffective,
			Integer numObligation, String refExternal,
			BigDecimal qtyFromPackaging, BigDecimal qtyToPackaging,
			String uomFromPackaging, String uomToPackaging,
			Date dtFromCargoReset, Date dtToCargoReset, Date dtFinalizaed,
			int numTxlTransfer, Short indImportType, int numNote,
			Date dtLastModify, int numModifyPerson, int numLock,
			int numLiftingStrategy, String codVenture, short indHasAttachment,
			int numOperatorPerson, int numTransferLink,
			short indTransferLinkType, short indCustomsDutyStatus,
			short indFromCustomsDutyStatus, short indToCustomsDutyStatus,
			String codBlNum, Date dtBl, Short indDeliveryActiveStatus,
			Date dtLiquidate, Short indMotType, int numReceiptLocation,
			int numDeliveryLocation, int numInventory, int numBatch,
			String idBatchLevel, String idFromBatch, String idToBatch,
			Date dtDelivery, short indDeliveryDtMtm, String comments,
			short indTransferSplit, int numParentTransfer, int numCompany,
			int numPath, short indAddTariffCost, Short indTransferState,
			Integer numToStrategy, Integer numFromStrategy) {
		this.numTransfer = numTransfer;
		this.indFromType = indFromType;
		this.numFromItinerary = numFromItinerary;
		this.numFromEquipment = numFromEquipment;
		this.numFromCargo = numFromCargo;
		this.qtyFrom = qtyFrom;
		this.codFromUom = codFromUom;
		this.indToType = indToType;
		this.numToItinerary = numToItinerary;
		this.numToEquipment = numToEquipment;
		this.numToCargo = numToCargo;
		this.qtyTo = qtyTo;
		this.codToUom = codToUom;
		this.numLocation = numLocation;
		this.factUomConv = factUomConv;
		this.indUomConvFactor = indUomConvFactor;
		this.qtyGainLoss = qtyGainLoss;
		this.numBuild = numBuild;
		this.numDraw = numDraw;
		this.numAdjustmentBd = numAdjustmentBd;
		this.prcTransfer = prcTransfer;
		this.codTransferPriceCurr = codTransferPriceCurr;
		this.codTransferPriceUom = codTransferPriceUom;
		this.indTransferPriceStatus = indTransferPriceStatus;
		this.dtTransferComm = dtTransferComm;
		this.dtTransferComp = dtTransferComp;
		this.indTransferAt = indTransferAt;
		this.qtyTradeSched = qtyTradeSched;
		this.qtyTradeInvoice = qtyTradeInvoice;
		this.codTradeInvoiceUom = codTradeInvoiceUom;
		this.indDeliveryStatus = indDeliveryStatus;
		this.dtApplication = dtApplication;
		this.dtEffective = dtEffective;
		this.numObligation = numObligation;
		this.refExternal = refExternal;
		this.qtyFromPackaging = qtyFromPackaging;
		this.qtyToPackaging = qtyToPackaging;
		this.uomFromPackaging = uomFromPackaging;
		this.uomToPackaging = uomToPackaging;
		this.dtFromCargoReset = dtFromCargoReset;
		this.dtToCargoReset = dtToCargoReset;
		this.dtFinalizaed = dtFinalizaed;
		this.numTxlTransfer = numTxlTransfer;
		this.indImportType = indImportType;
		this.numNote = numNote;
		this.dtLastModify = dtLastModify;
		this.numModifyPerson = numModifyPerson;
		this.numLock = numLock;
		this.numLiftingStrategy = numLiftingStrategy;
		this.codVenture = codVenture;
		this.indHasAttachment = indHasAttachment;
		this.numOperatorPerson = numOperatorPerson;
		this.numTransferLink = numTransferLink;
		this.indTransferLinkType = indTransferLinkType;
		this.indCustomsDutyStatus = indCustomsDutyStatus;
		this.indFromCustomsDutyStatus = indFromCustomsDutyStatus;
		this.indToCustomsDutyStatus = indToCustomsDutyStatus;
		this.codBlNum = codBlNum;
		this.dtBl = dtBl;
		this.indDeliveryActiveStatus = indDeliveryActiveStatus;
		this.dtLiquidate = dtLiquidate;
		this.indMotType = indMotType;
		this.numReceiptLocation = numReceiptLocation;
		this.numDeliveryLocation = numDeliveryLocation;
		this.numInventory = numInventory;
		this.numBatch = numBatch;
		this.idBatchLevel = idBatchLevel;
		this.idFromBatch = idFromBatch;
		this.idToBatch = idToBatch;
		this.dtDelivery = dtDelivery;
		this.indDeliveryDtMtm = indDeliveryDtMtm;
		this.comments = comments;
		this.indTransferSplit = indTransferSplit;
		this.numParentTransfer = numParentTransfer;
		this.numCompany = numCompany;
		this.numPath = numPath;
		this.indAddTariffCost = indAddTariffCost;
		this.indTransferState = indTransferState;
		this.numToStrategy = numToStrategy;
		this.numFromStrategy = numFromStrategy;
	}
	
	public ItineraryBean getItinerary() {
		return itinerary;
	}

	public void setItinerary(ItineraryBean itinerary) {
		this.itinerary = itinerary;
	}

	public void addTag(ActionEvent actionEvent) {
		VbuildDrawTagId buildDrawTagId = new VbuildDrawTagId();
		
		buildDrawTagId.setTagTypeCd(DefaultConstants.C_CHOP_DATA);
		buildDrawTagId.setChopId(this.itinerary.getTradeInputId().getTradeNum() + "-1-1");
		buildDrawTagId.setTagQty(0d);
		buildDrawTagId.setTagQtyUomCd(this.itinerary.getTradeInputId().getContractUomCd());
		
		tagLst.add(buildDrawTagId);
	}
	
	public void removeTag(VbuildDrawTagId buildDrawTagId) {
		if (buildDrawTagId != null) {
			this.tagLst.remove(buildDrawTagId);
		}
	}
	
	public int getNumTransfer() {
		return this.numTransfer;
	}

	public void setNumTransfer(int numTransfer) {
		this.numTransfer = numTransfer;
	}
	
	public short getIndLoadDischarge() {
		return indLoadDischarge;
	}

	public void setIndLoadDischarge(short indLoadDischarge) {
		this.indLoadDischarge = indLoadDischarge;
	}

	public VgenIndicatorId getLoadDischargeObj() {
		return loadDischargeObj;
	}

	public void setLoadDischargeObj(VgenIndicatorId loadDischargeObj) {
		this.loadDischargeObj = loadDischargeObj;
	}

	public short getIndFromType() {
		return this.indFromType;
	}

	public void setIndFromType(short indFromType) {
		this.indFromType = indFromType;
	}
	
	public VgenIndicatorId getFromTypeObj() {
		return fromTypeObj;
	}

	public void setFromTypeObj(VgenIndicatorId fromTypeObj) {
		this.fromTypeObj = fromTypeObj;
	}

	public int getNumFromItinerary() {
		return this.numFromItinerary;
	}

	public void setNumFromItinerary(int numFromItinerary) {
		this.numFromItinerary = numFromItinerary;
	}

	public int getNumFromEquipment() {
		return this.numFromEquipment;
	}

	public void setNumFromEquipment(int numFromEquipment) {
		this.numFromEquipment = numFromEquipment;
	}

	public int getNumFromCargo() {
		return this.numFromCargo;
	}

	public void setNumFromCargo(int numFromCargo) {
		this.numFromCargo = numFromCargo;
	}

	public BigDecimal getQtyFrom() {
		return this.qtyFrom;
	}

	public void setQtyFrom(BigDecimal qtyFrom) {
		this.qtyFrom = qtyFrom;
	}

	public String getCodFromUom() {
		return this.codFromUom;
	}

	public void setCodFromUom(String codFromUom) {
		this.codFromUom = codFromUom;
	}

	public short getIndToType() {
		return this.indToType;
	}

	public void setIndToType(short indToType) {
		this.indToType = indToType;
	}
	
	public VgenIndicatorId getToTypeObj() {
		return toTypeObj;
	}

	public void setToTypeObj(VgenIndicatorId toTypeObj) {
		this.toTypeObj = toTypeObj;
	}

	public int getNumToItinerary() {
		return this.numToItinerary;
	}

	public void setNumToItinerary(int numToItinerary) {
		this.numToItinerary = numToItinerary;
	}

	public int getNumToEquipment() {
		return this.numToEquipment;
	}

	public void setNumToEquipment(int numToEquipment) {
		this.numToEquipment = numToEquipment;
	}

	public int getNumToCargo() {
		return this.numToCargo;
	}

	public void setNumToCargo(int numToCargo) {
		this.numToCargo = numToCargo;
	}

	public BigDecimal getQtyTo() {
		return this.qtyTo;
	}

	public void setQtyTo(BigDecimal qtyTo) {
		this.qtyTo = qtyTo;
	}

	public String getCodToUom() {
		return this.codToUom;
	}

	public void setCodToUom(String codToUom) {
		this.codToUom = codToUom;
	}

	public Integer getNumLocation() {
		return this.numLocation;
	}

	public void setNumLocation(Integer numLocation) {
		this.numLocation = numLocation;
	}
	
	public VdimLocationId getLocationObj() {
		return locationObj;
	}

	public void setLocationObj(VdimLocationId locationObj) {
		this.locationObj = locationObj;
	}

	public BigDecimal getFactUomConv() {
		return this.factUomConv;
	}

	public void setFactUomConv(BigDecimal factUomConv) {
		this.factUomConv = factUomConv;
	}

	public short getIndUomConvFactor() {
		return this.indUomConvFactor;
	}

	public void setIndUomConvFactor(short indUomConvFactor) {
		this.indUomConvFactor = indUomConvFactor;
	}

	public BigDecimal getQtyGainLoss() {
		return this.qtyGainLoss;
	}

	public void setQtyGainLoss(BigDecimal qtyGainLoss) {
		this.qtyGainLoss = qtyGainLoss;
	}

	public int getNumBuild() {
		return this.numBuild;
	}

	public void setNumBuild(int numBuild) {
		this.numBuild = numBuild;
	}

	public int getNumDraw() {
		return this.numDraw;
	}

	public void setNumDraw(int numDraw) {
		this.numDraw = numDraw;
	}

	public int getNumAdjustmentBd() {
		return this.numAdjustmentBd;
	}

	public void setNumAdjustmentBd(int numAdjustmentBd) {
		this.numAdjustmentBd = numAdjustmentBd;
	}

	public BigDecimal getPrcTransfer() {
		return this.prcTransfer;
	}

	public void setPrcTransfer(BigDecimal prcTransfer) {
		this.prcTransfer = prcTransfer;
	}

	public String getCodTransferPriceCurr() {
		return this.codTransferPriceCurr;
	}

	public void setCodTransferPriceCurr(String codTransferPriceCurr) {
		this.codTransferPriceCurr = codTransferPriceCurr;
	}

	public String getCodTransferPriceUom() {
		return this.codTransferPriceUom;
	}

	public void setCodTransferPriceUom(String codTransferPriceUom) {
		this.codTransferPriceUom = codTransferPriceUom;
	}

	public short getIndTransferPriceStatus() {
		return this.indTransferPriceStatus;
	}

	public void setIndTransferPriceStatus(short indTransferPriceStatus) {
		this.indTransferPriceStatus = indTransferPriceStatus;
	}

	public Date getDtTransferComm() {
		return this.dtTransferComm;
	}

	public void setDtTransferComm(Date dtTransferComm) {
		this.dtTransferComm = dtTransferComm;
	}

	public Date getDtTransferComp() {
		return this.dtTransferComp;
	}

	public void setDtTransferComp(Date dtTransferComp) {
		this.dtTransferComp = dtTransferComp;
	}

	public short getIndTransferAt() {
		return this.indTransferAt;
	}

	public void setIndTransferAt(short indTransferAt) {
		this.indTransferAt = indTransferAt;
	}
	
	public VgenIndicatorId getTransferAtObj() {
		return transferAtObj;
	}

	public void setTransferAtObj(VgenIndicatorId transferAtObj) {
		this.transferAtObj = transferAtObj;
	}

	public BigDecimal getQtyTradeSched() {
		return this.qtyTradeSched;
	}

	public void setQtyTradeSched(BigDecimal qtyTradeSched) {
		this.qtyTradeSched = qtyTradeSched;
	}

	public BigDecimal getQtyTradeInvoice() {
		return this.qtyTradeInvoice;
	}

	public void setQtyTradeInvoice(BigDecimal qtyTradeInvoice) {
		this.qtyTradeInvoice = qtyTradeInvoice;
	}

	public String getCodTradeInvoiceUom() {
		return this.codTradeInvoiceUom;
	}

	public void setCodTradeInvoiceUom(String codTradeInvoiceUom) {
		this.codTradeInvoiceUom = codTradeInvoiceUom;
	}

	public short getIndDeliveryStatus() {
		return this.indDeliveryStatus;
	}

	public void setIndDeliveryStatus(short indDeliveryStatus) {
		this.indDeliveryStatus = indDeliveryStatus;
	}

	public Date getDtApplication() {
		return this.dtApplication;
	}

	public void setDtApplication(Date dtApplication) {
		this.dtApplication = dtApplication;
	}

	public Date getDtEffective() {
		return this.dtEffective;
	}

	public void setDtEffective(Date dtEffective) {
		this.dtEffective = dtEffective;
	}

	public Integer getNumObligation() {
		return this.numObligation;
	}

	public void setNumObligation(Integer numObligation) {
		this.numObligation = numObligation;
	}

	public String getRefExternal() {
		return this.refExternal;
	}

	public void setRefExternal(String refExternal) {
		this.refExternal = refExternal;
	}

	public BigDecimal getQtyFromPackaging() {
		return this.qtyFromPackaging;
	}

	public void setQtyFromPackaging(BigDecimal qtyFromPackaging) {
		this.qtyFromPackaging = qtyFromPackaging;
	}

	public BigDecimal getQtyToPackaging() {
		return this.qtyToPackaging;
	}

	public void setQtyToPackaging(BigDecimal qtyToPackaging) {
		this.qtyToPackaging = qtyToPackaging;
	}

	public String getUomFromPackaging() {
		return this.uomFromPackaging;
	}

	public void setUomFromPackaging(String uomFromPackaging) {
		this.uomFromPackaging = uomFromPackaging;
	}

	public String getUomToPackaging() {
		return this.uomToPackaging;
	}

	public void setUomToPackaging(String uomToPackaging) {
		this.uomToPackaging = uomToPackaging;
	}

	public Date getDtFromCargoReset() {
		return this.dtFromCargoReset;
	}

	public void setDtFromCargoReset(Date dtFromCargoReset) {
		this.dtFromCargoReset = dtFromCargoReset;
	}

	public Date getDtToCargoReset() {
		return this.dtToCargoReset;
	}

	public void setDtToCargoReset(Date dtToCargoReset) {
		this.dtToCargoReset = dtToCargoReset;
	}

	public Date getDtFinalizaed() {
		return this.dtFinalizaed;
	}

	public void setDtFinalizaed(Date dtFinalizaed) {
		this.dtFinalizaed = dtFinalizaed;
	}

	public int getNumTxlTransfer() {
		return this.numTxlTransfer;
	}

	public void setNumTxlTransfer(int numTxlTransfer) {
		this.numTxlTransfer = numTxlTransfer;
	}

	public Short getIndImportType() {
		return this.indImportType;
	}

	public void setIndImportType(Short indImportType) {
		this.indImportType = indImportType;
	}

	public int getNumNote() {
		return this.numNote;
	}

	public void setNumNote(int numNote) {
		this.numNote = numNote;
	}

	public Date getDtLastModify() {
		return this.dtLastModify;
	}

	public void setDtLastModify(Date dtLastModify) {
		this.dtLastModify = dtLastModify;
	}

	public int getNumModifyPerson() {
		return this.numModifyPerson;
	}

	public void setNumModifyPerson(int numModifyPerson) {
		this.numModifyPerson = numModifyPerson;
	}

	public int getNumLock() {
		return this.numLock;
	}

	public void setNumLock(int numLock) {
		this.numLock = numLock;
	}

	public int getNumLiftingStrategy() {
		return this.numLiftingStrategy;
	}

	public void setNumLiftingStrategy(int numLiftingStrategy) {
		this.numLiftingStrategy = numLiftingStrategy;
	}

	public String getCodVenture() {
		return this.codVenture;
	}

	public void setCodVenture(String codVenture) {
		this.codVenture = codVenture;
	}

	public short getIndHasAttachment() {
		return this.indHasAttachment;
	}

	public void setIndHasAttachment(short indHasAttachment) {
		this.indHasAttachment = indHasAttachment;
	}

	public int getNumOperatorPerson() {
		return this.numOperatorPerson;
	}

	public void setNumOperatorPerson(int numOperatorPerson) {
		this.numOperatorPerson = numOperatorPerson;
	}

	public int getNumTransferLink() {
		return this.numTransferLink;
	}

	public void setNumTransferLink(int numTransferLink) {
		this.numTransferLink = numTransferLink;
	}

	public short getIndTransferLinkType() {
		return this.indTransferLinkType;
	}

	public void setIndTransferLinkType(short indTransferLinkType) {
		this.indTransferLinkType = indTransferLinkType;
	}

	public short getIndCustomsDutyStatus() {
		return this.indCustomsDutyStatus;
	}

	public void setIndCustomsDutyStatus(short indCustomsDutyStatus) {
		this.indCustomsDutyStatus = indCustomsDutyStatus;
	}

	public short getIndFromCustomsDutyStatus() {
		return this.indFromCustomsDutyStatus;
	}

	public void setIndFromCustomsDutyStatus(short indFromCustomsDutyStatus) {
		this.indFromCustomsDutyStatus = indFromCustomsDutyStatus;
	}

	public short getIndToCustomsDutyStatus() {
		return this.indToCustomsDutyStatus;
	}

	public void setIndToCustomsDutyStatus(short indToCustomsDutyStatus) {
		this.indToCustomsDutyStatus = indToCustomsDutyStatus;
	}

	public String getCodBlNum() {
		return this.codBlNum;
	}

	public void setCodBlNum(String codBlNum) {
		this.codBlNum = codBlNum;
	}

	public Date getDtBl() {
		return this.dtBl;
	}

	public void setDtBl(Date dtBl) {
		this.dtBl = dtBl;
	}

	public Short getIndDeliveryActiveStatus() {
		return this.indDeliveryActiveStatus;
	}

	public void setIndDeliveryActiveStatus(Short indDeliveryActiveStatus) {
		this.indDeliveryActiveStatus = indDeliveryActiveStatus;
	}

	public Date getDtLiquidate() {
		return this.dtLiquidate;
	}

	public void setDtLiquidate(Date dtLiquidate) {
		this.dtLiquidate = dtLiquidate;
	}

	public Short getIndMotType() {
		return this.indMotType;
	}

	public void setIndMotType(Short indMotType) {
		this.indMotType = indMotType;
	}

	public int getNumReceiptLocation() {
		return this.numReceiptLocation;
	}

	public void setNumReceiptLocation(int numReceiptLocation) {
		this.numReceiptLocation = numReceiptLocation;
	}

	public int getNumDeliveryLocation() {
		return this.numDeliveryLocation;
	}

	public void setNumDeliveryLocation(int numDeliveryLocation) {
		this.numDeliveryLocation = numDeliveryLocation;
	}

	public int getNumInventory() {
		return this.numInventory;
	}

	public void setNumInventory(int numInventory) {
		this.numInventory = numInventory;
	}

	public int getNumBatch() {
		return this.numBatch;
	}

	public void setNumBatch(int numBatch) {
		this.numBatch = numBatch;
	}

	public String getIdBatchLevel() {
		return this.idBatchLevel;
	}

	public void setIdBatchLevel(String idBatchLevel) {
		this.idBatchLevel = idBatchLevel;
	}

	public String getIdFromBatch() {
		return this.idFromBatch;
	}

	public void setIdFromBatch(String idFromBatch) {
		this.idFromBatch = idFromBatch;
	}

	public String getIdToBatch() {
		return this.idToBatch;
	}

	public void setIdToBatch(String idToBatch) {
		this.idToBatch = idToBatch;
	}

	public Date getDtDelivery() {
		return this.dtDelivery;
	}

	public void setDtDelivery(Date dtDelivery) {
		this.dtDelivery = dtDelivery;
	}

	public short getIndDeliveryDtMtm() {
		return this.indDeliveryDtMtm;
	}

	public void setIndDeliveryDtMtm(short indDeliveryDtMtm) {
		this.indDeliveryDtMtm = indDeliveryDtMtm;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public short getIndTransferSplit() {
		return this.indTransferSplit;
	}

	public void setIndTransferSplit(short indTransferSplit) {
		this.indTransferSplit = indTransferSplit;
	}

	public int getNumParentTransfer() {
		return this.numParentTransfer;
	}

	public void setNumParentTransfer(int numParentTransfer) {
		this.numParentTransfer = numParentTransfer;
	}

	public int getNumCompany() {
		return this.numCompany;
	}

	public void setNumCompany(int numCompany) {
		this.numCompany = numCompany;
	}

	public int getNumPath() {
		return this.numPath;
	}

	public void setNumPath(int numPath) {
		this.numPath = numPath;
	}

	public short getIndAddTariffCost() {
		return this.indAddTariffCost;
	}

	public void setIndAddTariffCost(short indAddTariffCost) {
		this.indAddTariffCost = indAddTariffCost;
	}

	public Short getIndTransferState() {
		return this.indTransferState;
	}

	public void setIndTransferState(Short indTransferState) {
		this.indTransferState = indTransferState;
	}

	public Integer getNumToStrategy() {
		return this.numToStrategy;
	}

	public void setNumToStrategy(Integer numToStrategy) {
		this.numToStrategy = numToStrategy;
	}

	public Integer getNumFromStrategy() {
		return this.numFromStrategy;
	}

	public void setNumFromStrategy(Integer numFromStrategy) {
		this.numFromStrategy = numFromStrategy;
	}
	
	public List<VbuildDrawTagId> getTagLst() {
		return tagLst;
	}

	public void setTagLst(List<VbuildDrawTagId> tagLst) {
		this.tagLst = tagLst;
	}
	
	public VbuildDrawTagId getBuildDrawTagId() {
		return buildDrawTagId;
	}

	public void setBuildDrawTagId(VbuildDrawTagId buildDrawTagId) {
		this.buildDrawTagId = buildDrawTagId;
	}
	
	@Transient
	public String getLocationIdentifier() {
		return locationIdentifier;
	}

	@Transient
	public void setLocationIdentifier(String locationIdentifier) {
		this.locationIdentifier = locationIdentifier;
	}

	@Transient
	public BigDecimal getTagQty() {
		return tagQty;
	}

	@Transient
	public void setTagQty(BigDecimal tagQty) {
		this.tagQty = tagQty;
	}

	@Transient
	public BigDecimal getTagAllocQty() {
		return tagAllocQty;
	}

	@Transient
	public void setTagAllocQty(BigDecimal tagAllocQty) {
		this.tagAllocQty = tagAllocQty;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VdimTransferId))
			return false;
		VdimTransferId castOther = (VdimTransferId) other;

		return (this.getNumTransfer() == castOther.getNumTransfer())
				&& (this.getIndFromType() == castOther.getIndFromType())
				&& (this.getNumFromItinerary() == castOther
						.getNumFromItinerary())
				&& (this.getNumFromEquipment() == castOther
						.getNumFromEquipment())
				&& (this.getNumFromCargo() == castOther.getNumFromCargo())
				&& ((this.getQtyFrom() == castOther.getQtyFrom()) || (this
						.getQtyFrom() != null && castOther.getQtyFrom() != null && this
						.getQtyFrom().equals(castOther.getQtyFrom())))
				&& ((this.getCodFromUom() == castOther.getCodFromUom()) || (this
						.getCodFromUom() != null
						&& castOther.getCodFromUom() != null && this
						.getCodFromUom().equals(castOther.getCodFromUom())))
				&& (this.getIndToType() == castOther.getIndToType())
				&& (this.getNumToItinerary() == castOther.getNumToItinerary())
				&& (this.getNumToEquipment() == castOther.getNumToEquipment())
				&& (this.getNumToCargo() == castOther.getNumToCargo())
				&& ((this.getQtyTo() == castOther.getQtyTo()) || (this
						.getQtyTo() != null && castOther.getQtyTo() != null && this
						.getQtyTo().equals(castOther.getQtyTo())))
				&& ((this.getCodToUom() == castOther.getCodToUom()) || (this
						.getCodToUom() != null
						&& castOther.getCodToUom() != null && this
						.getCodToUom().equals(castOther.getCodToUom())))
				&& ((this.getNumLocation() == castOther.getNumLocation()) || (this
						.getNumLocation() != null
						&& castOther.getNumLocation() != null && this
						.getNumLocation().equals(castOther.getNumLocation())))
				&& ((this.getFactUomConv() == castOther.getFactUomConv()) || (this
						.getFactUomConv() != null
						&& castOther.getFactUomConv() != null && this
						.getFactUomConv().equals(castOther.getFactUomConv())))
				&& (this.getIndUomConvFactor() == castOther
						.getIndUomConvFactor())
				&& ((this.getQtyGainLoss() == castOther.getQtyGainLoss()) || (this
						.getQtyGainLoss() != null
						&& castOther.getQtyGainLoss() != null && this
						.getQtyGainLoss().equals(castOther.getQtyGainLoss())))
				&& (this.getNumBuild() == castOther.getNumBuild())
				&& (this.getNumDraw() == castOther.getNumDraw())
				&& (this.getNumAdjustmentBd() == castOther.getNumAdjustmentBd())
				&& ((this.getPrcTransfer() == castOther.getPrcTransfer()) || (this
						.getPrcTransfer() != null
						&& castOther.getPrcTransfer() != null && this
						.getPrcTransfer().equals(castOther.getPrcTransfer())))
				&& ((this.getCodTransferPriceCurr() == castOther
						.getCodTransferPriceCurr()) || (this
						.getCodTransferPriceCurr() != null
						&& castOther.getCodTransferPriceCurr() != null && this
						.getCodTransferPriceCurr().equals(
								castOther.getCodTransferPriceCurr())))
				&& ((this.getCodTransferPriceUom() == castOther
						.getCodTransferPriceUom()) || (this
						.getCodTransferPriceUom() != null
						&& castOther.getCodTransferPriceUom() != null && this
						.getCodTransferPriceUom().equals(
								castOther.getCodTransferPriceUom())))
				&& (this.getIndTransferPriceStatus() == castOther
						.getIndTransferPriceStatus())
				&& ((this.getDtTransferComm() == castOther.getDtTransferComm()) || (this
						.getDtTransferComm() != null
						&& castOther.getDtTransferComm() != null && this
						.getDtTransferComm().equals(
								castOther.getDtTransferComm())))
				&& ((this.getDtTransferComp() == castOther.getDtTransferComp()) || (this
						.getDtTransferComp() != null
						&& castOther.getDtTransferComp() != null && this
						.getDtTransferComp().equals(
								castOther.getDtTransferComp())))
				&& (this.getIndTransferAt() == castOther.getIndTransferAt())
				&& ((this.getQtyTradeSched() == castOther.getQtyTradeSched()) || (this
						.getQtyTradeSched() != null
						&& castOther.getQtyTradeSched() != null && this
						.getQtyTradeSched()
						.equals(castOther.getQtyTradeSched())))
				&& ((this.getQtyTradeInvoice() == castOther
						.getQtyTradeInvoice()) || (this.getQtyTradeInvoice() != null
						&& castOther.getQtyTradeInvoice() != null && this
						.getQtyTradeInvoice().equals(
								castOther.getQtyTradeInvoice())))
				&& ((this.getCodTradeInvoiceUom() == castOther
						.getCodTradeInvoiceUom()) || (this
						.getCodTradeInvoiceUom() != null
						&& castOther.getCodTradeInvoiceUom() != null && this
						.getCodTradeInvoiceUom().equals(
								castOther.getCodTradeInvoiceUom())))
				&& (this.getIndDeliveryStatus() == castOther
						.getIndDeliveryStatus())
				&& ((this.getDtApplication() == castOther.getDtApplication()) || (this
						.getDtApplication() != null
						&& castOther.getDtApplication() != null && this
						.getDtApplication()
						.equals(castOther.getDtApplication())))
				&& ((this.getDtEffective() == castOther.getDtEffective()) || (this
						.getDtEffective() != null
						&& castOther.getDtEffective() != null && this
						.getDtEffective().equals(castOther.getDtEffective())))
				&& ((this.getNumObligation() == castOther.getNumObligation()) || (this
						.getNumObligation() != null
						&& castOther.getNumObligation() != null && this
						.getNumObligation()
						.equals(castOther.getNumObligation())))
				&& ((this.getRefExternal() == castOther.getRefExternal()) || (this
						.getRefExternal() != null
						&& castOther.getRefExternal() != null && this
						.getRefExternal().equals(castOther.getRefExternal())))
				&& ((this.getQtyFromPackaging() == castOther
						.getQtyFromPackaging()) || (this.getQtyFromPackaging() != null
						&& castOther.getQtyFromPackaging() != null && this
						.getQtyFromPackaging().equals(
								castOther.getQtyFromPackaging())))
				&& ((this.getQtyToPackaging() == castOther.getQtyToPackaging()) || (this
						.getQtyToPackaging() != null
						&& castOther.getQtyToPackaging() != null && this
						.getQtyToPackaging().equals(
								castOther.getQtyToPackaging())))
				&& ((this.getUomFromPackaging() == castOther
						.getUomFromPackaging()) || (this.getUomFromPackaging() != null
						&& castOther.getUomFromPackaging() != null && this
						.getUomFromPackaging().equals(
								castOther.getUomFromPackaging())))
				&& ((this.getUomToPackaging() == castOther.getUomToPackaging()) || (this
						.getUomToPackaging() != null
						&& castOther.getUomToPackaging() != null && this
						.getUomToPackaging().equals(
								castOther.getUomToPackaging())))
				&& ((this.getDtFromCargoReset() == castOther
						.getDtFromCargoReset()) || (this.getDtFromCargoReset() != null
						&& castOther.getDtFromCargoReset() != null && this
						.getDtFromCargoReset().equals(
								castOther.getDtFromCargoReset())))
				&& ((this.getDtToCargoReset() == castOther.getDtToCargoReset()) || (this
						.getDtToCargoReset() != null
						&& castOther.getDtToCargoReset() != null && this
						.getDtToCargoReset().equals(
								castOther.getDtToCargoReset())))
				&& ((this.getDtFinalizaed() == castOther.getDtFinalizaed()) || (this
						.getDtFinalizaed() != null
						&& castOther.getDtFinalizaed() != null && this
						.getDtFinalizaed().equals(castOther.getDtFinalizaed())))
				&& (this.getNumTxlTransfer() == castOther.getNumTxlTransfer())
				&& ((this.getIndImportType() == castOther.getIndImportType()) || (this
						.getIndImportType() != null
						&& castOther.getIndImportType() != null && this
						.getIndImportType()
						.equals(castOther.getIndImportType())))
				&& (this.getNumNote() == castOther.getNumNote())
				&& ((this.getDtLastModify() == castOther.getDtLastModify()) || (this
						.getDtLastModify() != null
						&& castOther.getDtLastModify() != null && this
						.getDtLastModify().equals(castOther.getDtLastModify())))
				&& (this.getNumModifyPerson() == castOther.getNumModifyPerson())
				&& (this.getNumLock() == castOther.getNumLock())
				&& (this.getNumLiftingStrategy() == castOther
						.getNumLiftingStrategy())
				&& ((this.getCodVenture() == castOther.getCodVenture()) || (this
						.getCodVenture() != null
						&& castOther.getCodVenture() != null && this
						.getCodVenture().equals(castOther.getCodVenture())))
				&& (this.getIndHasAttachment() == castOther
						.getIndHasAttachment())
				&& (this.getNumOperatorPerson() == castOther
						.getNumOperatorPerson())
				&& (this.getNumTransferLink() == castOther.getNumTransferLink())
				&& (this.getIndTransferLinkType() == castOther
						.getIndTransferLinkType())
				&& (this.getIndCustomsDutyStatus() == castOther
						.getIndCustomsDutyStatus())
				&& (this.getIndFromCustomsDutyStatus() == castOther
						.getIndFromCustomsDutyStatus())
				&& (this.getIndToCustomsDutyStatus() == castOther
						.getIndToCustomsDutyStatus())
				&& ((this.getCodBlNum() == castOther.getCodBlNum()) || (this
						.getCodBlNum() != null
						&& castOther.getCodBlNum() != null && this
						.getCodBlNum().equals(castOther.getCodBlNum())))
				&& ((this.getDtBl() == castOther.getDtBl()) || (this.getDtBl() != null
						&& castOther.getDtBl() != null && this.getDtBl()
						.equals(castOther.getDtBl())))
				&& ((this.getIndDeliveryActiveStatus() == castOther
						.getIndDeliveryActiveStatus()) || (this
						.getIndDeliveryActiveStatus() != null
						&& castOther.getIndDeliveryActiveStatus() != null && this
						.getIndDeliveryActiveStatus().equals(
								castOther.getIndDeliveryActiveStatus())))
				&& ((this.getDtLiquidate() == castOther.getDtLiquidate()) || (this
						.getDtLiquidate() != null
						&& castOther.getDtLiquidate() != null && this
						.getDtLiquidate().equals(castOther.getDtLiquidate())))
				&& ((this.getIndMotType() == castOther.getIndMotType()) || (this
						.getIndMotType() != null
						&& castOther.getIndMotType() != null && this
						.getIndMotType().equals(castOther.getIndMotType())))
				&& (this.getNumReceiptLocation() == castOther
						.getNumReceiptLocation())
				&& (this.getNumDeliveryLocation() == castOther
						.getNumDeliveryLocation())
				&& (this.getNumInventory() == castOther.getNumInventory())
				&& (this.getNumBatch() == castOther.getNumBatch())
				&& ((this.getIdBatchLevel() == castOther.getIdBatchLevel()) || (this
						.getIdBatchLevel() != null
						&& castOther.getIdBatchLevel() != null && this
						.getIdBatchLevel().equals(castOther.getIdBatchLevel())))
				&& ((this.getIdFromBatch() == castOther.getIdFromBatch()) || (this
						.getIdFromBatch() != null
						&& castOther.getIdFromBatch() != null && this
						.getIdFromBatch().equals(castOther.getIdFromBatch())))
				&& ((this.getIdToBatch() == castOther.getIdToBatch()) || (this
						.getIdToBatch() != null
						&& castOther.getIdToBatch() != null && this
						.getIdToBatch().equals(castOther.getIdToBatch())))
				&& ((this.getDtDelivery() == castOther.getDtDelivery()) || (this
						.getDtDelivery() != null
						&& castOther.getDtDelivery() != null && this
						.getDtDelivery().equals(castOther.getDtDelivery())))
				&& (this.getIndDeliveryDtMtm() == castOther
						.getIndDeliveryDtMtm())
				&& ((this.getComments() == castOther.getComments()) || (this
						.getComments() != null
						&& castOther.getComments() != null && this
						.getComments().equals(castOther.getComments())))
				&& (this.getIndTransferSplit() == castOther
						.getIndTransferSplit())
				&& (this.getNumParentTransfer() == castOther
						.getNumParentTransfer())
				&& (this.getNumCompany() == castOther.getNumCompany())
				&& (this.getNumPath() == castOther.getNumPath())
				&& (this.getIndAddTariffCost() == castOther
						.getIndAddTariffCost())
				&& ((this.getIndTransferState() == castOther
						.getIndTransferState()) || (this.getIndTransferState() != null
						&& castOther.getIndTransferState() != null && this
						.getIndTransferState().equals(
								castOther.getIndTransferState())))
				&& ((this.getNumToStrategy() == castOther.getNumToStrategy()) || (this
						.getNumToStrategy() != null
						&& castOther.getNumToStrategy() != null && this
						.getNumToStrategy()
						.equals(castOther.getNumToStrategy())))
				&& ((this.getNumFromStrategy() == castOther
						.getNumFromStrategy()) || (this.getNumFromStrategy() != null
						&& castOther.getNumFromStrategy() != null && this
						.getNumFromStrategy().equals(
								castOther.getNumFromStrategy())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumTransfer();
		result = 37 * result + this.getIndFromType();
		result = 37 * result + this.getNumFromItinerary();
		result = 37 * result + this.getNumFromEquipment();
		result = 37 * result + this.getNumFromCargo();
		result = 37 * result
				+ (getQtyFrom() == null ? 0 : this.getQtyFrom().hashCode());
		result = 37
				* result
				+ (getCodFromUom() == null ? 0 : this.getCodFromUom()
						.hashCode());
		result = 37 * result + this.getIndToType();
		result = 37 * result + this.getNumToItinerary();
		result = 37 * result + this.getNumToEquipment();
		result = 37 * result + this.getNumToCargo();
		result = 37 * result
				+ (getQtyTo() == null ? 0 : this.getQtyTo().hashCode());
		result = 37 * result
				+ (getCodToUom() == null ? 0 : this.getCodToUom().hashCode());
		result = 37
				* result
				+ (getNumLocation() == null ? 0 : this.getNumLocation()
						.hashCode());
		result = 37
				* result
				+ (getFactUomConv() == null ? 0 : this.getFactUomConv()
						.hashCode());
		result = 37 * result + this.getIndUomConvFactor();
		result = 37
				* result
				+ (getQtyGainLoss() == null ? 0 : this.getQtyGainLoss()
						.hashCode());
		result = 37 * result + this.getNumBuild();
		result = 37 * result + this.getNumDraw();
		result = 37 * result + this.getNumAdjustmentBd();
		result = 37
				* result
				+ (getPrcTransfer() == null ? 0 : this.getPrcTransfer()
						.hashCode());
		result = 37
				* result
				+ (getCodTransferPriceCurr() == null ? 0 : this
						.getCodTransferPriceCurr().hashCode());
		result = 37
				* result
				+ (getCodTransferPriceUom() == null ? 0 : this
						.getCodTransferPriceUom().hashCode());
		result = 37 * result + this.getIndTransferPriceStatus();
		result = 37
				* result
				+ (getDtTransferComm() == null ? 0 : this.getDtTransferComm()
						.hashCode());
		result = 37
				* result
				+ (getDtTransferComp() == null ? 0 : this.getDtTransferComp()
						.hashCode());
		result = 37 * result + this.getIndTransferAt();
		result = 37
				* result
				+ (getQtyTradeSched() == null ? 0 : this.getQtyTradeSched()
						.hashCode());
		result = 37
				* result
				+ (getQtyTradeInvoice() == null ? 0 : this.getQtyTradeInvoice()
						.hashCode());
		result = 37
				* result
				+ (getCodTradeInvoiceUom() == null ? 0 : this
						.getCodTradeInvoiceUom().hashCode());
		result = 37 * result + this.getIndDeliveryStatus();
		result = 37
				* result
				+ (getDtApplication() == null ? 0 : this.getDtApplication()
						.hashCode());
		result = 37
				* result
				+ (getDtEffective() == null ? 0 : this.getDtEffective()
						.hashCode());
		result = 37
				* result
				+ (getNumObligation() == null ? 0 : this.getNumObligation()
						.hashCode());
		result = 37
				* result
				+ (getRefExternal() == null ? 0 : this.getRefExternal()
						.hashCode());
		result = 37
				* result
				+ (getQtyFromPackaging() == null ? 0 : this
						.getQtyFromPackaging().hashCode());
		result = 37
				* result
				+ (getQtyToPackaging() == null ? 0 : this.getQtyToPackaging()
						.hashCode());
		result = 37
				* result
				+ (getUomFromPackaging() == null ? 0 : this
						.getUomFromPackaging().hashCode());
		result = 37
				* result
				+ (getUomToPackaging() == null ? 0 : this.getUomToPackaging()
						.hashCode());
		result = 37
				* result
				+ (getDtFromCargoReset() == null ? 0 : this
						.getDtFromCargoReset().hashCode());
		result = 37
				* result
				+ (getDtToCargoReset() == null ? 0 : this.getDtToCargoReset()
						.hashCode());
		result = 37
				* result
				+ (getDtFinalizaed() == null ? 0 : this.getDtFinalizaed()
						.hashCode());
		result = 37 * result + this.getNumTxlTransfer();
		result = 37
				* result
				+ (getIndImportType() == null ? 0 : this.getIndImportType()
						.hashCode());
		result = 37 * result + this.getNumNote();
		result = 37
				* result
				+ (getDtLastModify() == null ? 0 : this.getDtLastModify()
						.hashCode());
		result = 37 * result + this.getNumModifyPerson();
		result = 37 * result + this.getNumLock();
		result = 37 * result + this.getNumLiftingStrategy();
		result = 37
				* result
				+ (getCodVenture() == null ? 0 : this.getCodVenture()
						.hashCode());
		result = 37 * result + this.getIndHasAttachment();
		result = 37 * result + this.getNumOperatorPerson();
		result = 37 * result + this.getNumTransferLink();
		result = 37 * result + this.getIndTransferLinkType();
		result = 37 * result + this.getIndCustomsDutyStatus();
		result = 37 * result + this.getIndFromCustomsDutyStatus();
		result = 37 * result + this.getIndToCustomsDutyStatus();
		result = 37 * result
				+ (getCodBlNum() == null ? 0 : this.getCodBlNum().hashCode());
		result = 37 * result
				+ (getDtBl() == null ? 0 : this.getDtBl().hashCode());
		result = 37
				* result
				+ (getIndDeliveryActiveStatus() == null ? 0 : this
						.getIndDeliveryActiveStatus().hashCode());
		result = 37
				* result
				+ (getDtLiquidate() == null ? 0 : this.getDtLiquidate()
						.hashCode());
		result = 37
				* result
				+ (getIndMotType() == null ? 0 : this.getIndMotType()
						.hashCode());
		result = 37 * result + this.getNumReceiptLocation();
		result = 37 * result + this.getNumDeliveryLocation();
		result = 37 * result + this.getNumInventory();
		result = 37 * result + this.getNumBatch();
		result = 37
				* result
				+ (getIdBatchLevel() == null ? 0 : this.getIdBatchLevel()
						.hashCode());
		result = 37
				* result
				+ (getIdFromBatch() == null ? 0 : this.getIdFromBatch()
						.hashCode());
		result = 37 * result
				+ (getIdToBatch() == null ? 0 : this.getIdToBatch().hashCode());
		result = 37
				* result
				+ (getDtDelivery() == null ? 0 : this.getDtDelivery()
						.hashCode());
		result = 37 * result + this.getIndDeliveryDtMtm();
		result = 37 * result
				+ (getComments() == null ? 0 : this.getComments().hashCode());
		result = 37 * result + this.getIndTransferSplit();
		result = 37 * result + this.getNumParentTransfer();
		result = 37 * result + this.getNumCompany();
		result = 37 * result + this.getNumPath();
		result = 37 * result + this.getIndAddTariffCost();
		result = 37
				* result
				+ (getIndTransferState() == null ? 0 : this
						.getIndTransferState().hashCode());
		result = 37
				* result
				+ (getNumToStrategy() == null ? 0 : this.getNumToStrategy()
						.hashCode());
		result = 37
				* result
				+ (getNumFromStrategy() == null ? 0 : this.getNumFromStrategy()
						.hashCode());
		return result;
	}

}
