package com.mercon.entities;

// Generated Jul 29, 2013 11:20:55 AM by Hibernate Tools 3.4.0.CR1

/**
 * VdimCompany generated by hbm2java
 */
public class VdimCompany implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private VdimCompanyId id;

	public VdimCompany() {
	}

	public VdimCompany(VdimCompanyId id) {
		this.id = id;
	}

	public VdimCompanyId getId() {
		return this.id;
	}

	public void setId(VdimCompanyId id) {
		this.id = id;
	}

}
