package com.mercon.entities;

// Generated 20-nov-2013 17:31:07 by Hibernate Tools 3.4.0.CR1

/**
 * VdimCommodity generated by hbm2java
 */
public class VdimCommodity implements java.io.Serializable {

	/**
	 * Serial ID
	 */
	private static final long serialVersionUID = -5399709795757948129L;
	
	private VdimCommodityId id;

	public VdimCommodity() {
	}

	public VdimCommodity(VdimCommodityId id) {
		this.id = id;
	}

	public VdimCommodityId getId() {
		return this.id;
	}

	public void setId(VdimCommodityId id) {
		this.id = id;
	}

}
