package com.mercon.entities;

// Generated 01-03-2013 04:45:01 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * VdimMktQuoteDefinitionId generated by hbm2java
 */
public class VdimMktQuoteDefinitionId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int numdefquote;
	private int numvolcurve;
	private String codsource;
	private String coddefquote;
	private String longdefquote;
	private short indquotedeftype;
	private String codquoteuom;
	private String codcurrquote;
	private int numfutbasequotedef;
	private String codcmdty;
	private String codexchange;
	private String codcalendar;
	private int numlocation;
	private String coddelivsched;
	private String serviceLevelCd;
	private BigDecimal qtylot;
	private String coduomqty;
	private short indexchangetraded;
	private int monthmaintain;
	private int numreferencequotedef;
	private short indpricecurvestyle;
	private short indcompfunction;
	private short indriskruledate;
	private int nummodifyperson;
	private short indstatus;
	private Date dtlastmodify;
	private int numlock;
	private short indexchsettlementrule;

	public VdimMktQuoteDefinitionId() {
	}

	public VdimMktQuoteDefinitionId(int numdefquote, String coddefquote,
			short indquotedeftype, String codquoteuom, String codcurrquote,
			String codcalendar, int numlocation, short indexchangetraded,
			short indcompfunction, short indriskruledate, int nummodifyperson,
			short indstatus, Date dtlastmodify, int numlock) {
		this.numdefquote = numdefquote;
		this.coddefquote = coddefquote;
		this.indquotedeftype = indquotedeftype;
		this.codquoteuom = codquoteuom;
		this.codcurrquote = codcurrquote;
		this.codcalendar = codcalendar;
		this.numlocation = numlocation;
		this.indexchangetraded = indexchangetraded;
		this.indcompfunction = indcompfunction;
		this.indriskruledate = indriskruledate;
		this.nummodifyperson = nummodifyperson;
		this.indstatus = indstatus;
		this.dtlastmodify = dtlastmodify;
		this.numlock = numlock;
	}

	public VdimMktQuoteDefinitionId(int numdefquote, Integer numvolcurve,
			String codsource, String coddefquote, String longdefquote,
			short indquotedeftype, String codquoteuom, String codcurrquote,
			Integer numfutbasequotedef, String codcmdty, String codexchange,
			String codcalendar, int numlocation, String coddelivsched,
			String serviceLevelCd, BigDecimal qtylot, String coduomqty,
			short indexchangetraded, Integer monthmaintain,
			Integer numreferencequotedef, Short indpricecurvestyle,
			short indcompfunction, short indriskruledate, int nummodifyperson,
			short indstatus, Date dtlastmodify, int numlock,
			Short indexchsettlementrule) {
		this.numdefquote = numdefquote;
		this.numvolcurve = numvolcurve;
		this.codsource = codsource;
		this.coddefquote = coddefquote;
		this.longdefquote = longdefquote;
		this.indquotedeftype = indquotedeftype;
		this.codquoteuom = codquoteuom;
		this.codcurrquote = codcurrquote;
		this.numfutbasequotedef = numfutbasequotedef;
		this.codcmdty = codcmdty;
		this.codexchange = codexchange;
		this.codcalendar = codcalendar;
		this.numlocation = numlocation;
		this.coddelivsched = coddelivsched;
		this.serviceLevelCd = serviceLevelCd;
		this.qtylot = qtylot;
		this.coduomqty = coduomqty;
		this.indexchangetraded = indexchangetraded;
		this.monthmaintain = monthmaintain;
		this.numreferencequotedef = numreferencequotedef;
		this.indpricecurvestyle = indpricecurvestyle;
		this.indcompfunction = indcompfunction;
		this.indriskruledate = indriskruledate;
		this.nummodifyperson = nummodifyperson;
		this.indstatus = indstatus;
		this.dtlastmodify = dtlastmodify;
		this.numlock = numlock;
		this.indexchsettlementrule = indexchsettlementrule;
	}

	public int getNumdefquote() {
		return this.numdefquote;
	}

	public void setNumdefquote(int numdefquote) {
		this.numdefquote = numdefquote;
	}

	public Integer getNumvolcurve() {
		return this.numvolcurve;
	}

	public void setNumvolcurve(Integer numvolcurve) {
		this.numvolcurve = numvolcurve;
	}

	public String getCodsource() {
		return this.codsource;
	}

	public void setCodsource(String codsource) {
		this.codsource = codsource;
	}

	public String getCoddefquote() {
		return this.coddefquote;
	}

	public void setCoddefquote(String coddefquote) {
		this.coddefquote = coddefquote;
	}

	public String getLongdefquote() {
		return this.longdefquote;
	}

	public void setLongdefquote(String longdefquote) {
		this.longdefquote = longdefquote;
	}

	public short getIndquotedeftype() {
		return this.indquotedeftype;
	}

	public void setIndquotedeftype(short indquotedeftype) {
		this.indquotedeftype = indquotedeftype;
	}

	public String getCodquoteuom() {
		return this.codquoteuom;
	}

	public void setCodquoteuom(String codquoteuom) {
		this.codquoteuom = codquoteuom;
	}

	public String getCodcurrquote() {
		return this.codcurrquote;
	}

	public void setCodcurrquote(String codcurrquote) {
		this.codcurrquote = codcurrquote;
	}

	public Integer getNumfutbasequotedef() {
		return this.numfutbasequotedef;
	}

	public void setNumfutbasequotedef(Integer numfutbasequotedef) {
		this.numfutbasequotedef = numfutbasequotedef;
	}

	public String getCodcmdty() {
		return this.codcmdty;
	}

	public void setCodcmdty(String codcmdty) {
		this.codcmdty = codcmdty;
	}

	public String getCodexchange() {
		return this.codexchange;
	}

	public void setCodexchange(String codexchange) {
		this.codexchange = codexchange;
	}

	public String getCodcalendar() {
		return this.codcalendar;
	}

	public void setCodcalendar(String codcalendar) {
		this.codcalendar = codcalendar;
	}

	public int getNumlocation() {
		return this.numlocation;
	}

	public void setNumlocation(int numlocation) {
		this.numlocation = numlocation;
	}

	public String getCoddelivsched() {
		return this.coddelivsched;
	}

	public void setCoddelivsched(String coddelivsched) {
		this.coddelivsched = coddelivsched;
	}

	public String getServiceLevelCd() {
		return this.serviceLevelCd;
	}

	public void setServiceLevelCd(String serviceLevelCd) {
		this.serviceLevelCd = serviceLevelCd;
	}

	public BigDecimal getQtylot() {
		return this.qtylot;
	}

	public void setQtylot(BigDecimal qtylot) {
		this.qtylot = qtylot;
	}

	public String getCoduomqty() {
		return this.coduomqty;
	}

	public void setCoduomqty(String coduomqty) {
		this.coduomqty = coduomqty;
	}

	public short getIndexchangetraded() {
		return this.indexchangetraded;
	}

	public void setIndexchangetraded(short indexchangetraded) {
		this.indexchangetraded = indexchangetraded;
	}

	public Integer getMonthmaintain() {
		return this.monthmaintain;
	}

	public void setMonthmaintain(Integer monthmaintain) {
		this.monthmaintain = monthmaintain;
	}

	public Integer getNumreferencequotedef() {
		return this.numreferencequotedef;
	}

	public void setNumreferencequotedef(Integer numreferencequotedef) {
		this.numreferencequotedef = numreferencequotedef;
	}

	public Short getIndpricecurvestyle() {
		return this.indpricecurvestyle;
	}

	public void setIndpricecurvestyle(Short indpricecurvestyle) {
		this.indpricecurvestyle = indpricecurvestyle;
	}

	public short getIndcompfunction() {
		return this.indcompfunction;
	}

	public void setIndcompfunction(short indcompfunction) {
		this.indcompfunction = indcompfunction;
	}

	public short getIndriskruledate() {
		return this.indriskruledate;
	}

	public void setIndriskruledate(short indriskruledate) {
		this.indriskruledate = indriskruledate;
	}

	public int getNummodifyperson() {
		return this.nummodifyperson;
	}

	public void setNummodifyperson(int nummodifyperson) {
		this.nummodifyperson = nummodifyperson;
	}

	public short getIndstatus() {
		return this.indstatus;
	}

	public void setIndstatus(short indstatus) {
		this.indstatus = indstatus;
	}

	public Date getDtlastmodify() {
		return this.dtlastmodify;
	}

	public void setDtlastmodify(Date dtlastmodify) {
		this.dtlastmodify = dtlastmodify;
	}

	public int getNumlock() {
		return this.numlock;
	}

	public void setNumlock(int numlock) {
		this.numlock = numlock;
	}

	public Short getIndexchsettlementrule() {
		return this.indexchsettlementrule;
	}

	public void setIndexchsettlementrule(Short indexchsettlementrule) {
		this.indexchsettlementrule = indexchsettlementrule;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VdimMktQuoteDefinitionId))
			return false;
		VdimMktQuoteDefinitionId castOther = (VdimMktQuoteDefinitionId) other;

		return (this.getNumdefquote() == castOther.getNumdefquote())
				&& ((this.getNumvolcurve() == castOther.getNumvolcurve()) || (this
						.getNumvolcurve() != null
						&& castOther.getNumvolcurve() != null && this
						.getNumvolcurve().equals(castOther.getNumvolcurve())))
				&& ((this.getCodsource() == castOther.getCodsource()) || (this
						.getCodsource() != null
						&& castOther.getCodsource() != null && this
						.getCodsource().equals(castOther.getCodsource())))
				&& ((this.getCoddefquote() == castOther.getCoddefquote()) || (this
						.getCoddefquote() != null
						&& castOther.getCoddefquote() != null && this
						.getCoddefquote().equals(castOther.getCoddefquote())))
				&& ((this.getLongdefquote() == castOther.getLongdefquote()) || (this
						.getLongdefquote() != null
						&& castOther.getLongdefquote() != null && this
						.getLongdefquote().equals(castOther.getLongdefquote())))
				&& (this.getIndquotedeftype() == castOther.getIndquotedeftype())
				&& ((this.getCodquoteuom() == castOther.getCodquoteuom()) || (this
						.getCodquoteuom() != null
						&& castOther.getCodquoteuom() != null && this
						.getCodquoteuom().equals(castOther.getCodquoteuom())))
				&& ((this.getCodcurrquote() == castOther.getCodcurrquote()) || (this
						.getCodcurrquote() != null
						&& castOther.getCodcurrquote() != null && this
						.getCodcurrquote().equals(castOther.getCodcurrquote())))
				&& ((this.getNumfutbasequotedef() == castOther
						.getNumfutbasequotedef()) || (this
						.getNumfutbasequotedef() != null
						&& castOther.getNumfutbasequotedef() != null && this
						.getNumfutbasequotedef().equals(
								castOther.getNumfutbasequotedef())))
				&& ((this.getCodcmdty() == castOther.getCodcmdty()) || (this
						.getCodcmdty() != null
						&& castOther.getCodcmdty() != null && this
						.getCodcmdty().equals(castOther.getCodcmdty())))
				&& ((this.getCodexchange() == castOther.getCodexchange()) || (this
						.getCodexchange() != null
						&& castOther.getCodexchange() != null && this
						.getCodexchange().equals(castOther.getCodexchange())))
				&& ((this.getCodcalendar() == castOther.getCodcalendar()) || (this
						.getCodcalendar() != null
						&& castOther.getCodcalendar() != null && this
						.getCodcalendar().equals(castOther.getCodcalendar())))
				&& (this.getNumlocation() == castOther.getNumlocation())
				&& ((this.getCoddelivsched() == castOther.getCoddelivsched()) || (this
						.getCoddelivsched() != null
						&& castOther.getCoddelivsched() != null && this
						.getCoddelivsched()
						.equals(castOther.getCoddelivsched())))
				&& ((this.getServiceLevelCd() == castOther.getServiceLevelCd()) || (this
						.getServiceLevelCd() != null
						&& castOther.getServiceLevelCd() != null && this
						.getServiceLevelCd().equals(
								castOther.getServiceLevelCd())))
				&& ((this.getQtylot() == castOther.getQtylot()) || (this
						.getQtylot() != null && castOther.getQtylot() != null && this
						.getQtylot().equals(castOther.getQtylot())))
				&& ((this.getCoduomqty() == castOther.getCoduomqty()) || (this
						.getCoduomqty() != null
						&& castOther.getCoduomqty() != null && this
						.getCoduomqty().equals(castOther.getCoduomqty())))
				&& (this.getIndexchangetraded() == castOther
						.getIndexchangetraded())
				&& ((this.getMonthmaintain() == castOther.getMonthmaintain()) || (this
						.getMonthmaintain() != null
						&& castOther.getMonthmaintain() != null && this
						.getMonthmaintain()
						.equals(castOther.getMonthmaintain())))
				&& ((this.getNumreferencequotedef() == castOther
						.getNumreferencequotedef()) || (this
						.getNumreferencequotedef() != null
						&& castOther.getNumreferencequotedef() != null && this
						.getNumreferencequotedef().equals(
								castOther.getNumreferencequotedef())))
				&& ((this.getIndpricecurvestyle() == castOther
						.getIndpricecurvestyle()) || (this
						.getIndpricecurvestyle() != null
						&& castOther.getIndpricecurvestyle() != null && this
						.getIndpricecurvestyle().equals(
								castOther.getIndpricecurvestyle())))
				&& (this.getIndcompfunction() == castOther.getIndcompfunction())
				&& (this.getIndriskruledate() == castOther.getIndriskruledate())
				&& (this.getNummodifyperson() == castOther.getNummodifyperson())
				&& (this.getIndstatus() == castOther.getIndstatus())
				&& ((this.getDtlastmodify() == castOther.getDtlastmodify()) || (this
						.getDtlastmodify() != null
						&& castOther.getDtlastmodify() != null && this
						.getDtlastmodify().equals(castOther.getDtlastmodify())))
				&& (this.getNumlock() == castOther.getNumlock())
				&& ((this.getIndexchsettlementrule() == castOther
						.getIndexchsettlementrule()) || (this
						.getIndexchsettlementrule() != null
						&& castOther.getIndexchsettlementrule() != null && this
						.getIndexchsettlementrule().equals(
								castOther.getIndexchsettlementrule())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumdefquote();
		result = 37
				* result
				+ (getNumvolcurve() == null ? 0 : this.getNumvolcurve()
						.hashCode());
		result = 37 * result
				+ (getCodsource() == null ? 0 : this.getCodsource().hashCode());
		result = 37
				* result
				+ (getCoddefquote() == null ? 0 : this.getCoddefquote()
						.hashCode());
		result = 37
				* result
				+ (getLongdefquote() == null ? 0 : this.getLongdefquote()
						.hashCode());
		result = 37 * result + this.getIndquotedeftype();
		result = 37
				* result
				+ (getCodquoteuom() == null ? 0 : this.getCodquoteuom()
						.hashCode());
		result = 37
				* result
				+ (getCodcurrquote() == null ? 0 : this.getCodcurrquote()
						.hashCode());
		result = 37
				* result
				+ (getNumfutbasequotedef() == null ? 0 : this
						.getNumfutbasequotedef().hashCode());
		result = 37 * result
				+ (getCodcmdty() == null ? 0 : this.getCodcmdty().hashCode());
		result = 37
				* result
				+ (getCodexchange() == null ? 0 : this.getCodexchange()
						.hashCode());
		result = 37
				* result
				+ (getCodcalendar() == null ? 0 : this.getCodcalendar()
						.hashCode());
		result = 37 * result + this.getNumlocation();
		result = 37
				* result
				+ (getCoddelivsched() == null ? 0 : this.getCoddelivsched()
						.hashCode());
		result = 37
				* result
				+ (getServiceLevelCd() == null ? 0 : this.getServiceLevelCd()
						.hashCode());
		result = 37 * result
				+ (getQtylot() == null ? 0 : this.getQtylot().hashCode());
		result = 37 * result
				+ (getCoduomqty() == null ? 0 : this.getCoduomqty().hashCode());
		result = 37 * result + this.getIndexchangetraded();
		result = 37
				* result
				+ (getMonthmaintain() == null ? 0 : this.getMonthmaintain()
						.hashCode());
		result = 37
				* result
				+ (getNumreferencequotedef() == null ? 0 : this
						.getNumreferencequotedef().hashCode());
		result = 37
				* result
				+ (getIndpricecurvestyle() == null ? 0 : this
						.getIndpricecurvestyle().hashCode());
		result = 37 * result + this.getIndcompfunction();
		result = 37 * result + this.getIndriskruledate();
		result = 37 * result + this.getNummodifyperson();
		result = 37 * result + this.getIndstatus();
		result = 37
				* result
				+ (getDtlastmodify() == null ? 0 : this.getDtlastmodify()
						.hashCode());
		result = 37 * result + this.getNumlock();
		result = 37
				* result
				+ (getIndexchsettlementrule() == null ? 0 : this
						.getIndexchsettlementrule().hashCode());
		return result;
	}

}
