package com.mercon.entities;

// Generated Oct 13, 2014 4:04:57 PM by Hibernate Tools 3.4.0.CR1

/**
 * VgenIndicator generated by hbm2java
 */
public class VgenIndicator implements java.io.Serializable {

	/**
	 * Serial ID
	 */
	private static final long serialVersionUID = 1123148266406746135L;

	private VgenIndicatorId id;

	public VgenIndicator() {
	}

	public VgenIndicator(VgenIndicatorId id) {
		this.id = id;
	}

	public VgenIndicatorId getId() {
		return this.id;
	}

	public void setId(VgenIndicatorId id) {
		this.id = id;
	}

}
