package com.mercon.entities;

// Generated Aug 8, 2014 11:06:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * VgenNoteId generated by hbm2java
 */
public class VgenNoteId implements java.io.Serializable {

	/**
	 * Serial ID
	 */
	private static final long serialVersionUID = 6637626359190288817L;

	private int noteNum;
	private int noteSubNum;
	private short noteTypeInd;
	private String noteCategoryCd;
	private String noteText;
	private String notePreview;
	private String tablename;
	private String keyname;
	private String keyvalue;
	private Date createdOnDt;
	private Integer creatorPersonNum;
	private Date lastModifyDt;
	private int modifyPersonNum;
	private int lockNum;
	private short documentSupportInd;
	private short confirmationSupportInd;
	private String mirrorKeyValue;

	public VgenNoteId() {
	}

	public VgenNoteId(int noteNum, int noteSubNum, short noteTypeInd,
			String noteCategoryCd, Date lastModifyDt, int modifyPersonNum,
			int lockNum, short documentSupportInd,
			short confirmationSupportInd, String mirrorKeyValue) {
		this.noteNum = noteNum;
		this.noteSubNum = noteSubNum;
		this.noteTypeInd = noteTypeInd;
		this.noteCategoryCd = noteCategoryCd;
		this.lastModifyDt = lastModifyDt;
		this.modifyPersonNum = modifyPersonNum;
		this.lockNum = lockNum;
		this.documentSupportInd = documentSupportInd;
		this.confirmationSupportInd = confirmationSupportInd;
		this.mirrorKeyValue = mirrorKeyValue;
	}

	public VgenNoteId(int noteNum, int noteSubNum, short noteTypeInd,
			String noteCategoryCd, String noteText, String notePreview,
			String tablename, String keyname, String keyvalue,
			Date createdOnDt, Integer creatorPersonNum, Date lastModifyDt,
			int modifyPersonNum, int lockNum, short documentSupportInd,
			short confirmationSupportInd, String mirrorKeyValue) {
		this.noteNum = noteNum;
		this.noteSubNum = noteSubNum;
		this.noteTypeInd = noteTypeInd;
		this.noteCategoryCd = noteCategoryCd;
		this.noteText = noteText;
		this.notePreview = notePreview;
		this.tablename = tablename;
		this.keyname = keyname;
		this.keyvalue = keyvalue;
		this.createdOnDt = createdOnDt;
		this.creatorPersonNum = creatorPersonNum;
		this.lastModifyDt = lastModifyDt;
		this.modifyPersonNum = modifyPersonNum;
		this.lockNum = lockNum;
		this.documentSupportInd = documentSupportInd;
		this.confirmationSupportInd = confirmationSupportInd;
		this.mirrorKeyValue = mirrorKeyValue;
	}

	public int getNoteNum() {
		return this.noteNum;
	}

	public void setNoteNum(int noteNum) {
		this.noteNum = noteNum;
	}

	public int getNoteSubNum() {
		return this.noteSubNum;
	}

	public void setNoteSubNum(int noteSubNum) {
		this.noteSubNum = noteSubNum;
	}

	public short getNoteTypeInd() {
		return this.noteTypeInd;
	}

	public void setNoteTypeInd(short noteTypeInd) {
		this.noteTypeInd = noteTypeInd;
	}

	public String getNoteCategoryCd() {
		return this.noteCategoryCd;
	}

	public void setNoteCategoryCd(String noteCategoryCd) {
		this.noteCategoryCd = noteCategoryCd;
	}

	public String getNoteText() {
		return this.noteText;
	}

	public void setNoteText(String noteText) {
		this.noteText = noteText;
	}

	public String getNotePreview() {
		return this.notePreview;
	}

	public void setNotePreview(String notePreview) {
		this.notePreview = notePreview;
	}

	public String getTablename() {
		return this.tablename;
	}

	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	public String getKeyname() {
		return this.keyname;
	}

	public void setKeyname(String keyname) {
		this.keyname = keyname;
	}

	public String getKeyvalue() {
		return this.keyvalue;
	}

	public void setKeyvalue(String keyvalue) {
		this.keyvalue = keyvalue;
	}

	public Date getCreatedOnDt() {
		return this.createdOnDt;
	}

	public void setCreatedOnDt(Date createdOnDt) {
		this.createdOnDt = createdOnDt;
	}

	public Integer getCreatorPersonNum() {
		return this.creatorPersonNum;
	}

	public void setCreatorPersonNum(Integer creatorPersonNum) {
		this.creatorPersonNum = creatorPersonNum;
	}

	public Date getLastModifyDt() {
		return this.lastModifyDt;
	}

	public void setLastModifyDt(Date lastModifyDt) {
		this.lastModifyDt = lastModifyDt;
	}

	public int getModifyPersonNum() {
		return this.modifyPersonNum;
	}

	public void setModifyPersonNum(int modifyPersonNum) {
		this.modifyPersonNum = modifyPersonNum;
	}

	public int getLockNum() {
		return this.lockNum;
	}

	public void setLockNum(int lockNum) {
		this.lockNum = lockNum;
	}

	public short getDocumentSupportInd() {
		return this.documentSupportInd;
	}

	public void setDocumentSupportInd(short documentSupportInd) {
		this.documentSupportInd = documentSupportInd;
	}

	public short getConfirmationSupportInd() {
		return this.confirmationSupportInd;
	}

	public void setConfirmationSupportInd(short confirmationSupportInd) {
		this.confirmationSupportInd = confirmationSupportInd;
	}

	public String getMirrorKeyValue() {
		return this.mirrorKeyValue;
	}

	public void setMirrorKeyValue(String mirrorKeyValue) {
		this.mirrorKeyValue = mirrorKeyValue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VgenNoteId))
			return false;
		VgenNoteId castOther = (VgenNoteId) other;

		return (this.getNoteNum() == castOther.getNoteNum())
				&& (this.getNoteSubNum() == castOther.getNoteSubNum())
				&& (this.getNoteTypeInd() == castOther.getNoteTypeInd())
				&& ((this.getNoteCategoryCd() == castOther.getNoteCategoryCd()) || (this
						.getNoteCategoryCd() != null
						&& castOther.getNoteCategoryCd() != null && this
						.getNoteCategoryCd().equals(
								castOther.getNoteCategoryCd())))
				&& ((this.getNoteText() == castOther.getNoteText()) || (this
						.getNoteText() != null
						&& castOther.getNoteText() != null && this
						.getNoteText().equals(castOther.getNoteText())))
				&& ((this.getNotePreview() == castOther.getNotePreview()) || (this
						.getNotePreview() != null
						&& castOther.getNotePreview() != null && this
						.getNotePreview().equals(castOther.getNotePreview())))
				&& ((this.getTablename() == castOther.getTablename()) || (this
						.getTablename() != null
						&& castOther.getTablename() != null && this
						.getTablename().equals(castOther.getTablename())))
				&& ((this.getKeyname() == castOther.getKeyname()) || (this
						.getKeyname() != null && castOther.getKeyname() != null && this
						.getKeyname().equals(castOther.getKeyname())))
				&& ((this.getKeyvalue() == castOther.getKeyvalue()) || (this
						.getKeyvalue() != null
						&& castOther.getKeyvalue() != null && this
						.getKeyvalue().equals(castOther.getKeyvalue())))
				&& ((this.getCreatedOnDt() == castOther.getCreatedOnDt()) || (this
						.getCreatedOnDt() != null
						&& castOther.getCreatedOnDt() != null && this
						.getCreatedOnDt().equals(castOther.getCreatedOnDt())))
				&& ((this.getCreatorPersonNum() == castOther
						.getCreatorPersonNum()) || (this.getCreatorPersonNum() != null
						&& castOther.getCreatorPersonNum() != null && this
						.getCreatorPersonNum().equals(
								castOther.getCreatorPersonNum())))
				&& ((this.getLastModifyDt() == castOther.getLastModifyDt()) || (this
						.getLastModifyDt() != null
						&& castOther.getLastModifyDt() != null && this
						.getLastModifyDt().equals(castOther.getLastModifyDt())))
				&& (this.getModifyPersonNum() == castOther.getModifyPersonNum())
				&& (this.getLockNum() == castOther.getLockNum())
				&& (this.getDocumentSupportInd() == castOther
						.getDocumentSupportInd())
				&& (this.getConfirmationSupportInd() == castOther
						.getConfirmationSupportInd())
				&& ((this.getMirrorKeyValue() == castOther.getMirrorKeyValue()) || (this
						.getMirrorKeyValue() != null
						&& castOther.getMirrorKeyValue() != null && this
						.getMirrorKeyValue().equals(
								castOther.getMirrorKeyValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNoteNum();
		result = 37 * result + this.getNoteSubNum();
		result = 37 * result + this.getNoteTypeInd();
		result = 37
				* result
				+ (getNoteCategoryCd() == null ? 0 : this.getNoteCategoryCd()
						.hashCode());
		result = 37 * result
				+ (getNoteText() == null ? 0 : this.getNoteText().hashCode());
		result = 37
				* result
				+ (getNotePreview() == null ? 0 : this.getNotePreview()
						.hashCode());
		result = 37 * result
				+ (getTablename() == null ? 0 : this.getTablename().hashCode());
		result = 37 * result
				+ (getKeyname() == null ? 0 : this.getKeyname().hashCode());
		result = 37 * result
				+ (getKeyvalue() == null ? 0 : this.getKeyvalue().hashCode());
		result = 37
				* result
				+ (getCreatedOnDt() == null ? 0 : this.getCreatedOnDt()
						.hashCode());
		result = 37
				* result
				+ (getCreatorPersonNum() == null ? 0 : this
						.getCreatorPersonNum().hashCode());
		result = 37
				* result
				+ (getLastModifyDt() == null ? 0 : this.getLastModifyDt()
						.hashCode());
		result = 37 * result + this.getModifyPersonNum();
		result = 37 * result + this.getLockNum();
		result = 37 * result + this.getDocumentSupportInd();
		result = 37 * result + this.getConfirmationSupportInd();
		result = 37
				* result
				+ (getMirrorKeyValue() == null ? 0 : this.getMirrorKeyValue()
						.hashCode());
		return result;
	}

}
