package com.mercon.entities;

// Generated Jun 18, 2014 11:58:16 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

/**
 * VopsItineraryId generated by hbm2java
 */
public class VopsItineraryId implements java.io.Serializable {

	/**
	 * Serial ID
	 */
	private static final long serialVersionUID = -7662616008978016975L;

	private int itineraryNum;
	private String itineraryName;
	private Integer operatorPersonNum;
	private VdimPersonId operatorPerson;
	private Short itineraryStatusInd;
	private short hasAttachmentInd;
	private Date startDt;
	private Date endDt;
	private Integer plannedMovementCnt;
	private Integer scheduledMovementCnt;
	private Integer intransitMovementCnt;
	private Integer arrivedMovementCnt;
	private Integer concludedMovementCnt;
	private Date createDt;
	private int internalCompanyNum;
	private short statusInd;
	private Integer noteNum;
	private Date lastModifyDt;
	private int modifyPersonNum;
	private int lockNum;
	private Integer vettedMovementCnt;
	private String ventureCd;
	private Integer nominatedMovementCnt;
	private Integer tentativeMovementCnt;
	private Integer acceptedMovementCnt;
	private Integer inprogressMovementCnt;
	private Integer dischargedMovementCnt;
	private Integer closedMovementCnt;
	private String itineraryNameNl;
	private String languageCd;
	private List<VopsMovement> movements;
	private Integer movementsSize;

	public VopsItineraryId() {
	}

	public VopsItineraryId(int itineraryNum, String itineraryName,
			Integer operatorPersonNum, VdimPersonId operatorPerson, Short itineraryStatusInd,
			short hasAttachmentInd, Date startDt, Date endDt,
			Integer plannedMovementCnt, Integer scheduledMovementCnt,
			Integer intransitMovementCnt, Integer arrivedMovementCnt,
			Integer concludedMovementCnt, Date createDt,
			int internalCompanyNum, short statusInd, Integer noteNum,
			Date lastModifyDt, int modifyPersonNum, int lockNum,
			Integer vettedMovementCnt, String ventureCd,
			Integer nominatedMovementCnt, Integer tentativeMovementCnt,
			Integer acceptedMovementCnt, Integer inprogressMovementCnt,
			Integer dischargedMovementCnt, Integer closedMovementCnt,
			String itineraryNameNl, String languageCd) {
		this.itineraryNum = itineraryNum;
		this.itineraryName = itineraryName;
		this.operatorPersonNum = operatorPersonNum;
		this.operatorPerson = operatorPerson;
		this.itineraryStatusInd = itineraryStatusInd;
		this.hasAttachmentInd = hasAttachmentInd;
		this.startDt = startDt;
		this.endDt = endDt;
		this.plannedMovementCnt = plannedMovementCnt;
		this.scheduledMovementCnt = scheduledMovementCnt;
		this.intransitMovementCnt = intransitMovementCnt;
		this.arrivedMovementCnt = arrivedMovementCnt;
		this.concludedMovementCnt = concludedMovementCnt;
		this.createDt = createDt;
		this.internalCompanyNum = internalCompanyNum;
		this.statusInd = statusInd;
		this.noteNum = noteNum;
		this.lastModifyDt = lastModifyDt;
		this.modifyPersonNum = modifyPersonNum;
		this.lockNum = lockNum;
		this.vettedMovementCnt = vettedMovementCnt;
		this.ventureCd = ventureCd;
		this.nominatedMovementCnt = nominatedMovementCnt;
		this.tentativeMovementCnt = tentativeMovementCnt;
		this.acceptedMovementCnt = acceptedMovementCnt;
		this.inprogressMovementCnt = inprogressMovementCnt;
		this.dischargedMovementCnt = dischargedMovementCnt;
		this.closedMovementCnt = closedMovementCnt;
		this.itineraryNameNl = itineraryNameNl;
		this.languageCd = languageCd;
	}

	public int getItineraryNum() {
		return this.itineraryNum;
	}

	public void setItineraryNum(int itineraryNum) {
		this.itineraryNum = itineraryNum;
	}

	public String getItineraryName() {
		return this.itineraryName;
	}

	public void setItineraryName(String itineraryName) {
		this.itineraryName = itineraryName;
	}

	public Integer getOperatorPersonNum() {
		return this.operatorPersonNum;
	}

	public void setOperatorPersonNum(Integer operatorPersonNum) {
		this.operatorPersonNum = operatorPersonNum;
	}
	
	public VdimPersonId getOperatorPerson() {
		return operatorPerson;
	}

	public void setOperatorPerson(VdimPersonId operatorPerson) {
		this.operatorPerson = operatorPerson;
	}

	public Short getItineraryStatusInd() {
		return this.itineraryStatusInd;
	}

	public void setItineraryStatusInd(Short itineraryStatusInd) {
		this.itineraryStatusInd = itineraryStatusInd;
	}

	public short getHasAttachmentInd() {
		return this.hasAttachmentInd;
	}

	public void setHasAttachmentInd(short hasAttachmentInd) {
		this.hasAttachmentInd = hasAttachmentInd;
	}

	public Date getStartDt() {
		return this.startDt;
	}

	public void setStartDt(Date startDt) {
		this.startDt = startDt;
	}

	public Date getEndDt() {
		return this.endDt;
	}

	public void setEndDt(Date endDt) {
		this.endDt = endDt;
	}

	public Integer getPlannedMovementCnt() {
		return this.plannedMovementCnt;
	}

	public void setPlannedMovementCnt(Integer plannedMovementCnt) {
		this.plannedMovementCnt = plannedMovementCnt;
	}

	public Integer getScheduledMovementCnt() {
		return this.scheduledMovementCnt;
	}

	public void setScheduledMovementCnt(Integer scheduledMovementCnt) {
		this.scheduledMovementCnt = scheduledMovementCnt;
	}

	public Integer getIntransitMovementCnt() {
		return this.intransitMovementCnt;
	}

	public void setIntransitMovementCnt(Integer intransitMovementCnt) {
		this.intransitMovementCnt = intransitMovementCnt;
	}

	public Integer getArrivedMovementCnt() {
		return this.arrivedMovementCnt;
	}

	public void setArrivedMovementCnt(Integer arrivedMovementCnt) {
		this.arrivedMovementCnt = arrivedMovementCnt;
	}

	public Integer getConcludedMovementCnt() {
		return this.concludedMovementCnt;
	}

	public void setConcludedMovementCnt(Integer concludedMovementCnt) {
		this.concludedMovementCnt = concludedMovementCnt;
	}

	public Date getCreateDt() {
		return this.createDt;
	}

	public void setCreateDt(Date createDt) {
		this.createDt = createDt;
	}

	public int getInternalCompanyNum() {
		return this.internalCompanyNum;
	}

	public void setInternalCompanyNum(int internalCompanyNum) {
		this.internalCompanyNum = internalCompanyNum;
	}

	public short getStatusInd() {
		return this.statusInd;
	}

	public void setStatusInd(short statusInd) {
		this.statusInd = statusInd;
	}

	public Integer getNoteNum() {
		return this.noteNum;
	}

	public void setNoteNum(Integer noteNum) {
		this.noteNum = noteNum;
	}

	public Date getLastModifyDt() {
		return this.lastModifyDt;
	}

	public void setLastModifyDt(Date lastModifyDt) {
		this.lastModifyDt = lastModifyDt;
	}

	public int getModifyPersonNum() {
		return this.modifyPersonNum;
	}

	public void setModifyPersonNum(int modifyPersonNum) {
		this.modifyPersonNum = modifyPersonNum;
	}

	public int getLockNum() {
		return this.lockNum;
	}

	public void setLockNum(int lockNum) {
		this.lockNum = lockNum;
	}

	public Integer getVettedMovementCnt() {
		return this.vettedMovementCnt;
	}

	public void setVettedMovementCnt(Integer vettedMovementCnt) {
		this.vettedMovementCnt = vettedMovementCnt;
	}

	public String getVentureCd() {
		return this.ventureCd;
	}

	public void setVentureCd(String ventureCd) {
		this.ventureCd = ventureCd;
	}

	public Integer getNominatedMovementCnt() {
		return this.nominatedMovementCnt;
	}

	public void setNominatedMovementCnt(Integer nominatedMovementCnt) {
		this.nominatedMovementCnt = nominatedMovementCnt;
	}

	public Integer getTentativeMovementCnt() {
		return this.tentativeMovementCnt;
	}

	public void setTentativeMovementCnt(Integer tentativeMovementCnt) {
		this.tentativeMovementCnt = tentativeMovementCnt;
	}

	public Integer getAcceptedMovementCnt() {
		return this.acceptedMovementCnt;
	}

	public void setAcceptedMovementCnt(Integer acceptedMovementCnt) {
		this.acceptedMovementCnt = acceptedMovementCnt;
	}

	public Integer getInprogressMovementCnt() {
		return this.inprogressMovementCnt;
	}

	public void setInprogressMovementCnt(Integer inprogressMovementCnt) {
		this.inprogressMovementCnt = inprogressMovementCnt;
	}

	public Integer getDischargedMovementCnt() {
		return this.dischargedMovementCnt;
	}

	public void setDischargedMovementCnt(Integer dischargedMovementCnt) {
		this.dischargedMovementCnt = dischargedMovementCnt;
	}

	public Integer getClosedMovementCnt() {
		return this.closedMovementCnt;
	}

	public void setClosedMovementCnt(Integer closedMovementCnt) {
		this.closedMovementCnt = closedMovementCnt;
	}

	public String getItineraryNameNl() {
		return this.itineraryNameNl;
	}

	public void setItineraryNameNl(String itineraryNameNl) {
		this.itineraryNameNl = itineraryNameNl;
	}

	public String getLanguageCd() {
		return this.languageCd;
	}

	public void setLanguageCd(String languageCd) {
		this.languageCd = languageCd;
	}

	public List<VopsMovement> getMovements() {
		return movements;
	}

	public void setMovements(List<VopsMovement> movements) {
		this.movements = movements;
	}
	
	public Integer getMovementsSize() {
		movementsSize = movements.size();
		return movementsSize;
	}

	public void setMovementsSize(Integer movementsSize) {
		this.movementsSize = movementsSize;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((acceptedMovementCnt == null) ? 0 : acceptedMovementCnt
						.hashCode());
		result = prime
				* result
				+ ((arrivedMovementCnt == null) ? 0 : arrivedMovementCnt
						.hashCode());
		result = prime
				* result
				+ ((closedMovementCnt == null) ? 0 : closedMovementCnt
						.hashCode());
		result = prime
				* result
				+ ((concludedMovementCnt == null) ? 0 : concludedMovementCnt
						.hashCode());
		result = prime * result
				+ ((createDt == null) ? 0 : createDt.hashCode());
		result = prime
				* result
				+ ((dischargedMovementCnt == null) ? 0 : dischargedMovementCnt
						.hashCode());
		result = prime * result + ((endDt == null) ? 0 : endDt.hashCode());
		result = prime * result + hasAttachmentInd;
		result = prime
				* result
				+ ((inprogressMovementCnt == null) ? 0 : inprogressMovementCnt
						.hashCode());
		result = prime * result + internalCompanyNum;
		result = prime
				* result
				+ ((intransitMovementCnt == null) ? 0 : intransitMovementCnt
						.hashCode());
		result = prime * result
				+ ((itineraryName == null) ? 0 : itineraryName.hashCode());
		result = prime * result
				+ ((itineraryNameNl == null) ? 0 : itineraryNameNl.hashCode());
		result = prime * result + itineraryNum;
		result = prime
				* result
				+ ((itineraryStatusInd == null) ? 0 : itineraryStatusInd
						.hashCode());
		result = prime * result
				+ ((languageCd == null) ? 0 : languageCd.hashCode());
		result = prime * result
				+ ((lastModifyDt == null) ? 0 : lastModifyDt.hashCode());
		result = prime * result + lockNum;
		result = prime * result + modifyPersonNum;
		result = prime * result
				+ ((movements == null) ? 0 : movements.hashCode());
		result = prime
				* result
				+ ((nominatedMovementCnt == null) ? 0 : nominatedMovementCnt
						.hashCode());
		result = prime * result + ((noteNum == null) ? 0 : noteNum.hashCode());
		result = prime * result
				+ ((operatorPerson == null) ? 0 : operatorPerson.hashCode());
		result = prime
				* result
				+ ((operatorPersonNum == null) ? 0 : operatorPersonNum
						.hashCode());
		result = prime
				* result
				+ ((plannedMovementCnt == null) ? 0 : plannedMovementCnt
						.hashCode());
		result = prime
				* result
				+ ((scheduledMovementCnt == null) ? 0 : scheduledMovementCnt
						.hashCode());
		result = prime * result + ((startDt == null) ? 0 : startDt.hashCode());
		result = prime * result + statusInd;
		result = prime
				* result
				+ ((tentativeMovementCnt == null) ? 0 : tentativeMovementCnt
						.hashCode());
		result = prime * result
				+ ((ventureCd == null) ? 0 : ventureCd.hashCode());
		result = prime
				* result
				+ ((vettedMovementCnt == null) ? 0 : vettedMovementCnt
						.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		VopsItineraryId other = (VopsItineraryId) obj;
		if (acceptedMovementCnt == null) {
			if (other.acceptedMovementCnt != null)
				return false;
		} else if (!acceptedMovementCnt.equals(other.acceptedMovementCnt))
			return false;
		if (arrivedMovementCnt == null) {
			if (other.arrivedMovementCnt != null)
				return false;
		} else if (!arrivedMovementCnt.equals(other.arrivedMovementCnt))
			return false;
		if (closedMovementCnt == null) {
			if (other.closedMovementCnt != null)
				return false;
		} else if (!closedMovementCnt.equals(other.closedMovementCnt))
			return false;
		if (concludedMovementCnt == null) {
			if (other.concludedMovementCnt != null)
				return false;
		} else if (!concludedMovementCnt.equals(other.concludedMovementCnt))
			return false;
		if (createDt == null) {
			if (other.createDt != null)
				return false;
		} else if (!createDt.equals(other.createDt))
			return false;
		if (dischargedMovementCnt == null) {
			if (other.dischargedMovementCnt != null)
				return false;
		} else if (!dischargedMovementCnt.equals(other.dischargedMovementCnt))
			return false;
		if (endDt == null) {
			if (other.endDt != null)
				return false;
		} else if (!endDt.equals(other.endDt))
			return false;
		if (hasAttachmentInd != other.hasAttachmentInd)
			return false;
		if (inprogressMovementCnt == null) {
			if (other.inprogressMovementCnt != null)
				return false;
		} else if (!inprogressMovementCnt.equals(other.inprogressMovementCnt))
			return false;
		if (internalCompanyNum != other.internalCompanyNum)
			return false;
		if (intransitMovementCnt == null) {
			if (other.intransitMovementCnt != null)
				return false;
		} else if (!intransitMovementCnt.equals(other.intransitMovementCnt))
			return false;
		if (itineraryName == null) {
			if (other.itineraryName != null)
				return false;
		} else if (!itineraryName.equals(other.itineraryName))
			return false;
		if (itineraryNameNl == null) {
			if (other.itineraryNameNl != null)
				return false;
		} else if (!itineraryNameNl.equals(other.itineraryNameNl))
			return false;
		if (itineraryNum != other.itineraryNum)
			return false;
		if (itineraryStatusInd == null) {
			if (other.itineraryStatusInd != null)
				return false;
		} else if (!itineraryStatusInd.equals(other.itineraryStatusInd))
			return false;
		if (languageCd == null) {
			if (other.languageCd != null)
				return false;
		} else if (!languageCd.equals(other.languageCd))
			return false;
		if (lastModifyDt == null) {
			if (other.lastModifyDt != null)
				return false;
		} else if (!lastModifyDt.equals(other.lastModifyDt))
			return false;
		if (lockNum != other.lockNum)
			return false;
		if (modifyPersonNum != other.modifyPersonNum)
			return false;
		if (movements == null) {
			if (other.movements != null)
				return false;
		} else if (!movements.equals(other.movements))
			return false;
		if (nominatedMovementCnt == null) {
			if (other.nominatedMovementCnt != null)
				return false;
		} else if (!nominatedMovementCnt.equals(other.nominatedMovementCnt))
			return false;
		if (noteNum == null) {
			if (other.noteNum != null)
				return false;
		} else if (!noteNum.equals(other.noteNum))
			return false;
		if (operatorPerson == null) {
			if (other.operatorPerson != null)
				return false;
		} else if (!operatorPerson.equals(other.operatorPerson))
			return false;
		if (operatorPersonNum == null) {
			if (other.operatorPersonNum != null)
				return false;
		} else if (!operatorPersonNum.equals(other.operatorPersonNum))
			return false;
		if (plannedMovementCnt == null) {
			if (other.plannedMovementCnt != null)
				return false;
		} else if (!plannedMovementCnt.equals(other.plannedMovementCnt))
			return false;
		if (scheduledMovementCnt == null) {
			if (other.scheduledMovementCnt != null)
				return false;
		} else if (!scheduledMovementCnt.equals(other.scheduledMovementCnt))
			return false;
		if (startDt == null) {
			if (other.startDt != null)
				return false;
		} else if (!startDt.equals(other.startDt))
			return false;
		if (statusInd != other.statusInd)
			return false;
		if (tentativeMovementCnt == null) {
			if (other.tentativeMovementCnt != null)
				return false;
		} else if (!tentativeMovementCnt.equals(other.tentativeMovementCnt))
			return false;
		if (ventureCd == null) {
			if (other.ventureCd != null)
				return false;
		} else if (!ventureCd.equals(other.ventureCd))
			return false;
		if (vettedMovementCnt == null) {
			if (other.vettedMovementCnt != null)
				return false;
		} else if (!vettedMovementCnt.equals(other.vettedMovementCnt))
			return false;
		return true;
	}
	
}
