package com.mercon.entities;

// Generated Jun 18, 2014 11:58:16 AM by Hibernate Tools 3.4.0.CR1

/**
 * VopsItinerary generated by hbm2java
 */
public class VopsItinerary implements java.io.Serializable {

	/**
	 * Serial ID
	 */
	private static final long serialVersionUID = -612650366385537821L;

	private VopsItineraryId id;

	public VopsItinerary() {
	}

	public VopsItinerary(VopsItineraryId id) {
		this.id = id;
	}

	public VopsItineraryId getId() {
		return this.id;
	}

	public void setId(VopsItineraryId id) {
		this.id = id;
	}

}
