package com.mercon.entities;

// Generated Aug 6, 2014 2:29:04 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * VopsItiDefaultActionDetailId generated by hbm2java
 */
public class VopsItiDefaultActionDetailId implements java.io.Serializable {

	/**
	 * Serial ID
	 */
	private static final long serialVersionUID = -8423189870678030097L;
	
	private int itineraryNum;
	private int actionDetailNum;
	private int actionSeqNum;
	private short actionPriority;
	private short actionEventBasedInd;
	private Date actionDueDt;
	private Date actionCompletionDt;
	private Short actionCompletedInd;
	private Integer userPersonNum;
	private String actionDescription;
	private String docTemplateCd;
	private short movementStatusInd;
	private short itineraryStatusInd;
	private short eventDays;
	private short eventOccurrenceTimeInd;
	private short customEventDateInd;
	private String calendarCd;
	private short saturdayRuleInd;
	private short sundayRuleInd;
	private short holidayRuleInd;
	private int noteNum;
	private int modifyPersonNum;
	private Date lastModifyDt;
	private int lockNum;
	private short alertDeliveryInd;
	private String actionGroupCd;
	private Integer movementNum;
	private int docNum;
	private int docVersionNum;
	private short docHeaderStatusInd;
	private Short notificationTypeInd;

	public VopsItiDefaultActionDetailId() {
	}

	public VopsItiDefaultActionDetailId(int itineraryNum, int actionDetailNum,
			int actionSeqNum, short actionPriority, short actionEventBasedInd,
			String actionDescription, String docTemplateCd,
			short movementStatusInd, short itineraryStatusInd, short eventDays,
			short eventOccurrenceTimeInd, short customEventDateInd,
			String calendarCd, short saturdayRuleInd, short sundayRuleInd,
			short holidayRuleInd, int noteNum, int modifyPersonNum,
			Date lastModifyDt, int lockNum, short alertDeliveryInd,
			String actionGroupCd, int docNum, int docVersionNum,
			short docHeaderStatusInd) {
		this.itineraryNum = itineraryNum;
		this.actionDetailNum = actionDetailNum;
		this.actionSeqNum = actionSeqNum;
		this.actionPriority = actionPriority;
		this.actionEventBasedInd = actionEventBasedInd;
		this.actionDescription = actionDescription;
		this.docTemplateCd = docTemplateCd;
		this.movementStatusInd = movementStatusInd;
		this.itineraryStatusInd = itineraryStatusInd;
		this.eventDays = eventDays;
		this.eventOccurrenceTimeInd = eventOccurrenceTimeInd;
		this.customEventDateInd = customEventDateInd;
		this.calendarCd = calendarCd;
		this.saturdayRuleInd = saturdayRuleInd;
		this.sundayRuleInd = sundayRuleInd;
		this.holidayRuleInd = holidayRuleInd;
		this.noteNum = noteNum;
		this.modifyPersonNum = modifyPersonNum;
		this.lastModifyDt = lastModifyDt;
		this.lockNum = lockNum;
		this.alertDeliveryInd = alertDeliveryInd;
		this.actionGroupCd = actionGroupCd;
		this.docNum = docNum;
		this.docVersionNum = docVersionNum;
		this.docHeaderStatusInd = docHeaderStatusInd;
	}

	public VopsItiDefaultActionDetailId(int itineraryNum, int actionDetailNum,
			int actionSeqNum, short actionPriority, short actionEventBasedInd,
			Date actionDueDt, Date actionCompletionDt,
			Short actionCompletedInd, Integer userPersonNum,
			String actionDescription, String docTemplateCd,
			short movementStatusInd, short itineraryStatusInd, short eventDays,
			short eventOccurrenceTimeInd, short customEventDateInd,
			String calendarCd, short saturdayRuleInd, short sundayRuleInd,
			short holidayRuleInd, int noteNum, int modifyPersonNum,
			Date lastModifyDt, int lockNum, short alertDeliveryInd,
			String actionGroupCd, Integer movementNum, int docNum,
			int docVersionNum, short docHeaderStatusInd,
			Short notificationTypeInd) {
		this.itineraryNum = itineraryNum;
		this.actionDetailNum = actionDetailNum;
		this.actionSeqNum = actionSeqNum;
		this.actionPriority = actionPriority;
		this.actionEventBasedInd = actionEventBasedInd;
		this.actionDueDt = actionDueDt;
		this.actionCompletionDt = actionCompletionDt;
		this.actionCompletedInd = actionCompletedInd;
		this.userPersonNum = userPersonNum;
		this.actionDescription = actionDescription;
		this.docTemplateCd = docTemplateCd;
		this.movementStatusInd = movementStatusInd;
		this.itineraryStatusInd = itineraryStatusInd;
		this.eventDays = eventDays;
		this.eventOccurrenceTimeInd = eventOccurrenceTimeInd;
		this.customEventDateInd = customEventDateInd;
		this.calendarCd = calendarCd;
		this.saturdayRuleInd = saturdayRuleInd;
		this.sundayRuleInd = sundayRuleInd;
		this.holidayRuleInd = holidayRuleInd;
		this.noteNum = noteNum;
		this.modifyPersonNum = modifyPersonNum;
		this.lastModifyDt = lastModifyDt;
		this.lockNum = lockNum;
		this.alertDeliveryInd = alertDeliveryInd;
		this.actionGroupCd = actionGroupCd;
		this.movementNum = movementNum;
		this.docNum = docNum;
		this.docVersionNum = docVersionNum;
		this.docHeaderStatusInd = docHeaderStatusInd;
		this.notificationTypeInd = notificationTypeInd;
	}

	public int getItineraryNum() {
		return this.itineraryNum;
	}

	public void setItineraryNum(int itineraryNum) {
		this.itineraryNum = itineraryNum;
	}

	public int getActionDetailNum() {
		return this.actionDetailNum;
	}

	public void setActionDetailNum(int actionDetailNum) {
		this.actionDetailNum = actionDetailNum;
	}

	public int getActionSeqNum() {
		return this.actionSeqNum;
	}

	public void setActionSeqNum(int actionSeqNum) {
		this.actionSeqNum = actionSeqNum;
	}

	public short getActionPriority() {
		return this.actionPriority;
	}

	public void setActionPriority(short actionPriority) {
		this.actionPriority = actionPriority;
	}

	public short getActionEventBasedInd() {
		return this.actionEventBasedInd;
	}

	public void setActionEventBasedInd(short actionEventBasedInd) {
		this.actionEventBasedInd = actionEventBasedInd;
	}

	public Date getActionDueDt() {
		return this.actionDueDt;
	}

	public void setActionDueDt(Date actionDueDt) {
		this.actionDueDt = actionDueDt;
	}

	public Date getActionCompletionDt() {
		return this.actionCompletionDt;
	}

	public void setActionCompletionDt(Date actionCompletionDt) {
		this.actionCompletionDt = actionCompletionDt;
	}

	public Short getActionCompletedInd() {
		return this.actionCompletedInd;
	}

	public void setActionCompletedInd(Short actionCompletedInd) {
		this.actionCompletedInd = actionCompletedInd;
	}

	public Integer getUserPersonNum() {
		return this.userPersonNum;
	}

	public void setUserPersonNum(Integer userPersonNum) {
		this.userPersonNum = userPersonNum;
	}

	public String getActionDescription() {
		return this.actionDescription;
	}

	public void setActionDescription(String actionDescription) {
		this.actionDescription = actionDescription;
	}

	public String getDocTemplateCd() {
		return this.docTemplateCd;
	}

	public void setDocTemplateCd(String docTemplateCd) {
		this.docTemplateCd = docTemplateCd;
	}

	public short getMovementStatusInd() {
		return this.movementStatusInd;
	}

	public void setMovementStatusInd(short movementStatusInd) {
		this.movementStatusInd = movementStatusInd;
	}

	public short getItineraryStatusInd() {
		return this.itineraryStatusInd;
	}

	public void setItineraryStatusInd(short itineraryStatusInd) {
		this.itineraryStatusInd = itineraryStatusInd;
	}

	public short getEventDays() {
		return this.eventDays;
	}

	public void setEventDays(short eventDays) {
		this.eventDays = eventDays;
	}

	public short getEventOccurrenceTimeInd() {
		return this.eventOccurrenceTimeInd;
	}

	public void setEventOccurrenceTimeInd(short eventOccurrenceTimeInd) {
		this.eventOccurrenceTimeInd = eventOccurrenceTimeInd;
	}

	public short getCustomEventDateInd() {
		return this.customEventDateInd;
	}

	public void setCustomEventDateInd(short customEventDateInd) {
		this.customEventDateInd = customEventDateInd;
	}

	public String getCalendarCd() {
		return this.calendarCd;
	}

	public void setCalendarCd(String calendarCd) {
		this.calendarCd = calendarCd;
	}

	public short getSaturdayRuleInd() {
		return this.saturdayRuleInd;
	}

	public void setSaturdayRuleInd(short saturdayRuleInd) {
		this.saturdayRuleInd = saturdayRuleInd;
	}

	public short getSundayRuleInd() {
		return this.sundayRuleInd;
	}

	public void setSundayRuleInd(short sundayRuleInd) {
		this.sundayRuleInd = sundayRuleInd;
	}

	public short getHolidayRuleInd() {
		return this.holidayRuleInd;
	}

	public void setHolidayRuleInd(short holidayRuleInd) {
		this.holidayRuleInd = holidayRuleInd;
	}

	public int getNoteNum() {
		return this.noteNum;
	}

	public void setNoteNum(int noteNum) {
		this.noteNum = noteNum;
	}

	public int getModifyPersonNum() {
		return this.modifyPersonNum;
	}

	public void setModifyPersonNum(int modifyPersonNum) {
		this.modifyPersonNum = modifyPersonNum;
	}

	public Date getLastModifyDt() {
		return this.lastModifyDt;
	}

	public void setLastModifyDt(Date lastModifyDt) {
		this.lastModifyDt = lastModifyDt;
	}

	public int getLockNum() {
		return this.lockNum;
	}

	public void setLockNum(int lockNum) {
		this.lockNum = lockNum;
	}

	public short getAlertDeliveryInd() {
		return this.alertDeliveryInd;
	}

	public void setAlertDeliveryInd(short alertDeliveryInd) {
		this.alertDeliveryInd = alertDeliveryInd;
	}

	public String getActionGroupCd() {
		return this.actionGroupCd;
	}

	public void setActionGroupCd(String actionGroupCd) {
		this.actionGroupCd = actionGroupCd;
	}

	public Integer getMovementNum() {
		return this.movementNum;
	}

	public void setMovementNum(Integer movementNum) {
		this.movementNum = movementNum;
	}

	public int getDocNum() {
		return this.docNum;
	}

	public void setDocNum(int docNum) {
		this.docNum = docNum;
	}

	public int getDocVersionNum() {
		return this.docVersionNum;
	}

	public void setDocVersionNum(int docVersionNum) {
		this.docVersionNum = docVersionNum;
	}

	public short getDocHeaderStatusInd() {
		return this.docHeaderStatusInd;
	}

	public void setDocHeaderStatusInd(short docHeaderStatusInd) {
		this.docHeaderStatusInd = docHeaderStatusInd;
	}

	public Short getNotificationTypeInd() {
		return this.notificationTypeInd;
	}

	public void setNotificationTypeInd(Short notificationTypeInd) {
		this.notificationTypeInd = notificationTypeInd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VopsItiDefaultActionDetailId))
			return false;
		VopsItiDefaultActionDetailId castOther = (VopsItiDefaultActionDetailId) other;

		return (this.getItineraryNum() == castOther.getItineraryNum())
				&& (this.getActionDetailNum() == castOther.getActionDetailNum())
				&& (this.getActionSeqNum() == castOther.getActionSeqNum())
				&& (this.getActionPriority() == castOther.getActionPriority())
				&& (this.getActionEventBasedInd() == castOther
						.getActionEventBasedInd())
				&& ((this.getActionDueDt() == castOther.getActionDueDt()) || (this
						.getActionDueDt() != null
						&& castOther.getActionDueDt() != null && this
						.getActionDueDt().equals(castOther.getActionDueDt())))
				&& ((this.getActionCompletionDt() == castOther
						.getActionCompletionDt()) || (this
						.getActionCompletionDt() != null
						&& castOther.getActionCompletionDt() != null && this
						.getActionCompletionDt().equals(
								castOther.getActionCompletionDt())))
				&& ((this.getActionCompletedInd() == castOther
						.getActionCompletedInd()) || (this
						.getActionCompletedInd() != null
						&& castOther.getActionCompletedInd() != null && this
						.getActionCompletedInd().equals(
								castOther.getActionCompletedInd())))
				&& ((this.getUserPersonNum() == castOther.getUserPersonNum()) || (this
						.getUserPersonNum() != null
						&& castOther.getUserPersonNum() != null && this
						.getUserPersonNum()
						.equals(castOther.getUserPersonNum())))
				&& ((this.getActionDescription() == castOther
						.getActionDescription()) || (this
						.getActionDescription() != null
						&& castOther.getActionDescription() != null && this
						.getActionDescription().equals(
								castOther.getActionDescription())))
				&& ((this.getDocTemplateCd() == castOther.getDocTemplateCd()) || (this
						.getDocTemplateCd() != null
						&& castOther.getDocTemplateCd() != null && this
						.getDocTemplateCd()
						.equals(castOther.getDocTemplateCd())))
				&& (this.getMovementStatusInd() == castOther
						.getMovementStatusInd())
				&& (this.getItineraryStatusInd() == castOther
						.getItineraryStatusInd())
				&& (this.getEventDays() == castOther.getEventDays())
				&& (this.getEventOccurrenceTimeInd() == castOther
						.getEventOccurrenceTimeInd())
				&& (this.getCustomEventDateInd() == castOther
						.getCustomEventDateInd())
				&& ((this.getCalendarCd() == castOther.getCalendarCd()) || (this
						.getCalendarCd() != null
						&& castOther.getCalendarCd() != null && this
						.getCalendarCd().equals(castOther.getCalendarCd())))
				&& (this.getSaturdayRuleInd() == castOther.getSaturdayRuleInd())
				&& (this.getSundayRuleInd() == castOther.getSundayRuleInd())
				&& (this.getHolidayRuleInd() == castOther.getHolidayRuleInd())
				&& (this.getNoteNum() == castOther.getNoteNum())
				&& (this.getModifyPersonNum() == castOther.getModifyPersonNum())
				&& ((this.getLastModifyDt() == castOther.getLastModifyDt()) || (this
						.getLastModifyDt() != null
						&& castOther.getLastModifyDt() != null && this
						.getLastModifyDt().equals(castOther.getLastModifyDt())))
				&& (this.getLockNum() == castOther.getLockNum())
				&& (this.getAlertDeliveryInd() == castOther
						.getAlertDeliveryInd())
				&& ((this.getActionGroupCd() == castOther.getActionGroupCd()) || (this
						.getActionGroupCd() != null
						&& castOther.getActionGroupCd() != null && this
						.getActionGroupCd()
						.equals(castOther.getActionGroupCd())))
				&& ((this.getMovementNum() == castOther.getMovementNum()) || (this
						.getMovementNum() != null
						&& castOther.getMovementNum() != null && this
						.getMovementNum().equals(castOther.getMovementNum())))
				&& (this.getDocNum() == castOther.getDocNum())
				&& (this.getDocVersionNum() == castOther.getDocVersionNum())
				&& (this.getDocHeaderStatusInd() == castOther
						.getDocHeaderStatusInd())
				&& ((this.getNotificationTypeInd() == castOther
						.getNotificationTypeInd()) || (this
						.getNotificationTypeInd() != null
						&& castOther.getNotificationTypeInd() != null && this
						.getNotificationTypeInd().equals(
								castOther.getNotificationTypeInd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getItineraryNum();
		result = 37 * result + this.getActionDetailNum();
		result = 37 * result + this.getActionSeqNum();
		result = 37 * result + this.getActionPriority();
		result = 37 * result + this.getActionEventBasedInd();
		result = 37
				* result
				+ (getActionDueDt() == null ? 0 : this.getActionDueDt()
						.hashCode());
		result = 37
				* result
				+ (getActionCompletionDt() == null ? 0 : this
						.getActionCompletionDt().hashCode());
		result = 37
				* result
				+ (getActionCompletedInd() == null ? 0 : this
						.getActionCompletedInd().hashCode());
		result = 37
				* result
				+ (getUserPersonNum() == null ? 0 : this.getUserPersonNum()
						.hashCode());
		result = 37
				* result
				+ (getActionDescription() == null ? 0 : this
						.getActionDescription().hashCode());
		result = 37
				* result
				+ (getDocTemplateCd() == null ? 0 : this.getDocTemplateCd()
						.hashCode());
		result = 37 * result + this.getMovementStatusInd();
		result = 37 * result + this.getItineraryStatusInd();
		result = 37 * result + this.getEventDays();
		result = 37 * result + this.getEventOccurrenceTimeInd();
		result = 37 * result + this.getCustomEventDateInd();
		result = 37
				* result
				+ (getCalendarCd() == null ? 0 : this.getCalendarCd()
						.hashCode());
		result = 37 * result + this.getSaturdayRuleInd();
		result = 37 * result + this.getSundayRuleInd();
		result = 37 * result + this.getHolidayRuleInd();
		result = 37 * result + this.getNoteNum();
		result = 37 * result + this.getModifyPersonNum();
		result = 37
				* result
				+ (getLastModifyDt() == null ? 0 : this.getLastModifyDt()
						.hashCode());
		result = 37 * result + this.getLockNum();
		result = 37 * result + this.getAlertDeliveryInd();
		result = 37
				* result
				+ (getActionGroupCd() == null ? 0 : this.getActionGroupCd()
						.hashCode());
		result = 37
				* result
				+ (getMovementNum() == null ? 0 : this.getMovementNum()
						.hashCode());
		result = 37 * result + this.getDocNum();
		result = 37 * result + this.getDocVersionNum();
		result = 37 * result + this.getDocHeaderStatusInd();
		result = 37
				* result
				+ (getNotificationTypeInd() == null ? 0 : this
						.getNotificationTypeInd().hashCode());
		return result;
	}

}
