package com.mercon.entities;

// Generated Aug 7, 2014 10:54:12 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * VopsObligationHdrId generated by hbm2java
 */
public class VopsObligationHdrId implements java.io.Serializable {

	/**
	 * Serial ID
	 */
	private static final long serialVersionUID = 7949299551413465915L;

	private int obligationNum;
	private String mtmPremiumUomCd;
	private String mtmPremiumCurrCd;
	private int mtmQuoteDefNum;
	private String mtmPeriodCd;
	private int jvCounterpartCompanyNum;
	private Integer strategyNum;
	private int termNum;
	private Integer tradeNum;
	private int detailNum;
	private Integer internalCoNum;
	private Integer companyNum;
	private Short buySellInd;
	private String cmdtyCd;
	private Integer locationNum;
	private Short motTypeInd;
	private Integer traderPersonNum;
	private String deliveryTermCd;
	private BigDecimal baseQty;
	private String baseUomCd;
	private BigDecimal contractQty;
	private String contractUomCd;
	private BigDecimal openQty;
	private BigDecimal delivQty;
	private String delivUomCd;
	private BigDecimal packagingQty;
	private String packagingUomCd;
	private String settlementCurrCd;
	private String settlementUomCd;
	private BigDecimal uomConversionRate;
	private BigDecimal price;
	private String priceUomCd;
	private String priceCurrCd;
	private BigDecimal priceScr;
	private short priceStatusInd;
	private BigDecimal apiGravity;
	private BigDecimal specificGravity;
	private short airVacInd;
	private Short internalInd;
	private Date laycanStartDt;
	private Date laycanEndDt;
	private Integer mtmFwdCurveNum;
	private Short formulaPriceEventInd;
	private Short payDtEvent1Ind;
	private Short payDtEvent2Ind;
	private Date deemedBlDt;
	private Date deemedNorDt;
	private Date deemedCommLDt;
	private Date deemedCompLDt;
	private Date deemedCommDDt;
	private Date deemedCompDDt;
	private Date deemedRoiDt;
	private Date deemedDeliveryMonthEndDt;
	private Date riskStartDt;
	private Short timePeriodTypeInd;
	private int motNum;
	private Integer originLocNum;
	private short tradeStatusInd;
	private String deliverySchedCd;
	private BigDecimal minTolerance;
	private BigDecimal maxTolerance;
	private String termSectionCd;
	private String purchaseCategoryCd;
	private BigDecimal openBalAdjQty;
	private Integer rfVersionNum;
	private BigDecimal priceLumpScr;
	private BigDecimal baseuomConvFactor;
	private BigDecimal bblMtFactor;
	private BigDecimal mtmPremium;
	private int obligationOpenbalNum;
	private Date paymentDueDt;
	private BigDecimal toleranceBelowPct;
	private BigDecimal toleranceAbovePct;
	private String pipelineCycleCd;
	private Date lastModifyDt;
	private int modifyPersonNum;
	private int lockNum;
	private Short obligationTypeInd;
	private BigDecimal stdPrice;
	private String stdPriceCurrCd;
	private String stdPriceUomCd;
	private int planningLocationNum;
	private String tradeTypeCd;
	private String instrumentTypeCd;
	private Short obligationScheduledInd;
	private String ventureCd;
	private short customsDutyStatusInd;
	private short schConfExecutedInd;
	private Short statusInd;
	private String externalRef;
	private String tradePriceCurrCd;
	private String specCd;
	private String settlePaymentTermCd;
	private short pricingStatusInd;
	private short futuresPricingStatusInd;
	private short basisPricingStatusInd;
	private int shippingCompanyNum;
	private Integer originationLocNum;
	private int destinationLocNum;
	private short interCompInd;
	private int interCompTrdNum;
	private int interCompOpenbalNum;
	private Date reportingPeriodDt;
	private BigDecimal min1ToleranceQty;
	private BigDecimal max1ToleranceQty;
	private BigDecimal toleranceBaseQty;
	private BigDecimal toleranceDelivQty;
	private BigDecimal overUnderShipmentQty;
	private short bulkToleranceScheduleInd;
	private BigDecimal uptoTmin1Qty;
	private BigDecimal uptoTmax1Qty;

	public VopsObligationHdrId() {
	}

	public VopsObligationHdrId(int obligationNum, String mtmPremiumUomCd,
			String mtmPremiumCurrCd, int mtmQuoteDefNum, String mtmPeriodCd,
			int jvCounterpartCompanyNum, int termNum, int detailNum,
			BigDecimal packagingQty, String packagingUomCd,
			short priceStatusInd, BigDecimal apiGravity,
			BigDecimal specificGravity, short airVacInd, Date deemedBlDt,
			Date deemedNorDt, Date deemedCommLDt, Date deemedCompLDt,
			Date deemedCommDDt, Date deemedCompDDt, Date deemedRoiDt,
			Date deemedDeliveryMonthEndDt, int motNum, short tradeStatusInd,
			BigDecimal minTolerance, BigDecimal maxTolerance,
			String purchaseCategoryCd, BigDecimal openBalAdjQty,
			BigDecimal mtmPremium, int obligationOpenbalNum,
			BigDecimal toleranceBelowPct, BigDecimal toleranceAbovePct,
			String pipelineCycleCd, Date lastModifyDt, int modifyPersonNum,
			int lockNum, int planningLocationNum, String ventureCd,
			short customsDutyStatusInd, short schConfExecutedInd,
			String externalRef, String specCd, short pricingStatusInd,
			short futuresPricingStatusInd, short basisPricingStatusInd,
			int shippingCompanyNum, int destinationLocNum, short interCompInd,
			int interCompTrdNum, int interCompOpenbalNum,
			BigDecimal min1ToleranceQty, BigDecimal max1ToleranceQty,
			BigDecimal toleranceBaseQty, BigDecimal toleranceDelivQty,
			BigDecimal overUnderShipmentQty, short bulkToleranceScheduleInd,
			BigDecimal uptoTmin1Qty, BigDecimal uptoTmax1Qty) {
		this.obligationNum = obligationNum;
		this.mtmPremiumUomCd = mtmPremiumUomCd;
		this.mtmPremiumCurrCd = mtmPremiumCurrCd;
		this.mtmQuoteDefNum = mtmQuoteDefNum;
		this.mtmPeriodCd = mtmPeriodCd;
		this.jvCounterpartCompanyNum = jvCounterpartCompanyNum;
		this.termNum = termNum;
		this.detailNum = detailNum;
		this.packagingQty = packagingQty;
		this.packagingUomCd = packagingUomCd;
		this.priceStatusInd = priceStatusInd;
		this.apiGravity = apiGravity;
		this.specificGravity = specificGravity;
		this.airVacInd = airVacInd;
		this.deemedBlDt = deemedBlDt;
		this.deemedNorDt = deemedNorDt;
		this.deemedCommLDt = deemedCommLDt;
		this.deemedCompLDt = deemedCompLDt;
		this.deemedCommDDt = deemedCommDDt;
		this.deemedCompDDt = deemedCompDDt;
		this.deemedRoiDt = deemedRoiDt;
		this.deemedDeliveryMonthEndDt = deemedDeliveryMonthEndDt;
		this.motNum = motNum;
		this.tradeStatusInd = tradeStatusInd;
		this.minTolerance = minTolerance;
		this.maxTolerance = maxTolerance;
		this.purchaseCategoryCd = purchaseCategoryCd;
		this.openBalAdjQty = openBalAdjQty;
		this.mtmPremium = mtmPremium;
		this.obligationOpenbalNum = obligationOpenbalNum;
		this.toleranceBelowPct = toleranceBelowPct;
		this.toleranceAbovePct = toleranceAbovePct;
		this.pipelineCycleCd = pipelineCycleCd;
		this.lastModifyDt = lastModifyDt;
		this.modifyPersonNum = modifyPersonNum;
		this.lockNum = lockNum;
		this.planningLocationNum = planningLocationNum;
		this.ventureCd = ventureCd;
		this.customsDutyStatusInd = customsDutyStatusInd;
		this.schConfExecutedInd = schConfExecutedInd;
		this.externalRef = externalRef;
		this.specCd = specCd;
		this.pricingStatusInd = pricingStatusInd;
		this.futuresPricingStatusInd = futuresPricingStatusInd;
		this.basisPricingStatusInd = basisPricingStatusInd;
		this.shippingCompanyNum = shippingCompanyNum;
		this.destinationLocNum = destinationLocNum;
		this.interCompInd = interCompInd;
		this.interCompTrdNum = interCompTrdNum;
		this.interCompOpenbalNum = interCompOpenbalNum;
		this.min1ToleranceQty = min1ToleranceQty;
		this.max1ToleranceQty = max1ToleranceQty;
		this.toleranceBaseQty = toleranceBaseQty;
		this.toleranceDelivQty = toleranceDelivQty;
		this.overUnderShipmentQty = overUnderShipmentQty;
		this.bulkToleranceScheduleInd = bulkToleranceScheduleInd;
		this.uptoTmin1Qty = uptoTmin1Qty;
		this.uptoTmax1Qty = uptoTmax1Qty;
	}

	public VopsObligationHdrId(int obligationNum, String mtmPremiumUomCd,
			String mtmPremiumCurrCd, int mtmQuoteDefNum, String mtmPeriodCd,
			int jvCounterpartCompanyNum, Integer strategyNum, int termNum,
			Integer tradeNum, int detailNum, Integer internalCoNum,
			Integer companyNum, Short buySellInd, String cmdtyCd,
			Integer locationNum, Short motTypeInd, Integer traderPersonNum,
			String deliveryTermCd, BigDecimal baseQty, String baseUomCd,
			BigDecimal contractQty, String contractUomCd, BigDecimal openQty,
			BigDecimal delivQty, String delivUomCd, BigDecimal packagingQty,
			String packagingUomCd, String settlementCurrCd,
			String settlementUomCd, BigDecimal uomConversionRate,
			BigDecimal price, String priceUomCd, String priceCurrCd,
			BigDecimal priceScr, short priceStatusInd, BigDecimal apiGravity,
			BigDecimal specificGravity, short airVacInd, Short internalInd,
			Date laycanStartDt, Date laycanEndDt, Integer mtmFwdCurveNum,
			Short formulaPriceEventInd, Short payDtEvent1Ind,
			Short payDtEvent2Ind, Date deemedBlDt, Date deemedNorDt,
			Date deemedCommLDt, Date deemedCompLDt, Date deemedCommDDt,
			Date deemedCompDDt, Date deemedRoiDt,
			Date deemedDeliveryMonthEndDt, Date riskStartDt,
			Short timePeriodTypeInd, int motNum, Integer originLocNum,
			short tradeStatusInd, String deliverySchedCd,
			BigDecimal minTolerance, BigDecimal maxTolerance,
			String termSectionCd, String purchaseCategoryCd,
			BigDecimal openBalAdjQty, Integer rfVersionNum,
			BigDecimal priceLumpScr, BigDecimal baseuomConvFactor,
			BigDecimal bblMtFactor, BigDecimal mtmPremium,
			int obligationOpenbalNum, Date paymentDueDt,
			BigDecimal toleranceBelowPct, BigDecimal toleranceAbovePct,
			String pipelineCycleCd, Date lastModifyDt, int modifyPersonNum,
			int lockNum, Short obligationTypeInd, BigDecimal stdPrice,
			String stdPriceCurrCd, String stdPriceUomCd,
			int planningLocationNum, String tradeTypeCd,
			String instrumentTypeCd, Short obligationScheduledInd,
			String ventureCd, short customsDutyStatusInd,
			short schConfExecutedInd, Short statusInd, String externalRef,
			String tradePriceCurrCd, String specCd, String settlePaymentTermCd,
			short pricingStatusInd, short futuresPricingStatusInd,
			short basisPricingStatusInd, int shippingCompanyNum,
			Integer originationLocNum, int destinationLocNum,
			short interCompInd, int interCompTrdNum, int interCompOpenbalNum,
			Date reportingPeriodDt, BigDecimal min1ToleranceQty,
			BigDecimal max1ToleranceQty, BigDecimal toleranceBaseQty,
			BigDecimal toleranceDelivQty, BigDecimal overUnderShipmentQty,
			short bulkToleranceScheduleInd, BigDecimal uptoTmin1Qty,
			BigDecimal uptoTmax1Qty) {
		this.obligationNum = obligationNum;
		this.mtmPremiumUomCd = mtmPremiumUomCd;
		this.mtmPremiumCurrCd = mtmPremiumCurrCd;
		this.mtmQuoteDefNum = mtmQuoteDefNum;
		this.mtmPeriodCd = mtmPeriodCd;
		this.jvCounterpartCompanyNum = jvCounterpartCompanyNum;
		this.strategyNum = strategyNum;
		this.termNum = termNum;
		this.tradeNum = tradeNum;
		this.detailNum = detailNum;
		this.internalCoNum = internalCoNum;
		this.companyNum = companyNum;
		this.buySellInd = buySellInd;
		this.cmdtyCd = cmdtyCd;
		this.locationNum = locationNum;
		this.motTypeInd = motTypeInd;
		this.traderPersonNum = traderPersonNum;
		this.deliveryTermCd = deliveryTermCd;
		this.baseQty = baseQty;
		this.baseUomCd = baseUomCd;
		this.contractQty = contractQty;
		this.contractUomCd = contractUomCd;
		this.openQty = openQty;
		this.delivQty = delivQty;
		this.delivUomCd = delivUomCd;
		this.packagingQty = packagingQty;
		this.packagingUomCd = packagingUomCd;
		this.settlementCurrCd = settlementCurrCd;
		this.settlementUomCd = settlementUomCd;
		this.uomConversionRate = uomConversionRate;
		this.price = price;
		this.priceUomCd = priceUomCd;
		this.priceCurrCd = priceCurrCd;
		this.priceScr = priceScr;
		this.priceStatusInd = priceStatusInd;
		this.apiGravity = apiGravity;
		this.specificGravity = specificGravity;
		this.airVacInd = airVacInd;
		this.internalInd = internalInd;
		this.laycanStartDt = laycanStartDt;
		this.laycanEndDt = laycanEndDt;
		this.mtmFwdCurveNum = mtmFwdCurveNum;
		this.formulaPriceEventInd = formulaPriceEventInd;
		this.payDtEvent1Ind = payDtEvent1Ind;
		this.payDtEvent2Ind = payDtEvent2Ind;
		this.deemedBlDt = deemedBlDt;
		this.deemedNorDt = deemedNorDt;
		this.deemedCommLDt = deemedCommLDt;
		this.deemedCompLDt = deemedCompLDt;
		this.deemedCommDDt = deemedCommDDt;
		this.deemedCompDDt = deemedCompDDt;
		this.deemedRoiDt = deemedRoiDt;
		this.deemedDeliveryMonthEndDt = deemedDeliveryMonthEndDt;
		this.riskStartDt = riskStartDt;
		this.timePeriodTypeInd = timePeriodTypeInd;
		this.motNum = motNum;
		this.originLocNum = originLocNum;
		this.tradeStatusInd = tradeStatusInd;
		this.deliverySchedCd = deliverySchedCd;
		this.minTolerance = minTolerance;
		this.maxTolerance = maxTolerance;
		this.termSectionCd = termSectionCd;
		this.purchaseCategoryCd = purchaseCategoryCd;
		this.openBalAdjQty = openBalAdjQty;
		this.rfVersionNum = rfVersionNum;
		this.priceLumpScr = priceLumpScr;
		this.baseuomConvFactor = baseuomConvFactor;
		this.bblMtFactor = bblMtFactor;
		this.mtmPremium = mtmPremium;
		this.obligationOpenbalNum = obligationOpenbalNum;
		this.paymentDueDt = paymentDueDt;
		this.toleranceBelowPct = toleranceBelowPct;
		this.toleranceAbovePct = toleranceAbovePct;
		this.pipelineCycleCd = pipelineCycleCd;
		this.lastModifyDt = lastModifyDt;
		this.modifyPersonNum = modifyPersonNum;
		this.lockNum = lockNum;
		this.obligationTypeInd = obligationTypeInd;
		this.stdPrice = stdPrice;
		this.stdPriceCurrCd = stdPriceCurrCd;
		this.stdPriceUomCd = stdPriceUomCd;
		this.planningLocationNum = planningLocationNum;
		this.tradeTypeCd = tradeTypeCd;
		this.instrumentTypeCd = instrumentTypeCd;
		this.obligationScheduledInd = obligationScheduledInd;
		this.ventureCd = ventureCd;
		this.customsDutyStatusInd = customsDutyStatusInd;
		this.schConfExecutedInd = schConfExecutedInd;
		this.statusInd = statusInd;
		this.externalRef = externalRef;
		this.tradePriceCurrCd = tradePriceCurrCd;
		this.specCd = specCd;
		this.settlePaymentTermCd = settlePaymentTermCd;
		this.pricingStatusInd = pricingStatusInd;
		this.futuresPricingStatusInd = futuresPricingStatusInd;
		this.basisPricingStatusInd = basisPricingStatusInd;
		this.shippingCompanyNum = shippingCompanyNum;
		this.originationLocNum = originationLocNum;
		this.destinationLocNum = destinationLocNum;
		this.interCompInd = interCompInd;
		this.interCompTrdNum = interCompTrdNum;
		this.interCompOpenbalNum = interCompOpenbalNum;
		this.reportingPeriodDt = reportingPeriodDt;
		this.min1ToleranceQty = min1ToleranceQty;
		this.max1ToleranceQty = max1ToleranceQty;
		this.toleranceBaseQty = toleranceBaseQty;
		this.toleranceDelivQty = toleranceDelivQty;
		this.overUnderShipmentQty = overUnderShipmentQty;
		this.bulkToleranceScheduleInd = bulkToleranceScheduleInd;
		this.uptoTmin1Qty = uptoTmin1Qty;
		this.uptoTmax1Qty = uptoTmax1Qty;
	}

	public int getObligationNum() {
		return this.obligationNum;
	}

	public void setObligationNum(int obligationNum) {
		this.obligationNum = obligationNum;
	}

	public String getMtmPremiumUomCd() {
		return this.mtmPremiumUomCd;
	}

	public void setMtmPremiumUomCd(String mtmPremiumUomCd) {
		this.mtmPremiumUomCd = mtmPremiumUomCd;
	}

	public String getMtmPremiumCurrCd() {
		return this.mtmPremiumCurrCd;
	}

	public void setMtmPremiumCurrCd(String mtmPremiumCurrCd) {
		this.mtmPremiumCurrCd = mtmPremiumCurrCd;
	}

	public int getMtmQuoteDefNum() {
		return this.mtmQuoteDefNum;
	}

	public void setMtmQuoteDefNum(int mtmQuoteDefNum) {
		this.mtmQuoteDefNum = mtmQuoteDefNum;
	}

	public String getMtmPeriodCd() {
		return this.mtmPeriodCd;
	}

	public void setMtmPeriodCd(String mtmPeriodCd) {
		this.mtmPeriodCd = mtmPeriodCd;
	}

	public int getJvCounterpartCompanyNum() {
		return this.jvCounterpartCompanyNum;
	}

	public void setJvCounterpartCompanyNum(int jvCounterpartCompanyNum) {
		this.jvCounterpartCompanyNum = jvCounterpartCompanyNum;
	}

	public Integer getStrategyNum() {
		return this.strategyNum;
	}

	public void setStrategyNum(Integer strategyNum) {
		this.strategyNum = strategyNum;
	}

	public int getTermNum() {
		return this.termNum;
	}

	public void setTermNum(int termNum) {
		this.termNum = termNum;
	}

	public Integer getTradeNum() {
		return this.tradeNum;
	}

	public void setTradeNum(Integer tradeNum) {
		this.tradeNum = tradeNum;
	}

	public int getDetailNum() {
		return this.detailNum;
	}

	public void setDetailNum(int detailNum) {
		this.detailNum = detailNum;
	}

	public Integer getInternalCoNum() {
		return this.internalCoNum;
	}

	public void setInternalCoNum(Integer internalCoNum) {
		this.internalCoNum = internalCoNum;
	}

	public Integer getCompanyNum() {
		return this.companyNum;
	}

	public void setCompanyNum(Integer companyNum) {
		this.companyNum = companyNum;
	}

	public Short getBuySellInd() {
		return this.buySellInd;
	}

	public void setBuySellInd(Short buySellInd) {
		this.buySellInd = buySellInd;
	}

	public String getCmdtyCd() {
		return this.cmdtyCd;
	}

	public void setCmdtyCd(String cmdtyCd) {
		this.cmdtyCd = cmdtyCd;
	}

	public Integer getLocationNum() {
		return this.locationNum;
	}

	public void setLocationNum(Integer locationNum) {
		this.locationNum = locationNum;
	}

	public Short getMotTypeInd() {
		return this.motTypeInd;
	}

	public void setMotTypeInd(Short motTypeInd) {
		this.motTypeInd = motTypeInd;
	}

	public Integer getTraderPersonNum() {
		return this.traderPersonNum;
	}

	public void setTraderPersonNum(Integer traderPersonNum) {
		this.traderPersonNum = traderPersonNum;
	}

	public String getDeliveryTermCd() {
		return this.deliveryTermCd;
	}

	public void setDeliveryTermCd(String deliveryTermCd) {
		this.deliveryTermCd = deliveryTermCd;
	}

	public BigDecimal getBaseQty() {
		return this.baseQty;
	}

	public void setBaseQty(BigDecimal baseQty) {
		this.baseQty = baseQty;
	}

	public String getBaseUomCd() {
		return this.baseUomCd;
	}

	public void setBaseUomCd(String baseUomCd) {
		this.baseUomCd = baseUomCd;
	}

	public BigDecimal getContractQty() {
		return this.contractQty;
	}

	public void setContractQty(BigDecimal contractQty) {
		this.contractQty = contractQty;
	}

	public String getContractUomCd() {
		return this.contractUomCd;
	}

	public void setContractUomCd(String contractUomCd) {
		this.contractUomCd = contractUomCd;
	}

	public BigDecimal getOpenQty() {
		return this.openQty;
	}

	public void setOpenQty(BigDecimal openQty) {
		this.openQty = openQty;
	}

	public BigDecimal getDelivQty() {
		return this.delivQty;
	}

	public void setDelivQty(BigDecimal delivQty) {
		this.delivQty = delivQty;
	}

	public String getDelivUomCd() {
		return this.delivUomCd;
	}

	public void setDelivUomCd(String delivUomCd) {
		this.delivUomCd = delivUomCd;
	}

	public BigDecimal getPackagingQty() {
		return this.packagingQty;
	}

	public void setPackagingQty(BigDecimal packagingQty) {
		this.packagingQty = packagingQty;
	}

	public String getPackagingUomCd() {
		return this.packagingUomCd;
	}

	public void setPackagingUomCd(String packagingUomCd) {
		this.packagingUomCd = packagingUomCd;
	}

	public String getSettlementCurrCd() {
		return this.settlementCurrCd;
	}

	public void setSettlementCurrCd(String settlementCurrCd) {
		this.settlementCurrCd = settlementCurrCd;
	}

	public String getSettlementUomCd() {
		return this.settlementUomCd;
	}

	public void setSettlementUomCd(String settlementUomCd) {
		this.settlementUomCd = settlementUomCd;
	}

	public BigDecimal getUomConversionRate() {
		return this.uomConversionRate;
	}

	public void setUomConversionRate(BigDecimal uomConversionRate) {
		this.uomConversionRate = uomConversionRate;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public String getPriceUomCd() {
		return this.priceUomCd;
	}

	public void setPriceUomCd(String priceUomCd) {
		this.priceUomCd = priceUomCd;
	}

	public String getPriceCurrCd() {
		return this.priceCurrCd;
	}

	public void setPriceCurrCd(String priceCurrCd) {
		this.priceCurrCd = priceCurrCd;
	}

	public BigDecimal getPriceScr() {
		return this.priceScr;
	}

	public void setPriceScr(BigDecimal priceScr) {
		this.priceScr = priceScr;
	}

	public short getPriceStatusInd() {
		return this.priceStatusInd;
	}

	public void setPriceStatusInd(short priceStatusInd) {
		this.priceStatusInd = priceStatusInd;
	}

	public BigDecimal getApiGravity() {
		return this.apiGravity;
	}

	public void setApiGravity(BigDecimal apiGravity) {
		this.apiGravity = apiGravity;
	}

	public BigDecimal getSpecificGravity() {
		return this.specificGravity;
	}

	public void setSpecificGravity(BigDecimal specificGravity) {
		this.specificGravity = specificGravity;
	}

	public short getAirVacInd() {
		return this.airVacInd;
	}

	public void setAirVacInd(short airVacInd) {
		this.airVacInd = airVacInd;
	}

	public Short getInternalInd() {
		return this.internalInd;
	}

	public void setInternalInd(Short internalInd) {
		this.internalInd = internalInd;
	}

	public Date getLaycanStartDt() {
		return this.laycanStartDt;
	}

	public void setLaycanStartDt(Date laycanStartDt) {
		this.laycanStartDt = laycanStartDt;
	}

	public Date getLaycanEndDt() {
		return this.laycanEndDt;
	}

	public void setLaycanEndDt(Date laycanEndDt) {
		this.laycanEndDt = laycanEndDt;
	}

	public Integer getMtmFwdCurveNum() {
		return this.mtmFwdCurveNum;
	}

	public void setMtmFwdCurveNum(Integer mtmFwdCurveNum) {
		this.mtmFwdCurveNum = mtmFwdCurveNum;
	}

	public Short getFormulaPriceEventInd() {
		return this.formulaPriceEventInd;
	}

	public void setFormulaPriceEventInd(Short formulaPriceEventInd) {
		this.formulaPriceEventInd = formulaPriceEventInd;
	}

	public Short getPayDtEvent1Ind() {
		return this.payDtEvent1Ind;
	}

	public void setPayDtEvent1Ind(Short payDtEvent1Ind) {
		this.payDtEvent1Ind = payDtEvent1Ind;
	}

	public Short getPayDtEvent2Ind() {
		return this.payDtEvent2Ind;
	}

	public void setPayDtEvent2Ind(Short payDtEvent2Ind) {
		this.payDtEvent2Ind = payDtEvent2Ind;
	}

	public Date getDeemedBlDt() {
		return this.deemedBlDt;
	}

	public void setDeemedBlDt(Date deemedBlDt) {
		this.deemedBlDt = deemedBlDt;
	}

	public Date getDeemedNorDt() {
		return this.deemedNorDt;
	}

	public void setDeemedNorDt(Date deemedNorDt) {
		this.deemedNorDt = deemedNorDt;
	}

	public Date getDeemedCommLDt() {
		return this.deemedCommLDt;
	}

	public void setDeemedCommLDt(Date deemedCommLDt) {
		this.deemedCommLDt = deemedCommLDt;
	}

	public Date getDeemedCompLDt() {
		return this.deemedCompLDt;
	}

	public void setDeemedCompLDt(Date deemedCompLDt) {
		this.deemedCompLDt = deemedCompLDt;
	}

	public Date getDeemedCommDDt() {
		return this.deemedCommDDt;
	}

	public void setDeemedCommDDt(Date deemedCommDDt) {
		this.deemedCommDDt = deemedCommDDt;
	}

	public Date getDeemedCompDDt() {
		return this.deemedCompDDt;
	}

	public void setDeemedCompDDt(Date deemedCompDDt) {
		this.deemedCompDDt = deemedCompDDt;
	}

	public Date getDeemedRoiDt() {
		return this.deemedRoiDt;
	}

	public void setDeemedRoiDt(Date deemedRoiDt) {
		this.deemedRoiDt = deemedRoiDt;
	}

	public Date getDeemedDeliveryMonthEndDt() {
		return this.deemedDeliveryMonthEndDt;
	}

	public void setDeemedDeliveryMonthEndDt(Date deemedDeliveryMonthEndDt) {
		this.deemedDeliveryMonthEndDt = deemedDeliveryMonthEndDt;
	}

	public Date getRiskStartDt() {
		return this.riskStartDt;
	}

	public void setRiskStartDt(Date riskStartDt) {
		this.riskStartDt = riskStartDt;
	}

	public Short getTimePeriodTypeInd() {
		return this.timePeriodTypeInd;
	}

	public void setTimePeriodTypeInd(Short timePeriodTypeInd) {
		this.timePeriodTypeInd = timePeriodTypeInd;
	}

	public int getMotNum() {
		return this.motNum;
	}

	public void setMotNum(int motNum) {
		this.motNum = motNum;
	}

	public Integer getOriginLocNum() {
		return this.originLocNum;
	}

	public void setOriginLocNum(Integer originLocNum) {
		this.originLocNum = originLocNum;
	}

	public short getTradeStatusInd() {
		return this.tradeStatusInd;
	}

	public void setTradeStatusInd(short tradeStatusInd) {
		this.tradeStatusInd = tradeStatusInd;
	}

	public String getDeliverySchedCd() {
		return this.deliverySchedCd;
	}

	public void setDeliverySchedCd(String deliverySchedCd) {
		this.deliverySchedCd = deliverySchedCd;
	}

	public BigDecimal getMinTolerance() {
		return this.minTolerance;
	}

	public void setMinTolerance(BigDecimal minTolerance) {
		this.minTolerance = minTolerance;
	}

	public BigDecimal getMaxTolerance() {
		return this.maxTolerance;
	}

	public void setMaxTolerance(BigDecimal maxTolerance) {
		this.maxTolerance = maxTolerance;
	}

	public String getTermSectionCd() {
		return this.termSectionCd;
	}

	public void setTermSectionCd(String termSectionCd) {
		this.termSectionCd = termSectionCd;
	}

	public String getPurchaseCategoryCd() {
		return this.purchaseCategoryCd;
	}

	public void setPurchaseCategoryCd(String purchaseCategoryCd) {
		this.purchaseCategoryCd = purchaseCategoryCd;
	}

	public BigDecimal getOpenBalAdjQty() {
		return this.openBalAdjQty;
	}

	public void setOpenBalAdjQty(BigDecimal openBalAdjQty) {
		this.openBalAdjQty = openBalAdjQty;
	}

	public Integer getRfVersionNum() {
		return this.rfVersionNum;
	}

	public void setRfVersionNum(Integer rfVersionNum) {
		this.rfVersionNum = rfVersionNum;
	}

	public BigDecimal getPriceLumpScr() {
		return this.priceLumpScr;
	}

	public void setPriceLumpScr(BigDecimal priceLumpScr) {
		this.priceLumpScr = priceLumpScr;
	}

	public BigDecimal getBaseuomConvFactor() {
		return this.baseuomConvFactor;
	}

	public void setBaseuomConvFactor(BigDecimal baseuomConvFactor) {
		this.baseuomConvFactor = baseuomConvFactor;
	}

	public BigDecimal getBblMtFactor() {
		return this.bblMtFactor;
	}

	public void setBblMtFactor(BigDecimal bblMtFactor) {
		this.bblMtFactor = bblMtFactor;
	}

	public BigDecimal getMtmPremium() {
		return this.mtmPremium;
	}

	public void setMtmPremium(BigDecimal mtmPremium) {
		this.mtmPremium = mtmPremium;
	}

	public int getObligationOpenbalNum() {
		return this.obligationOpenbalNum;
	}

	public void setObligationOpenbalNum(int obligationOpenbalNum) {
		this.obligationOpenbalNum = obligationOpenbalNum;
	}

	public Date getPaymentDueDt() {
		return this.paymentDueDt;
	}

	public void setPaymentDueDt(Date paymentDueDt) {
		this.paymentDueDt = paymentDueDt;
	}

	public BigDecimal getToleranceBelowPct() {
		return this.toleranceBelowPct;
	}

	public void setToleranceBelowPct(BigDecimal toleranceBelowPct) {
		this.toleranceBelowPct = toleranceBelowPct;
	}

	public BigDecimal getToleranceAbovePct() {
		return this.toleranceAbovePct;
	}

	public void setToleranceAbovePct(BigDecimal toleranceAbovePct) {
		this.toleranceAbovePct = toleranceAbovePct;
	}

	public String getPipelineCycleCd() {
		return this.pipelineCycleCd;
	}

	public void setPipelineCycleCd(String pipelineCycleCd) {
		this.pipelineCycleCd = pipelineCycleCd;
	}

	public Date getLastModifyDt() {
		return this.lastModifyDt;
	}

	public void setLastModifyDt(Date lastModifyDt) {
		this.lastModifyDt = lastModifyDt;
	}

	public int getModifyPersonNum() {
		return this.modifyPersonNum;
	}

	public void setModifyPersonNum(int modifyPersonNum) {
		this.modifyPersonNum = modifyPersonNum;
	}

	public int getLockNum() {
		return this.lockNum;
	}

	public void setLockNum(int lockNum) {
		this.lockNum = lockNum;
	}

	public Short getObligationTypeInd() {
		return this.obligationTypeInd;
	}

	public void setObligationTypeInd(Short obligationTypeInd) {
		this.obligationTypeInd = obligationTypeInd;
	}

	public BigDecimal getStdPrice() {
		return this.stdPrice;
	}

	public void setStdPrice(BigDecimal stdPrice) {
		this.stdPrice = stdPrice;
	}

	public String getStdPriceCurrCd() {
		return this.stdPriceCurrCd;
	}

	public void setStdPriceCurrCd(String stdPriceCurrCd) {
		this.stdPriceCurrCd = stdPriceCurrCd;
	}

	public String getStdPriceUomCd() {
		return this.stdPriceUomCd;
	}

	public void setStdPriceUomCd(String stdPriceUomCd) {
		this.stdPriceUomCd = stdPriceUomCd;
	}

	public int getPlanningLocationNum() {
		return this.planningLocationNum;
	}

	public void setPlanningLocationNum(int planningLocationNum) {
		this.planningLocationNum = planningLocationNum;
	}

	public String getTradeTypeCd() {
		return this.tradeTypeCd;
	}

	public void setTradeTypeCd(String tradeTypeCd) {
		this.tradeTypeCd = tradeTypeCd;
	}

	public String getInstrumentTypeCd() {
		return this.instrumentTypeCd;
	}

	public void setInstrumentTypeCd(String instrumentTypeCd) {
		this.instrumentTypeCd = instrumentTypeCd;
	}

	public Short getObligationScheduledInd() {
		return this.obligationScheduledInd;
	}

	public void setObligationScheduledInd(Short obligationScheduledInd) {
		this.obligationScheduledInd = obligationScheduledInd;
	}

	public String getVentureCd() {
		return this.ventureCd;
	}

	public void setVentureCd(String ventureCd) {
		this.ventureCd = ventureCd;
	}

	public short getCustomsDutyStatusInd() {
		return this.customsDutyStatusInd;
	}

	public void setCustomsDutyStatusInd(short customsDutyStatusInd) {
		this.customsDutyStatusInd = customsDutyStatusInd;
	}

	public short getSchConfExecutedInd() {
		return this.schConfExecutedInd;
	}

	public void setSchConfExecutedInd(short schConfExecutedInd) {
		this.schConfExecutedInd = schConfExecutedInd;
	}

	public Short getStatusInd() {
		return this.statusInd;
	}

	public void setStatusInd(Short statusInd) {
		this.statusInd = statusInd;
	}

	public String getExternalRef() {
		return this.externalRef;
	}

	public void setExternalRef(String externalRef) {
		this.externalRef = externalRef;
	}

	public String getTradePriceCurrCd() {
		return this.tradePriceCurrCd;
	}

	public void setTradePriceCurrCd(String tradePriceCurrCd) {
		this.tradePriceCurrCd = tradePriceCurrCd;
	}

	public String getSpecCd() {
		return this.specCd;
	}

	public void setSpecCd(String specCd) {
		this.specCd = specCd;
	}

	public String getSettlePaymentTermCd() {
		return this.settlePaymentTermCd;
	}

	public void setSettlePaymentTermCd(String settlePaymentTermCd) {
		this.settlePaymentTermCd = settlePaymentTermCd;
	}

	public short getPricingStatusInd() {
		return this.pricingStatusInd;
	}

	public void setPricingStatusInd(short pricingStatusInd) {
		this.pricingStatusInd = pricingStatusInd;
	}

	public short getFuturesPricingStatusInd() {
		return this.futuresPricingStatusInd;
	}

	public void setFuturesPricingStatusInd(short futuresPricingStatusInd) {
		this.futuresPricingStatusInd = futuresPricingStatusInd;
	}

	public short getBasisPricingStatusInd() {
		return this.basisPricingStatusInd;
	}

	public void setBasisPricingStatusInd(short basisPricingStatusInd) {
		this.basisPricingStatusInd = basisPricingStatusInd;
	}

	public int getShippingCompanyNum() {
		return this.shippingCompanyNum;
	}

	public void setShippingCompanyNum(int shippingCompanyNum) {
		this.shippingCompanyNum = shippingCompanyNum;
	}

	public Integer getOriginationLocNum() {
		return this.originationLocNum;
	}

	public void setOriginationLocNum(Integer originationLocNum) {
		this.originationLocNum = originationLocNum;
	}

	public int getDestinationLocNum() {
		return this.destinationLocNum;
	}

	public void setDestinationLocNum(int destinationLocNum) {
		this.destinationLocNum = destinationLocNum;
	}

	public short getInterCompInd() {
		return this.interCompInd;
	}

	public void setInterCompInd(short interCompInd) {
		this.interCompInd = interCompInd;
	}

	public int getInterCompTrdNum() {
		return this.interCompTrdNum;
	}

	public void setInterCompTrdNum(int interCompTrdNum) {
		this.interCompTrdNum = interCompTrdNum;
	}

	public int getInterCompOpenbalNum() {
		return this.interCompOpenbalNum;
	}

	public void setInterCompOpenbalNum(int interCompOpenbalNum) {
		this.interCompOpenbalNum = interCompOpenbalNum;
	}

	public Date getReportingPeriodDt() {
		return this.reportingPeriodDt;
	}

	public void setReportingPeriodDt(Date reportingPeriodDt) {
		this.reportingPeriodDt = reportingPeriodDt;
	}

	public BigDecimal getMin1ToleranceQty() {
		return this.min1ToleranceQty;
	}

	public void setMin1ToleranceQty(BigDecimal min1ToleranceQty) {
		this.min1ToleranceQty = min1ToleranceQty;
	}

	public BigDecimal getMax1ToleranceQty() {
		return this.max1ToleranceQty;
	}

	public void setMax1ToleranceQty(BigDecimal max1ToleranceQty) {
		this.max1ToleranceQty = max1ToleranceQty;
	}

	public BigDecimal getToleranceBaseQty() {
		return this.toleranceBaseQty;
	}

	public void setToleranceBaseQty(BigDecimal toleranceBaseQty) {
		this.toleranceBaseQty = toleranceBaseQty;
	}

	public BigDecimal getToleranceDelivQty() {
		return this.toleranceDelivQty;
	}

	public void setToleranceDelivQty(BigDecimal toleranceDelivQty) {
		this.toleranceDelivQty = toleranceDelivQty;
	}

	public BigDecimal getOverUnderShipmentQty() {
		return this.overUnderShipmentQty;
	}

	public void setOverUnderShipmentQty(BigDecimal overUnderShipmentQty) {
		this.overUnderShipmentQty = overUnderShipmentQty;
	}

	public short getBulkToleranceScheduleInd() {
		return this.bulkToleranceScheduleInd;
	}

	public void setBulkToleranceScheduleInd(short bulkToleranceScheduleInd) {
		this.bulkToleranceScheduleInd = bulkToleranceScheduleInd;
	}

	public BigDecimal getUptoTmin1Qty() {
		return this.uptoTmin1Qty;
	}

	public void setUptoTmin1Qty(BigDecimal uptoTmin1Qty) {
		this.uptoTmin1Qty = uptoTmin1Qty;
	}

	public BigDecimal getUptoTmax1Qty() {
		return this.uptoTmax1Qty;
	}

	public void setUptoTmax1Qty(BigDecimal uptoTmax1Qty) {
		this.uptoTmax1Qty = uptoTmax1Qty;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VopsObligationHdrId))
			return false;
		VopsObligationHdrId castOther = (VopsObligationHdrId) other;

		return (this.getObligationNum() == castOther.getObligationNum())
				&& ((this.getMtmPremiumUomCd() == castOther
						.getMtmPremiumUomCd()) || (this.getMtmPremiumUomCd() != null
						&& castOther.getMtmPremiumUomCd() != null && this
						.getMtmPremiumUomCd().equals(
								castOther.getMtmPremiumUomCd())))
				&& ((this.getMtmPremiumCurrCd() == castOther
						.getMtmPremiumCurrCd()) || (this.getMtmPremiumCurrCd() != null
						&& castOther.getMtmPremiumCurrCd() != null && this
						.getMtmPremiumCurrCd().equals(
								castOther.getMtmPremiumCurrCd())))
				&& (this.getMtmQuoteDefNum() == castOther.getMtmQuoteDefNum())
				&& ((this.getMtmPeriodCd() == castOther.getMtmPeriodCd()) || (this
						.getMtmPeriodCd() != null
						&& castOther.getMtmPeriodCd() != null && this
						.getMtmPeriodCd().equals(castOther.getMtmPeriodCd())))
				&& (this.getJvCounterpartCompanyNum() == castOther
						.getJvCounterpartCompanyNum())
				&& ((this.getStrategyNum() == castOther.getStrategyNum()) || (this
						.getStrategyNum() != null
						&& castOther.getStrategyNum() != null && this
						.getStrategyNum().equals(castOther.getStrategyNum())))
				&& (this.getTermNum() == castOther.getTermNum())
				&& ((this.getTradeNum() == castOther.getTradeNum()) || (this
						.getTradeNum() != null
						&& castOther.getTradeNum() != null && this
						.getTradeNum().equals(castOther.getTradeNum())))
				&& (this.getDetailNum() == castOther.getDetailNum())
				&& ((this.getInternalCoNum() == castOther.getInternalCoNum()) || (this
						.getInternalCoNum() != null
						&& castOther.getInternalCoNum() != null && this
						.getInternalCoNum()
						.equals(castOther.getInternalCoNum())))
				&& ((this.getCompanyNum() == castOther.getCompanyNum()) || (this
						.getCompanyNum() != null
						&& castOther.getCompanyNum() != null && this
						.getCompanyNum().equals(castOther.getCompanyNum())))
				&& ((this.getBuySellInd() == castOther.getBuySellInd()) || (this
						.getBuySellInd() != null
						&& castOther.getBuySellInd() != null && this
						.getBuySellInd().equals(castOther.getBuySellInd())))
				&& ((this.getCmdtyCd() == castOther.getCmdtyCd()) || (this
						.getCmdtyCd() != null && castOther.getCmdtyCd() != null && this
						.getCmdtyCd().equals(castOther.getCmdtyCd())))
				&& ((this.getLocationNum() == castOther.getLocationNum()) || (this
						.getLocationNum() != null
						&& castOther.getLocationNum() != null && this
						.getLocationNum().equals(castOther.getLocationNum())))
				&& ((this.getMotTypeInd() == castOther.getMotTypeInd()) || (this
						.getMotTypeInd() != null
						&& castOther.getMotTypeInd() != null && this
						.getMotTypeInd().equals(castOther.getMotTypeInd())))
				&& ((this.getTraderPersonNum() == castOther
						.getTraderPersonNum()) || (this.getTraderPersonNum() != null
						&& castOther.getTraderPersonNum() != null && this
						.getTraderPersonNum().equals(
								castOther.getTraderPersonNum())))
				&& ((this.getDeliveryTermCd() == castOther.getDeliveryTermCd()) || (this
						.getDeliveryTermCd() != null
						&& castOther.getDeliveryTermCd() != null && this
						.getDeliveryTermCd().equals(
								castOther.getDeliveryTermCd())))
				&& ((this.getBaseQty() == castOther.getBaseQty()) || (this
						.getBaseQty() != null && castOther.getBaseQty() != null && this
						.getBaseQty().equals(castOther.getBaseQty())))
				&& ((this.getBaseUomCd() == castOther.getBaseUomCd()) || (this
						.getBaseUomCd() != null
						&& castOther.getBaseUomCd() != null && this
						.getBaseUomCd().equals(castOther.getBaseUomCd())))
				&& ((this.getContractQty() == castOther.getContractQty()) || (this
						.getContractQty() != null
						&& castOther.getContractQty() != null && this
						.getContractQty().equals(castOther.getContractQty())))
				&& ((this.getContractUomCd() == castOther.getContractUomCd()) || (this
						.getContractUomCd() != null
						&& castOther.getContractUomCd() != null && this
						.getContractUomCd()
						.equals(castOther.getContractUomCd())))
				&& ((this.getOpenQty() == castOther.getOpenQty()) || (this
						.getOpenQty() != null && castOther.getOpenQty() != null && this
						.getOpenQty().equals(castOther.getOpenQty())))
				&& ((this.getDelivQty() == castOther.getDelivQty()) || (this
						.getDelivQty() != null
						&& castOther.getDelivQty() != null && this
						.getDelivQty().equals(castOther.getDelivQty())))
				&& ((this.getDelivUomCd() == castOther.getDelivUomCd()) || (this
						.getDelivUomCd() != null
						&& castOther.getDelivUomCd() != null && this
						.getDelivUomCd().equals(castOther.getDelivUomCd())))
				&& ((this.getPackagingQty() == castOther.getPackagingQty()) || (this
						.getPackagingQty() != null
						&& castOther.getPackagingQty() != null && this
						.getPackagingQty().equals(castOther.getPackagingQty())))
				&& ((this.getPackagingUomCd() == castOther.getPackagingUomCd()) || (this
						.getPackagingUomCd() != null
						&& castOther.getPackagingUomCd() != null && this
						.getPackagingUomCd().equals(
								castOther.getPackagingUomCd())))
				&& ((this.getSettlementCurrCd() == castOther
						.getSettlementCurrCd()) || (this.getSettlementCurrCd() != null
						&& castOther.getSettlementCurrCd() != null && this
						.getSettlementCurrCd().equals(
								castOther.getSettlementCurrCd())))
				&& ((this.getSettlementUomCd() == castOther
						.getSettlementUomCd()) || (this.getSettlementUomCd() != null
						&& castOther.getSettlementUomCd() != null && this
						.getSettlementUomCd().equals(
								castOther.getSettlementUomCd())))
				&& ((this.getUomConversionRate() == castOther
						.getUomConversionRate()) || (this
						.getUomConversionRate() != null
						&& castOther.getUomConversionRate() != null && this
						.getUomConversionRate().equals(
								castOther.getUomConversionRate())))
				&& ((this.getPrice() == castOther.getPrice()) || (this
						.getPrice() != null && castOther.getPrice() != null && this
						.getPrice().equals(castOther.getPrice())))
				&& ((this.getPriceUomCd() == castOther.getPriceUomCd()) || (this
						.getPriceUomCd() != null
						&& castOther.getPriceUomCd() != null && this
						.getPriceUomCd().equals(castOther.getPriceUomCd())))
				&& ((this.getPriceCurrCd() == castOther.getPriceCurrCd()) || (this
						.getPriceCurrCd() != null
						&& castOther.getPriceCurrCd() != null && this
						.getPriceCurrCd().equals(castOther.getPriceCurrCd())))
				&& ((this.getPriceScr() == castOther.getPriceScr()) || (this
						.getPriceScr() != null
						&& castOther.getPriceScr() != null && this
						.getPriceScr().equals(castOther.getPriceScr())))
				&& (this.getPriceStatusInd() == castOther.getPriceStatusInd())
				&& ((this.getApiGravity() == castOther.getApiGravity()) || (this
						.getApiGravity() != null
						&& castOther.getApiGravity() != null && this
						.getApiGravity().equals(castOther.getApiGravity())))
				&& ((this.getSpecificGravity() == castOther
						.getSpecificGravity()) || (this.getSpecificGravity() != null
						&& castOther.getSpecificGravity() != null && this
						.getSpecificGravity().equals(
								castOther.getSpecificGravity())))
				&& (this.getAirVacInd() == castOther.getAirVacInd())
				&& ((this.getInternalInd() == castOther.getInternalInd()) || (this
						.getInternalInd() != null
						&& castOther.getInternalInd() != null && this
						.getInternalInd().equals(castOther.getInternalInd())))
				&& ((this.getLaycanStartDt() == castOther.getLaycanStartDt()) || (this
						.getLaycanStartDt() != null
						&& castOther.getLaycanStartDt() != null && this
						.getLaycanStartDt()
						.equals(castOther.getLaycanStartDt())))
				&& ((this.getLaycanEndDt() == castOther.getLaycanEndDt()) || (this
						.getLaycanEndDt() != null
						&& castOther.getLaycanEndDt() != null && this
						.getLaycanEndDt().equals(castOther.getLaycanEndDt())))
				&& ((this.getMtmFwdCurveNum() == castOther.getMtmFwdCurveNum()) || (this
						.getMtmFwdCurveNum() != null
						&& castOther.getMtmFwdCurveNum() != null && this
						.getMtmFwdCurveNum().equals(
								castOther.getMtmFwdCurveNum())))
				&& ((this.getFormulaPriceEventInd() == castOther
						.getFormulaPriceEventInd()) || (this
						.getFormulaPriceEventInd() != null
						&& castOther.getFormulaPriceEventInd() != null && this
						.getFormulaPriceEventInd().equals(
								castOther.getFormulaPriceEventInd())))
				&& ((this.getPayDtEvent1Ind() == castOther.getPayDtEvent1Ind()) || (this
						.getPayDtEvent1Ind() != null
						&& castOther.getPayDtEvent1Ind() != null && this
						.getPayDtEvent1Ind().equals(
								castOther.getPayDtEvent1Ind())))
				&& ((this.getPayDtEvent2Ind() == castOther.getPayDtEvent2Ind()) || (this
						.getPayDtEvent2Ind() != null
						&& castOther.getPayDtEvent2Ind() != null && this
						.getPayDtEvent2Ind().equals(
								castOther.getPayDtEvent2Ind())))
				&& ((this.getDeemedBlDt() == castOther.getDeemedBlDt()) || (this
						.getDeemedBlDt() != null
						&& castOther.getDeemedBlDt() != null && this
						.getDeemedBlDt().equals(castOther.getDeemedBlDt())))
				&& ((this.getDeemedNorDt() == castOther.getDeemedNorDt()) || (this
						.getDeemedNorDt() != null
						&& castOther.getDeemedNorDt() != null && this
						.getDeemedNorDt().equals(castOther.getDeemedNorDt())))
				&& ((this.getDeemedCommLDt() == castOther.getDeemedCommLDt()) || (this
						.getDeemedCommLDt() != null
						&& castOther.getDeemedCommLDt() != null && this
						.getDeemedCommLDt()
						.equals(castOther.getDeemedCommLDt())))
				&& ((this.getDeemedCompLDt() == castOther.getDeemedCompLDt()) || (this
						.getDeemedCompLDt() != null
						&& castOther.getDeemedCompLDt() != null && this
						.getDeemedCompLDt()
						.equals(castOther.getDeemedCompLDt())))
				&& ((this.getDeemedCommDDt() == castOther.getDeemedCommDDt()) || (this
						.getDeemedCommDDt() != null
						&& castOther.getDeemedCommDDt() != null && this
						.getDeemedCommDDt()
						.equals(castOther.getDeemedCommDDt())))
				&& ((this.getDeemedCompDDt() == castOther.getDeemedCompDDt()) || (this
						.getDeemedCompDDt() != null
						&& castOther.getDeemedCompDDt() != null && this
						.getDeemedCompDDt()
						.equals(castOther.getDeemedCompDDt())))
				&& ((this.getDeemedRoiDt() == castOther.getDeemedRoiDt()) || (this
						.getDeemedRoiDt() != null
						&& castOther.getDeemedRoiDt() != null && this
						.getDeemedRoiDt().equals(castOther.getDeemedRoiDt())))
				&& ((this.getDeemedDeliveryMonthEndDt() == castOther
						.getDeemedDeliveryMonthEndDt()) || (this
						.getDeemedDeliveryMonthEndDt() != null
						&& castOther.getDeemedDeliveryMonthEndDt() != null && this
						.getDeemedDeliveryMonthEndDt().equals(
								castOther.getDeemedDeliveryMonthEndDt())))
				&& ((this.getRiskStartDt() == castOther.getRiskStartDt()) || (this
						.getRiskStartDt() != null
						&& castOther.getRiskStartDt() != null && this
						.getRiskStartDt().equals(castOther.getRiskStartDt())))
				&& ((this.getTimePeriodTypeInd() == castOther
						.getTimePeriodTypeInd()) || (this
						.getTimePeriodTypeInd() != null
						&& castOther.getTimePeriodTypeInd() != null && this
						.getTimePeriodTypeInd().equals(
								castOther.getTimePeriodTypeInd())))
				&& (this.getMotNum() == castOther.getMotNum())
				&& ((this.getOriginLocNum() == castOther.getOriginLocNum()) || (this
						.getOriginLocNum() != null
						&& castOther.getOriginLocNum() != null && this
						.getOriginLocNum().equals(castOther.getOriginLocNum())))
				&& (this.getTradeStatusInd() == castOther.getTradeStatusInd())
				&& ((this.getDeliverySchedCd() == castOther
						.getDeliverySchedCd()) || (this.getDeliverySchedCd() != null
						&& castOther.getDeliverySchedCd() != null && this
						.getDeliverySchedCd().equals(
								castOther.getDeliverySchedCd())))
				&& ((this.getMinTolerance() == castOther.getMinTolerance()) || (this
						.getMinTolerance() != null
						&& castOther.getMinTolerance() != null && this
						.getMinTolerance().equals(castOther.getMinTolerance())))
				&& ((this.getMaxTolerance() == castOther.getMaxTolerance()) || (this
						.getMaxTolerance() != null
						&& castOther.getMaxTolerance() != null && this
						.getMaxTolerance().equals(castOther.getMaxTolerance())))
				&& ((this.getTermSectionCd() == castOther.getTermSectionCd()) || (this
						.getTermSectionCd() != null
						&& castOther.getTermSectionCd() != null && this
						.getTermSectionCd()
						.equals(castOther.getTermSectionCd())))
				&& ((this.getPurchaseCategoryCd() == castOther
						.getPurchaseCategoryCd()) || (this
						.getPurchaseCategoryCd() != null
						&& castOther.getPurchaseCategoryCd() != null && this
						.getPurchaseCategoryCd().equals(
								castOther.getPurchaseCategoryCd())))
				&& ((this.getOpenBalAdjQty() == castOther.getOpenBalAdjQty()) || (this
						.getOpenBalAdjQty() != null
						&& castOther.getOpenBalAdjQty() != null && this
						.getOpenBalAdjQty()
						.equals(castOther.getOpenBalAdjQty())))
				&& ((this.getRfVersionNum() == castOther.getRfVersionNum()) || (this
						.getRfVersionNum() != null
						&& castOther.getRfVersionNum() != null && this
						.getRfVersionNum().equals(castOther.getRfVersionNum())))
				&& ((this.getPriceLumpScr() == castOther.getPriceLumpScr()) || (this
						.getPriceLumpScr() != null
						&& castOther.getPriceLumpScr() != null && this
						.getPriceLumpScr().equals(castOther.getPriceLumpScr())))
				&& ((this.getBaseuomConvFactor() == castOther
						.getBaseuomConvFactor()) || (this
						.getBaseuomConvFactor() != null
						&& castOther.getBaseuomConvFactor() != null && this
						.getBaseuomConvFactor().equals(
								castOther.getBaseuomConvFactor())))
				&& ((this.getBblMtFactor() == castOther.getBblMtFactor()) || (this
						.getBblMtFactor() != null
						&& castOther.getBblMtFactor() != null && this
						.getBblMtFactor().equals(castOther.getBblMtFactor())))
				&& ((this.getMtmPremium() == castOther.getMtmPremium()) || (this
						.getMtmPremium() != null
						&& castOther.getMtmPremium() != null && this
						.getMtmPremium().equals(castOther.getMtmPremium())))
				&& (this.getObligationOpenbalNum() == castOther
						.getObligationOpenbalNum())
				&& ((this.getPaymentDueDt() == castOther.getPaymentDueDt()) || (this
						.getPaymentDueDt() != null
						&& castOther.getPaymentDueDt() != null && this
						.getPaymentDueDt().equals(castOther.getPaymentDueDt())))
				&& ((this.getToleranceBelowPct() == castOther
						.getToleranceBelowPct()) || (this
						.getToleranceBelowPct() != null
						&& castOther.getToleranceBelowPct() != null && this
						.getToleranceBelowPct().equals(
								castOther.getToleranceBelowPct())))
				&& ((this.getToleranceAbovePct() == castOther
						.getToleranceAbovePct()) || (this
						.getToleranceAbovePct() != null
						&& castOther.getToleranceAbovePct() != null && this
						.getToleranceAbovePct().equals(
								castOther.getToleranceAbovePct())))
				&& ((this.getPipelineCycleCd() == castOther
						.getPipelineCycleCd()) || (this.getPipelineCycleCd() != null
						&& castOther.getPipelineCycleCd() != null && this
						.getPipelineCycleCd().equals(
								castOther.getPipelineCycleCd())))
				&& ((this.getLastModifyDt() == castOther.getLastModifyDt()) || (this
						.getLastModifyDt() != null
						&& castOther.getLastModifyDt() != null && this
						.getLastModifyDt().equals(castOther.getLastModifyDt())))
				&& (this.getModifyPersonNum() == castOther.getModifyPersonNum())
				&& (this.getLockNum() == castOther.getLockNum())
				&& ((this.getObligationTypeInd() == castOther
						.getObligationTypeInd()) || (this
						.getObligationTypeInd() != null
						&& castOther.getObligationTypeInd() != null && this
						.getObligationTypeInd().equals(
								castOther.getObligationTypeInd())))
				&& ((this.getStdPrice() == castOther.getStdPrice()) || (this
						.getStdPrice() != null
						&& castOther.getStdPrice() != null && this
						.getStdPrice().equals(castOther.getStdPrice())))
				&& ((this.getStdPriceCurrCd() == castOther.getStdPriceCurrCd()) || (this
						.getStdPriceCurrCd() != null
						&& castOther.getStdPriceCurrCd() != null && this
						.getStdPriceCurrCd().equals(
								castOther.getStdPriceCurrCd())))
				&& ((this.getStdPriceUomCd() == castOther.getStdPriceUomCd()) || (this
						.getStdPriceUomCd() != null
						&& castOther.getStdPriceUomCd() != null && this
						.getStdPriceUomCd()
						.equals(castOther.getStdPriceUomCd())))
				&& (this.getPlanningLocationNum() == castOther
						.getPlanningLocationNum())
				&& ((this.getTradeTypeCd() == castOther.getTradeTypeCd()) || (this
						.getTradeTypeCd() != null
						&& castOther.getTradeTypeCd() != null && this
						.getTradeTypeCd().equals(castOther.getTradeTypeCd())))
				&& ((this.getInstrumentTypeCd() == castOther
						.getInstrumentTypeCd()) || (this.getInstrumentTypeCd() != null
						&& castOther.getInstrumentTypeCd() != null && this
						.getInstrumentTypeCd().equals(
								castOther.getInstrumentTypeCd())))
				&& ((this.getObligationScheduledInd() == castOther
						.getObligationScheduledInd()) || (this
						.getObligationScheduledInd() != null
						&& castOther.getObligationScheduledInd() != null && this
						.getObligationScheduledInd().equals(
								castOther.getObligationScheduledInd())))
				&& ((this.getVentureCd() == castOther.getVentureCd()) || (this
						.getVentureCd() != null
						&& castOther.getVentureCd() != null && this
						.getVentureCd().equals(castOther.getVentureCd())))
				&& (this.getCustomsDutyStatusInd() == castOther
						.getCustomsDutyStatusInd())
				&& (this.getSchConfExecutedInd() == castOther
						.getSchConfExecutedInd())
				&& ((this.getStatusInd() == castOther.getStatusInd()) || (this
						.getStatusInd() != null
						&& castOther.getStatusInd() != null && this
						.getStatusInd().equals(castOther.getStatusInd())))
				&& ((this.getExternalRef() == castOther.getExternalRef()) || (this
						.getExternalRef() != null
						&& castOther.getExternalRef() != null && this
						.getExternalRef().equals(castOther.getExternalRef())))
				&& ((this.getTradePriceCurrCd() == castOther
						.getTradePriceCurrCd()) || (this.getTradePriceCurrCd() != null
						&& castOther.getTradePriceCurrCd() != null && this
						.getTradePriceCurrCd().equals(
								castOther.getTradePriceCurrCd())))
				&& ((this.getSpecCd() == castOther.getSpecCd()) || (this
						.getSpecCd() != null && castOther.getSpecCd() != null && this
						.getSpecCd().equals(castOther.getSpecCd())))
				&& ((this.getSettlePaymentTermCd() == castOther
						.getSettlePaymentTermCd()) || (this
						.getSettlePaymentTermCd() != null
						&& castOther.getSettlePaymentTermCd() != null && this
						.getSettlePaymentTermCd().equals(
								castOther.getSettlePaymentTermCd())))
				&& (this.getPricingStatusInd() == castOther
						.getPricingStatusInd())
				&& (this.getFuturesPricingStatusInd() == castOther
						.getFuturesPricingStatusInd())
				&& (this.getBasisPricingStatusInd() == castOther
						.getBasisPricingStatusInd())
				&& (this.getShippingCompanyNum() == castOther
						.getShippingCompanyNum())
				&& ((this.getOriginationLocNum() == castOther
						.getOriginationLocNum()) || (this
						.getOriginationLocNum() != null
						&& castOther.getOriginationLocNum() != null && this
						.getOriginationLocNum().equals(
								castOther.getOriginationLocNum())))
				&& (this.getDestinationLocNum() == castOther
						.getDestinationLocNum())
				&& (this.getInterCompInd() == castOther.getInterCompInd())
				&& (this.getInterCompTrdNum() == castOther.getInterCompTrdNum())
				&& (this.getInterCompOpenbalNum() == castOther
						.getInterCompOpenbalNum())
				&& ((this.getReportingPeriodDt() == castOther
						.getReportingPeriodDt()) || (this
						.getReportingPeriodDt() != null
						&& castOther.getReportingPeriodDt() != null && this
						.getReportingPeriodDt().equals(
								castOther.getReportingPeriodDt())))
				&& ((this.getMin1ToleranceQty() == castOther
						.getMin1ToleranceQty()) || (this.getMin1ToleranceQty() != null
						&& castOther.getMin1ToleranceQty() != null && this
						.getMin1ToleranceQty().equals(
								castOther.getMin1ToleranceQty())))
				&& ((this.getMax1ToleranceQty() == castOther
						.getMax1ToleranceQty()) || (this.getMax1ToleranceQty() != null
						&& castOther.getMax1ToleranceQty() != null && this
						.getMax1ToleranceQty().equals(
								castOther.getMax1ToleranceQty())))
				&& ((this.getToleranceBaseQty() == castOther
						.getToleranceBaseQty()) || (this.getToleranceBaseQty() != null
						&& castOther.getToleranceBaseQty() != null && this
						.getToleranceBaseQty().equals(
								castOther.getToleranceBaseQty())))
				&& ((this.getToleranceDelivQty() == castOther
						.getToleranceDelivQty()) || (this
						.getToleranceDelivQty() != null
						&& castOther.getToleranceDelivQty() != null && this
						.getToleranceDelivQty().equals(
								castOther.getToleranceDelivQty())))
				&& ((this.getOverUnderShipmentQty() == castOther
						.getOverUnderShipmentQty()) || (this
						.getOverUnderShipmentQty() != null
						&& castOther.getOverUnderShipmentQty() != null && this
						.getOverUnderShipmentQty().equals(
								castOther.getOverUnderShipmentQty())))
				&& (this.getBulkToleranceScheduleInd() == castOther
						.getBulkToleranceScheduleInd())
				&& ((this.getUptoTmin1Qty() == castOther.getUptoTmin1Qty()) || (this
						.getUptoTmin1Qty() != null
						&& castOther.getUptoTmin1Qty() != null && this
						.getUptoTmin1Qty().equals(castOther.getUptoTmin1Qty())))
				&& ((this.getUptoTmax1Qty() == castOther.getUptoTmax1Qty()) || (this
						.getUptoTmax1Qty() != null
						&& castOther.getUptoTmax1Qty() != null && this
						.getUptoTmax1Qty().equals(castOther.getUptoTmax1Qty())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getObligationNum();
		result = 37
				* result
				+ (getMtmPremiumUomCd() == null ? 0 : this.getMtmPremiumUomCd()
						.hashCode());
		result = 37
				* result
				+ (getMtmPremiumCurrCd() == null ? 0 : this
						.getMtmPremiumCurrCd().hashCode());
		result = 37 * result + this.getMtmQuoteDefNum();
		result = 37
				* result
				+ (getMtmPeriodCd() == null ? 0 : this.getMtmPeriodCd()
						.hashCode());
		result = 37 * result + this.getJvCounterpartCompanyNum();
		result = 37
				* result
				+ (getStrategyNum() == null ? 0 : this.getStrategyNum()
						.hashCode());
		result = 37 * result + this.getTermNum();
		result = 37 * result
				+ (getTradeNum() == null ? 0 : this.getTradeNum().hashCode());
		result = 37 * result + this.getDetailNum();
		result = 37
				* result
				+ (getInternalCoNum() == null ? 0 : this.getInternalCoNum()
						.hashCode());
		result = 37
				* result
				+ (getCompanyNum() == null ? 0 : this.getCompanyNum()
						.hashCode());
		result = 37
				* result
				+ (getBuySellInd() == null ? 0 : this.getBuySellInd()
						.hashCode());
		result = 37 * result
				+ (getCmdtyCd() == null ? 0 : this.getCmdtyCd().hashCode());
		result = 37
				* result
				+ (getLocationNum() == null ? 0 : this.getLocationNum()
						.hashCode());
		result = 37
				* result
				+ (getMotTypeInd() == null ? 0 : this.getMotTypeInd()
						.hashCode());
		result = 37
				* result
				+ (getTraderPersonNum() == null ? 0 : this.getTraderPersonNum()
						.hashCode());
		result = 37
				* result
				+ (getDeliveryTermCd() == null ? 0 : this.getDeliveryTermCd()
						.hashCode());
		result = 37 * result
				+ (getBaseQty() == null ? 0 : this.getBaseQty().hashCode());
		result = 37 * result
				+ (getBaseUomCd() == null ? 0 : this.getBaseUomCd().hashCode());
		result = 37
				* result
				+ (getContractQty() == null ? 0 : this.getContractQty()
						.hashCode());
		result = 37
				* result
				+ (getContractUomCd() == null ? 0 : this.getContractUomCd()
						.hashCode());
		result = 37 * result
				+ (getOpenQty() == null ? 0 : this.getOpenQty().hashCode());
		result = 37 * result
				+ (getDelivQty() == null ? 0 : this.getDelivQty().hashCode());
		result = 37
				* result
				+ (getDelivUomCd() == null ? 0 : this.getDelivUomCd()
						.hashCode());
		result = 37
				* result
				+ (getPackagingQty() == null ? 0 : this.getPackagingQty()
						.hashCode());
		result = 37
				* result
				+ (getPackagingUomCd() == null ? 0 : this.getPackagingUomCd()
						.hashCode());
		result = 37
				* result
				+ (getSettlementCurrCd() == null ? 0 : this
						.getSettlementCurrCd().hashCode());
		result = 37
				* result
				+ (getSettlementUomCd() == null ? 0 : this.getSettlementUomCd()
						.hashCode());
		result = 37
				* result
				+ (getUomConversionRate() == null ? 0 : this
						.getUomConversionRate().hashCode());
		result = 37 * result
				+ (getPrice() == null ? 0 : this.getPrice().hashCode());
		result = 37
				* result
				+ (getPriceUomCd() == null ? 0 : this.getPriceUomCd()
						.hashCode());
		result = 37
				* result
				+ (getPriceCurrCd() == null ? 0 : this.getPriceCurrCd()
						.hashCode());
		result = 37 * result
				+ (getPriceScr() == null ? 0 : this.getPriceScr().hashCode());
		result = 37 * result + this.getPriceStatusInd();
		result = 37
				* result
				+ (getApiGravity() == null ? 0 : this.getApiGravity()
						.hashCode());
		result = 37
				* result
				+ (getSpecificGravity() == null ? 0 : this.getSpecificGravity()
						.hashCode());
		result = 37 * result + this.getAirVacInd();
		result = 37
				* result
				+ (getInternalInd() == null ? 0 : this.getInternalInd()
						.hashCode());
		result = 37
				* result
				+ (getLaycanStartDt() == null ? 0 : this.getLaycanStartDt()
						.hashCode());
		result = 37
				* result
				+ (getLaycanEndDt() == null ? 0 : this.getLaycanEndDt()
						.hashCode());
		result = 37
				* result
				+ (getMtmFwdCurveNum() == null ? 0 : this.getMtmFwdCurveNum()
						.hashCode());
		result = 37
				* result
				+ (getFormulaPriceEventInd() == null ? 0 : this
						.getFormulaPriceEventInd().hashCode());
		result = 37
				* result
				+ (getPayDtEvent1Ind() == null ? 0 : this.getPayDtEvent1Ind()
						.hashCode());
		result = 37
				* result
				+ (getPayDtEvent2Ind() == null ? 0 : this.getPayDtEvent2Ind()
						.hashCode());
		result = 37
				* result
				+ (getDeemedBlDt() == null ? 0 : this.getDeemedBlDt()
						.hashCode());
		result = 37
				* result
				+ (getDeemedNorDt() == null ? 0 : this.getDeemedNorDt()
						.hashCode());
		result = 37
				* result
				+ (getDeemedCommLDt() == null ? 0 : this.getDeemedCommLDt()
						.hashCode());
		result = 37
				* result
				+ (getDeemedCompLDt() == null ? 0 : this.getDeemedCompLDt()
						.hashCode());
		result = 37
				* result
				+ (getDeemedCommDDt() == null ? 0 : this.getDeemedCommDDt()
						.hashCode());
		result = 37
				* result
				+ (getDeemedCompDDt() == null ? 0 : this.getDeemedCompDDt()
						.hashCode());
		result = 37
				* result
				+ (getDeemedRoiDt() == null ? 0 : this.getDeemedRoiDt()
						.hashCode());
		result = 37
				* result
				+ (getDeemedDeliveryMonthEndDt() == null ? 0 : this
						.getDeemedDeliveryMonthEndDt().hashCode());
		result = 37
				* result
				+ (getRiskStartDt() == null ? 0 : this.getRiskStartDt()
						.hashCode());
		result = 37
				* result
				+ (getTimePeriodTypeInd() == null ? 0 : this
						.getTimePeriodTypeInd().hashCode());
		result = 37 * result + this.getMotNum();
		result = 37
				* result
				+ (getOriginLocNum() == null ? 0 : this.getOriginLocNum()
						.hashCode());
		result = 37 * result + this.getTradeStatusInd();
		result = 37
				* result
				+ (getDeliverySchedCd() == null ? 0 : this.getDeliverySchedCd()
						.hashCode());
		result = 37
				* result
				+ (getMinTolerance() == null ? 0 : this.getMinTolerance()
						.hashCode());
		result = 37
				* result
				+ (getMaxTolerance() == null ? 0 : this.getMaxTolerance()
						.hashCode());
		result = 37
				* result
				+ (getTermSectionCd() == null ? 0 : this.getTermSectionCd()
						.hashCode());
		result = 37
				* result
				+ (getPurchaseCategoryCd() == null ? 0 : this
						.getPurchaseCategoryCd().hashCode());
		result = 37
				* result
				+ (getOpenBalAdjQty() == null ? 0 : this.getOpenBalAdjQty()
						.hashCode());
		result = 37
				* result
				+ (getRfVersionNum() == null ? 0 : this.getRfVersionNum()
						.hashCode());
		result = 37
				* result
				+ (getPriceLumpScr() == null ? 0 : this.getPriceLumpScr()
						.hashCode());
		result = 37
				* result
				+ (getBaseuomConvFactor() == null ? 0 : this
						.getBaseuomConvFactor().hashCode());
		result = 37
				* result
				+ (getBblMtFactor() == null ? 0 : this.getBblMtFactor()
						.hashCode());
		result = 37
				* result
				+ (getMtmPremium() == null ? 0 : this.getMtmPremium()
						.hashCode());
		result = 37 * result + this.getObligationOpenbalNum();
		result = 37
				* result
				+ (getPaymentDueDt() == null ? 0 : this.getPaymentDueDt()
						.hashCode());
		result = 37
				* result
				+ (getToleranceBelowPct() == null ? 0 : this
						.getToleranceBelowPct().hashCode());
		result = 37
				* result
				+ (getToleranceAbovePct() == null ? 0 : this
						.getToleranceAbovePct().hashCode());
		result = 37
				* result
				+ (getPipelineCycleCd() == null ? 0 : this.getPipelineCycleCd()
						.hashCode());
		result = 37
				* result
				+ (getLastModifyDt() == null ? 0 : this.getLastModifyDt()
						.hashCode());
		result = 37 * result + this.getModifyPersonNum();
		result = 37 * result + this.getLockNum();
		result = 37
				* result
				+ (getObligationTypeInd() == null ? 0 : this
						.getObligationTypeInd().hashCode());
		result = 37 * result
				+ (getStdPrice() == null ? 0 : this.getStdPrice().hashCode());
		result = 37
				* result
				+ (getStdPriceCurrCd() == null ? 0 : this.getStdPriceCurrCd()
						.hashCode());
		result = 37
				* result
				+ (getStdPriceUomCd() == null ? 0 : this.getStdPriceUomCd()
						.hashCode());
		result = 37 * result + this.getPlanningLocationNum();
		result = 37
				* result
				+ (getTradeTypeCd() == null ? 0 : this.getTradeTypeCd()
						.hashCode());
		result = 37
				* result
				+ (getInstrumentTypeCd() == null ? 0 : this
						.getInstrumentTypeCd().hashCode());
		result = 37
				* result
				+ (getObligationScheduledInd() == null ? 0 : this
						.getObligationScheduledInd().hashCode());
		result = 37 * result
				+ (getVentureCd() == null ? 0 : this.getVentureCd().hashCode());
		result = 37 * result + this.getCustomsDutyStatusInd();
		result = 37 * result + this.getSchConfExecutedInd();
		result = 37 * result
				+ (getStatusInd() == null ? 0 : this.getStatusInd().hashCode());
		result = 37
				* result
				+ (getExternalRef() == null ? 0 : this.getExternalRef()
						.hashCode());
		result = 37
				* result
				+ (getTradePriceCurrCd() == null ? 0 : this
						.getTradePriceCurrCd().hashCode());
		result = 37 * result
				+ (getSpecCd() == null ? 0 : this.getSpecCd().hashCode());
		result = 37
				* result
				+ (getSettlePaymentTermCd() == null ? 0 : this
						.getSettlePaymentTermCd().hashCode());
		result = 37 * result + this.getPricingStatusInd();
		result = 37 * result + this.getFuturesPricingStatusInd();
		result = 37 * result + this.getBasisPricingStatusInd();
		result = 37 * result + this.getShippingCompanyNum();
		result = 37
				* result
				+ (getOriginationLocNum() == null ? 0 : this
						.getOriginationLocNum().hashCode());
		result = 37 * result + this.getDestinationLocNum();
		result = 37 * result + this.getInterCompInd();
		result = 37 * result + this.getInterCompTrdNum();
		result = 37 * result + this.getInterCompOpenbalNum();
		result = 37
				* result
				+ (getReportingPeriodDt() == null ? 0 : this
						.getReportingPeriodDt().hashCode());
		result = 37
				* result
				+ (getMin1ToleranceQty() == null ? 0 : this
						.getMin1ToleranceQty().hashCode());
		result = 37
				* result
				+ (getMax1ToleranceQty() == null ? 0 : this
						.getMax1ToleranceQty().hashCode());
		result = 37
				* result
				+ (getToleranceBaseQty() == null ? 0 : this
						.getToleranceBaseQty().hashCode());
		result = 37
				* result
				+ (getToleranceDelivQty() == null ? 0 : this
						.getToleranceDelivQty().hashCode());
		result = 37
				* result
				+ (getOverUnderShipmentQty() == null ? 0 : this
						.getOverUnderShipmentQty().hashCode());
		result = 37 * result + this.getBulkToleranceScheduleInd();
		result = 37
				* result
				+ (getUptoTmin1Qty() == null ? 0 : this.getUptoTmin1Qty()
						.hashCode());
		result = 37
				* result
				+ (getUptoTmax1Qty() == null ? 0 : this.getUptoTmax1Qty()
						.hashCode());
		return result;
	}

}
