package com.mercon.entities;

// Generated Aug 6, 2014 2:29:04 PM by Hibernate Tools 3.4.0.CR1

/**
 * VopsItiDefaultActionDetail generated by hbm2java
 */
public class VopsItiDefaultActionDetail implements java.io.Serializable {

	/**
	 * Serial ID
	 */
	private static final long serialVersionUID = -120908135196023456L;
	
	private VopsItiDefaultActionDetailId id;

	public VopsItiDefaultActionDetail() {
	}

	public VopsItiDefaultActionDetail(VopsItiDefaultActionDetailId id) {
		this.id = id;
	}

	public VopsItiDefaultActionDetailId getId() {
		return this.id;
	}

	public void setId(VopsItiDefaultActionDetailId id) {
		this.id = id;
	}

}
