package com.mercon.entities;

// Generated Jul 2, 2014 5:30:24 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.validation.constraints.Digits;

/**
 * VopsObligationMatchId generated by hbm2java
 */
public class VopsObligationMatchId implements java.io.Serializable {

	/**
	 * Serial ID
	 */
	private static final long serialVersionUID = -7630122768656431636L;
	
	private int obligationMatchNum;
	private Date matchDt;
	private Date applicationDt;
	private String matchDesc;
	private Short motTypeInd;
	private VgenIndicatorId motType;
	private int loadMotNum;
	private int dischargeMotNum;
	private int motNum;
	private int titleTransferLocationNum;
	private String cmdtyCd;
	private short deliveryStatusInd;
	private Integer operatorPersonNum;
	private VdimPersonId operatorPerson;
	private Integer internalCoNum;
	private VdimCompanyId internalCompany;
	private int loadLocationNum;
	private int dischargeLocationNum;
	private int loadPortLocationNum;
	private int dischargePortLocationNum;
	private String batch;
	private String sequence;
	private String tow;
	private Date finalizedDt;
	private int txlPsNum;
	private int noteNum;
	private short deliveryTypeInd;
	private String ourRef;
	private String theirRef;
	private Date paymentDueDt;
	private Date blDt;
	private Date invoiceDt;
	private int counterpartContactNum;
	private int loadCargoNum;
	private int loadEquipmentNum;
	private int internalContactNum;
	private int dischargeEquipmentNum;
	private int dischargeCargoNum;
	private Date etaLoadDt;
	private Date completionLoadDt;
	private Date commenceLoadDt;
	private Date etaDischargeDt;
	private Date completionDischargeDt;
	private Date commenceDischargeDt;
	private Date lastModifyDt;
	private int modifyPersonNum;
	private int lockNum;
	private short matchAtInd;
	private BigDecimal matchPrice;
	private String matchPriceCurrCd;
	private String matchPriceUomCd;
	private Integer mtmFwdCurveNum;
	private String customInvoiceFormatCd;
	private short invoiceFormatTypeInd;
	private String docTypeCd;
	private String docTemplateCd;
	private String ventureCd;
	private short hasAttachmentInd;
	private Short createInvoiceInd;
	private String matchDescNl;
	private String languageCd;
	private Short deliveryActiveStatusInd;
	private Date liquidateDt;
	private short initiatorInd;
	private Date pumpDt;
	private String matchSettlementCurrCd;
	private String pipelineCycleCd;
	private BigDecimal mktBasisDiff;
	private Short mktPriceLockDtInd;
	private Date mktPriceLockDt;
	private List<VopsObligationDetail> opsObligationDetail;
	private VtradeInputId pTradeInputId;
	private VtradeInputId sTradeInputId;

	@Digits(integer = 15, fraction = 0)
	private Integer tradeContractNumber;
	
	public VopsObligationMatchId() {
	}

	public VopsObligationMatchId(int obligationMatchNum, Date matchDt,
			Date applicationDt, String matchDesc, Short motTypeInd,
			int loadMotNum, int dischargeMotNum, int motNum,
			int titleTransferLocationNum, String cmdtyCd,
			short deliveryStatusInd, Integer operatorPersonNum,
			Integer internalCoNum, int loadLocationNum,
			int dischargeLocationNum, int loadPortLocationNum,
			int dischargePortLocationNum, String batch, String sequence,
			String tow, Date finalizedDt, int txlPsNum, int noteNum,
			short deliveryTypeInd, String ourRef, String theirRef,
			Date paymentDueDt, Date blDt, Date invoiceDt,
			int counterpartContactNum, int loadCargoNum, int loadEquipmentNum,
			int internalContactNum, int dischargeEquipmentNum,
			int dischargeCargoNum, Date etaLoadDt, Date completionLoadDt,
			Date commenceLoadDt, Date etaDischargeDt,
			Date completionDischargeDt, Date commenceDischargeDt,
			Date lastModifyDt, int modifyPersonNum, int lockNum,
			short matchAtInd, BigDecimal matchPrice, String matchPriceCurrCd,
			String matchPriceUomCd, Integer mtmFwdCurveNum,
			String customInvoiceFormatCd, short invoiceFormatTypeInd,
			String docTypeCd, String docTemplateCd, String ventureCd,
			short hasAttachmentInd, Short createInvoiceInd, String matchDescNl,
			String languageCd, Short deliveryActiveStatusInd, Date liquidateDt,
			short initiatorInd, Date pumpDt, String matchSettlementCurrCd,
			String pipelineCycleCd, BigDecimal mktBasisDiff,
			Short mktPriceLockDtInd, Date mktPriceLockDt) {
		this.obligationMatchNum = obligationMatchNum;
		this.matchDt = matchDt;
		this.applicationDt = applicationDt;
		this.matchDesc = matchDesc;
		this.motTypeInd = motTypeInd;
		this.loadMotNum = loadMotNum;
		this.dischargeMotNum = dischargeMotNum;
		this.motNum = motNum;
		this.titleTransferLocationNum = titleTransferLocationNum;
		this.cmdtyCd = cmdtyCd;
		this.deliveryStatusInd = deliveryStatusInd;
		this.operatorPersonNum = operatorPersonNum;
		this.internalCoNum = internalCoNum;
		this.loadLocationNum = loadLocationNum;
		this.dischargeLocationNum = dischargeLocationNum;
		this.loadPortLocationNum = loadPortLocationNum;
		this.dischargePortLocationNum = dischargePortLocationNum;
		this.batch = batch;
		this.sequence = sequence;
		this.tow = tow;
		this.finalizedDt = finalizedDt;
		this.txlPsNum = txlPsNum;
		this.noteNum = noteNum;
		this.deliveryTypeInd = deliveryTypeInd;
		this.ourRef = ourRef;
		this.theirRef = theirRef;
		this.paymentDueDt = paymentDueDt;
		this.blDt = blDt;
		this.invoiceDt = invoiceDt;
		this.counterpartContactNum = counterpartContactNum;
		this.loadCargoNum = loadCargoNum;
		this.loadEquipmentNum = loadEquipmentNum;
		this.internalContactNum = internalContactNum;
		this.dischargeEquipmentNum = dischargeEquipmentNum;
		this.dischargeCargoNum = dischargeCargoNum;
		this.etaLoadDt = etaLoadDt;
		this.completionLoadDt = completionLoadDt;
		this.commenceLoadDt = commenceLoadDt;
		this.etaDischargeDt = etaDischargeDt;
		this.completionDischargeDt = completionDischargeDt;
		this.commenceDischargeDt = commenceDischargeDt;
		this.lastModifyDt = lastModifyDt;
		this.modifyPersonNum = modifyPersonNum;
		this.lockNum = lockNum;
		this.matchAtInd = matchAtInd;
		this.matchPrice = matchPrice;
		this.matchPriceCurrCd = matchPriceCurrCd;
		this.matchPriceUomCd = matchPriceUomCd;
		this.mtmFwdCurveNum = mtmFwdCurveNum;
		this.customInvoiceFormatCd = customInvoiceFormatCd;
		this.invoiceFormatTypeInd = invoiceFormatTypeInd;
		this.docTypeCd = docTypeCd;
		this.docTemplateCd = docTemplateCd;
		this.ventureCd = ventureCd;
		this.hasAttachmentInd = hasAttachmentInd;
		this.createInvoiceInd = createInvoiceInd;
		this.matchDescNl = matchDescNl;
		this.languageCd = languageCd;
		this.deliveryActiveStatusInd = deliveryActiveStatusInd;
		this.liquidateDt = liquidateDt;
		this.initiatorInd = initiatorInd;
		this.pumpDt = pumpDt;
		this.matchSettlementCurrCd = matchSettlementCurrCd;
		this.pipelineCycleCd = pipelineCycleCd;
		this.mktBasisDiff = mktBasisDiff;
		this.mktPriceLockDtInd = mktPriceLockDtInd;
		this.mktPriceLockDt = mktPriceLockDt;
	}

	public int getObligationMatchNum() {
		return this.obligationMatchNum;
	}

	public void setObligationMatchNum(int obligationMatchNum) {
		this.obligationMatchNum = obligationMatchNum;
	}

	public Date getMatchDt() {
		return this.matchDt;
	}

	public void setMatchDt(Date matchDt) {
		this.matchDt = matchDt;
	}

	public Date getApplicationDt() {
		return this.applicationDt;
	}

	public void setApplicationDt(Date applicationDt) {
		this.applicationDt = applicationDt;
	}

	public String getMatchDesc() {
		return this.matchDesc;
	}

	public void setMatchDesc(String matchDesc) {
		this.matchDesc = matchDesc;
	}

	public Short getMotTypeInd() {
		return this.motTypeInd;
	}

	public void setMotTypeInd(Short motTypeInd) {
		this.motTypeInd = motTypeInd;
	}
	
	public VgenIndicatorId getMotType() {
		return motType;
	}

	public void setMotType(VgenIndicatorId motType) {
		this.motType = motType;
	}

	public int getLoadMotNum() {
		return this.loadMotNum;
	}

	public void setLoadMotNum(int loadMotNum) {
		this.loadMotNum = loadMotNum;
	}

	public int getDischargeMotNum() {
		return this.dischargeMotNum;
	}

	public void setDischargeMotNum(int dischargeMotNum) {
		this.dischargeMotNum = dischargeMotNum;
	}

	public int getMotNum() {
		return this.motNum;
	}

	public void setMotNum(int motNum) {
		this.motNum = motNum;
	}

	public int getTitleTransferLocationNum() {
		return this.titleTransferLocationNum;
	}

	public void setTitleTransferLocationNum(int titleTransferLocationNum) {
		this.titleTransferLocationNum = titleTransferLocationNum;
	}

	public String getCmdtyCd() {
		return this.cmdtyCd;
	}

	public void setCmdtyCd(String cmdtyCd) {
		this.cmdtyCd = cmdtyCd;
	}

	public short getDeliveryStatusInd() {
		return this.deliveryStatusInd;
	}

	public void setDeliveryStatusInd(short deliveryStatusInd) {
		this.deliveryStatusInd = deliveryStatusInd;
	}

	public Integer getOperatorPersonNum() {
		return this.operatorPersonNum;
	}

	public void setOperatorPersonNum(Integer operatorPersonNum) {
		this.operatorPersonNum = operatorPersonNum;
	}
	
	public VdimPersonId getOperatorPerson() {
		return operatorPerson;
	}

	public void setOperatorPerson(VdimPersonId operatorPerson) {
		this.operatorPerson = operatorPerson;
	}

	public Integer getInternalCoNum() {
		return this.internalCoNum;
	}

	public void setInternalCoNum(Integer internalCoNum) {
		this.internalCoNum = internalCoNum;
	}
	
	public VdimCompanyId getInternalCompany() {
		return internalCompany;
	}

	public void setInternalCompany(VdimCompanyId internalCompany) {
		this.internalCompany = internalCompany;
	}

	public int getLoadLocationNum() {
		return this.loadLocationNum;
	}

	public void setLoadLocationNum(int loadLocationNum) {
		this.loadLocationNum = loadLocationNum;
	}

	public int getDischargeLocationNum() {
		return this.dischargeLocationNum;
	}

	public void setDischargeLocationNum(int dischargeLocationNum) {
		this.dischargeLocationNum = dischargeLocationNum;
	}

	public int getLoadPortLocationNum() {
		return this.loadPortLocationNum;
	}

	public void setLoadPortLocationNum(int loadPortLocationNum) {
		this.loadPortLocationNum = loadPortLocationNum;
	}

	public int getDischargePortLocationNum() {
		return this.dischargePortLocationNum;
	}

	public void setDischargePortLocationNum(int dischargePortLocationNum) {
		this.dischargePortLocationNum = dischargePortLocationNum;
	}

	public String getBatch() {
		return this.batch;
	}

	public void setBatch(String batch) {
		this.batch = batch;
	}

	public String getSequence() {
		return this.sequence;
	}

	public void setSequence(String sequence) {
		this.sequence = sequence;
	}

	public String getTow() {
		return this.tow;
	}

	public void setTow(String tow) {
		this.tow = tow;
	}

	public Date getFinalizedDt() {
		return this.finalizedDt;
	}

	public void setFinalizedDt(Date finalizedDt) {
		this.finalizedDt = finalizedDt;
	}

	public int getTxlPsNum() {
		return this.txlPsNum;
	}

	public void setTxlPsNum(int txlPsNum) {
		this.txlPsNum = txlPsNum;
	}

	public int getNoteNum() {
		return this.noteNum;
	}

	public void setNoteNum(int noteNum) {
		this.noteNum = noteNum;
	}

	public short getDeliveryTypeInd() {
		return this.deliveryTypeInd;
	}

	public void setDeliveryTypeInd(short deliveryTypeInd) {
		this.deliveryTypeInd = deliveryTypeInd;
	}

	public String getOurRef() {
		return this.ourRef;
	}

	public void setOurRef(String ourRef) {
		this.ourRef = ourRef;
	}

	public String getTheirRef() {
		return this.theirRef;
	}

	public void setTheirRef(String theirRef) {
		this.theirRef = theirRef;
	}

	public Date getPaymentDueDt() {
		return this.paymentDueDt;
	}

	public void setPaymentDueDt(Date paymentDueDt) {
		this.paymentDueDt = paymentDueDt;
	}

	public Date getBlDt() {
		return this.blDt;
	}

	public void setBlDt(Date blDt) {
		this.blDt = blDt;
	}

	public Date getInvoiceDt() {
		return this.invoiceDt;
	}

	public void setInvoiceDt(Date invoiceDt) {
		this.invoiceDt = invoiceDt;
	}

	public int getCounterpartContactNum() {
		return this.counterpartContactNum;
	}

	public void setCounterpartContactNum(int counterpartContactNum) {
		this.counterpartContactNum = counterpartContactNum;
	}

	public int getLoadCargoNum() {
		return this.loadCargoNum;
	}

	public void setLoadCargoNum(int loadCargoNum) {
		this.loadCargoNum = loadCargoNum;
	}

	public int getLoadEquipmentNum() {
		return this.loadEquipmentNum;
	}

	public void setLoadEquipmentNum(int loadEquipmentNum) {
		this.loadEquipmentNum = loadEquipmentNum;
	}

	public int getInternalContactNum() {
		return this.internalContactNum;
	}

	public void setInternalContactNum(int internalContactNum) {
		this.internalContactNum = internalContactNum;
	}

	public int getDischargeEquipmentNum() {
		return this.dischargeEquipmentNum;
	}

	public void setDischargeEquipmentNum(int dischargeEquipmentNum) {
		this.dischargeEquipmentNum = dischargeEquipmentNum;
	}

	public int getDischargeCargoNum() {
		return this.dischargeCargoNum;
	}

	public void setDischargeCargoNum(int dischargeCargoNum) {
		this.dischargeCargoNum = dischargeCargoNum;
	}

	public Date getEtaLoadDt() {
		return this.etaLoadDt;
	}

	public void setEtaLoadDt(Date etaLoadDt) {
		this.etaLoadDt = etaLoadDt;
	}

	public Date getCompletionLoadDt() {
		return this.completionLoadDt;
	}

	public void setCompletionLoadDt(Date completionLoadDt) {
		this.completionLoadDt = completionLoadDt;
	}

	public Date getCommenceLoadDt() {
		return this.commenceLoadDt;
	}

	public void setCommenceLoadDt(Date commenceLoadDt) {
		this.commenceLoadDt = commenceLoadDt;
	}

	public Date getEtaDischargeDt() {
		return this.etaDischargeDt;
	}

	public void setEtaDischargeDt(Date etaDischargeDt) {
		this.etaDischargeDt = etaDischargeDt;
	}

	public Date getCompletionDischargeDt() {
		return this.completionDischargeDt;
	}

	public void setCompletionDischargeDt(Date completionDischargeDt) {
		this.completionDischargeDt = completionDischargeDt;
	}

	public Date getCommenceDischargeDt() {
		return this.commenceDischargeDt;
	}

	public void setCommenceDischargeDt(Date commenceDischargeDt) {
		this.commenceDischargeDt = commenceDischargeDt;
	}

	public Date getLastModifyDt() {
		return this.lastModifyDt;
	}

	public void setLastModifyDt(Date lastModifyDt) {
		this.lastModifyDt = lastModifyDt;
	}

	public int getModifyPersonNum() {
		return this.modifyPersonNum;
	}

	public void setModifyPersonNum(int modifyPersonNum) {
		this.modifyPersonNum = modifyPersonNum;
	}

	public int getLockNum() {
		return this.lockNum;
	}

	public void setLockNum(int lockNum) {
		this.lockNum = lockNum;
	}

	public short getMatchAtInd() {
		return this.matchAtInd;
	}

	public void setMatchAtInd(short matchAtInd) {
		this.matchAtInd = matchAtInd;
	}

	public BigDecimal getMatchPrice() {
		return this.matchPrice;
	}

	public void setMatchPrice(BigDecimal matchPrice) {
		this.matchPrice = matchPrice;
	}

	public String getMatchPriceCurrCd() {
		return this.matchPriceCurrCd;
	}

	public void setMatchPriceCurrCd(String matchPriceCurrCd) {
		this.matchPriceCurrCd = matchPriceCurrCd;
	}

	public String getMatchPriceUomCd() {
		return this.matchPriceUomCd;
	}

	public void setMatchPriceUomCd(String matchPriceUomCd) {
		this.matchPriceUomCd = matchPriceUomCd;
	}

	public Integer getMtmFwdCurveNum() {
		return this.mtmFwdCurveNum;
	}

	public void setMtmFwdCurveNum(Integer mtmFwdCurveNum) {
		this.mtmFwdCurveNum = mtmFwdCurveNum;
	}

	public String getCustomInvoiceFormatCd() {
		return this.customInvoiceFormatCd;
	}

	public void setCustomInvoiceFormatCd(String customInvoiceFormatCd) {
		this.customInvoiceFormatCd = customInvoiceFormatCd;
	}

	public short getInvoiceFormatTypeInd() {
		return this.invoiceFormatTypeInd;
	}

	public void setInvoiceFormatTypeInd(short invoiceFormatTypeInd) {
		this.invoiceFormatTypeInd = invoiceFormatTypeInd;
	}

	public String getDocTypeCd() {
		return this.docTypeCd;
	}

	public void setDocTypeCd(String docTypeCd) {
		this.docTypeCd = docTypeCd;
	}

	public String getDocTemplateCd() {
		return this.docTemplateCd;
	}

	public void setDocTemplateCd(String docTemplateCd) {
		this.docTemplateCd = docTemplateCd;
	}

	public String getVentureCd() {
		return this.ventureCd;
	}

	public void setVentureCd(String ventureCd) {
		this.ventureCd = ventureCd;
	}

	public short getHasAttachmentInd() {
		return this.hasAttachmentInd;
	}

	public void setHasAttachmentInd(short hasAttachmentInd) {
		this.hasAttachmentInd = hasAttachmentInd;
	}

	public Short getCreateInvoiceInd() {
		return this.createInvoiceInd;
	}

	public void setCreateInvoiceInd(Short createInvoiceInd) {
		this.createInvoiceInd = createInvoiceInd;
	}

	public String getMatchDescNl() {
		return this.matchDescNl;
	}

	public void setMatchDescNl(String matchDescNl) {
		this.matchDescNl = matchDescNl;
	}

	public String getLanguageCd() {
		return this.languageCd;
	}

	public void setLanguageCd(String languageCd) {
		this.languageCd = languageCd;
	}

	public Short getDeliveryActiveStatusInd() {
		return this.deliveryActiveStatusInd;
	}

	public void setDeliveryActiveStatusInd(Short deliveryActiveStatusInd) {
		this.deliveryActiveStatusInd = deliveryActiveStatusInd;
	}

	public Date getLiquidateDt() {
		return this.liquidateDt;
	}

	public void setLiquidateDt(Date liquidateDt) {
		this.liquidateDt = liquidateDt;
	}

	public short getInitiatorInd() {
		return this.initiatorInd;
	}

	public void setInitiatorInd(short initiatorInd) {
		this.initiatorInd = initiatorInd;
	}

	public Date getPumpDt() {
		return this.pumpDt;
	}

	public void setPumpDt(Date pumpDt) {
		this.pumpDt = pumpDt;
	}

	public String getMatchSettlementCurrCd() {
		return this.matchSettlementCurrCd;
	}

	public void setMatchSettlementCurrCd(String matchSettlementCurrCd) {
		this.matchSettlementCurrCd = matchSettlementCurrCd;
	}

	public String getPipelineCycleCd() {
		return this.pipelineCycleCd;
	}

	public void setPipelineCycleCd(String pipelineCycleCd) {
		this.pipelineCycleCd = pipelineCycleCd;
	}

	public BigDecimal getMktBasisDiff() {
		return this.mktBasisDiff;
	}

	public void setMktBasisDiff(BigDecimal mktBasisDiff) {
		this.mktBasisDiff = mktBasisDiff;
	}

	public Short getMktPriceLockDtInd() {
		return this.mktPriceLockDtInd;
	}

	public void setMktPriceLockDtInd(Short mktPriceLockDtInd) {
		this.mktPriceLockDtInd = mktPriceLockDtInd;
	}

	public Date getMktPriceLockDt() {
		return this.mktPriceLockDt;
	}

	public void setMktPriceLockDt(Date mktPriceLockDt) {
		this.mktPriceLockDt = mktPriceLockDt;
	}
	
	public List<VopsObligationDetail> getOpsObligationDetail() {
		return opsObligationDetail;
	}

	public void setOpsObligationDetail(
			List<VopsObligationDetail> opsObligationDetail) {
		this.opsObligationDetail = opsObligationDetail;
	}
	
	public VtradeInputId getpTradeInputId() {
		return pTradeInputId;
	}

	public void setpTradeInputId(VtradeInputId pTradeInputId) {
		this.pTradeInputId = pTradeInputId;
	}

	public VtradeInputId getsTradeInputId() {
		return sTradeInputId;
	}

	public void setsTradeInputId(VtradeInputId sTradeInputId) {
		this.sTradeInputId = sTradeInputId;
	}
	
	public Integer getTradeContractNumber() {
		return tradeContractNumber;
	}

	public void setTradeContractNumber(Integer tradeContractNumber) {
		this.tradeContractNumber = tradeContractNumber;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((applicationDt == null) ? 0 : applicationDt.hashCode());
		result = prime * result + ((batch == null) ? 0 : batch.hashCode());
		result = prime * result + ((blDt == null) ? 0 : blDt.hashCode());
		result = prime * result + ((cmdtyCd == null) ? 0 : cmdtyCd.hashCode());
		result = prime
				* result
				+ ((commenceDischargeDt == null) ? 0 : commenceDischargeDt
						.hashCode());
		result = prime * result
				+ ((commenceLoadDt == null) ? 0 : commenceLoadDt.hashCode());
		result = prime
				* result
				+ ((completionDischargeDt == null) ? 0 : completionDischargeDt
						.hashCode());
		result = prime
				* result
				+ ((completionLoadDt == null) ? 0 : completionLoadDt.hashCode());
		result = prime * result + counterpartContactNum;
		result = prime
				* result
				+ ((createInvoiceInd == null) ? 0 : createInvoiceInd.hashCode());
		result = prime
				* result
				+ ((customInvoiceFormatCd == null) ? 0 : customInvoiceFormatCd
						.hashCode());
		result = prime
				* result
				+ ((deliveryActiveStatusInd == null) ? 0
						: deliveryActiveStatusInd.hashCode());
		result = prime * result + deliveryStatusInd;
		result = prime * result + deliveryTypeInd;
		result = prime * result + dischargeCargoNum;
		result = prime * result + dischargeEquipmentNum;
		result = prime * result + dischargeLocationNum;
		result = prime * result + dischargeMotNum;
		result = prime * result + dischargePortLocationNum;
		result = prime * result
				+ ((docTemplateCd == null) ? 0 : docTemplateCd.hashCode());
		result = prime * result
				+ ((docTypeCd == null) ? 0 : docTypeCd.hashCode());
		result = prime * result
				+ ((etaDischargeDt == null) ? 0 : etaDischargeDt.hashCode());
		result = prime * result
				+ ((etaLoadDt == null) ? 0 : etaLoadDt.hashCode());
		result = prime * result
				+ ((finalizedDt == null) ? 0 : finalizedDt.hashCode());
		result = prime * result + hasAttachmentInd;
		result = prime * result + initiatorInd;
		result = prime * result
				+ ((internalCoNum == null) ? 0 : internalCoNum.hashCode());
		result = prime * result + internalContactNum;
		result = prime * result
				+ ((invoiceDt == null) ? 0 : invoiceDt.hashCode());
		result = prime * result + invoiceFormatTypeInd;
		result = prime * result
				+ ((languageCd == null) ? 0 : languageCd.hashCode());
		result = prime * result
				+ ((lastModifyDt == null) ? 0 : lastModifyDt.hashCode());
		result = prime * result
				+ ((liquidateDt == null) ? 0 : liquidateDt.hashCode());
		result = prime * result + loadCargoNum;
		result = prime * result + loadEquipmentNum;
		result = prime * result + loadLocationNum;
		result = prime * result + loadMotNum;
		result = prime * result + loadPortLocationNum;
		result = prime * result + lockNum;
		result = prime * result + matchAtInd;
		result = prime * result
				+ ((matchDesc == null) ? 0 : matchDesc.hashCode());
		result = prime * result
				+ ((matchDescNl == null) ? 0 : matchDescNl.hashCode());
		result = prime * result + ((matchDt == null) ? 0 : matchDt.hashCode());
		result = prime * result
				+ ((matchPrice == null) ? 0 : matchPrice.hashCode());
		result = prime
				* result
				+ ((matchPriceCurrCd == null) ? 0 : matchPriceCurrCd.hashCode());
		result = prime * result
				+ ((matchPriceUomCd == null) ? 0 : matchPriceUomCd.hashCode());
		result = prime
				* result
				+ ((matchSettlementCurrCd == null) ? 0 : matchSettlementCurrCd
						.hashCode());
		result = prime * result
				+ ((mktBasisDiff == null) ? 0 : mktBasisDiff.hashCode());
		result = prime * result
				+ ((mktPriceLockDt == null) ? 0 : mktPriceLockDt.hashCode());
		result = prime
				* result
				+ ((mktPriceLockDtInd == null) ? 0 : mktPriceLockDtInd
						.hashCode());
		result = prime * result + modifyPersonNum;
		result = prime * result + motNum;
		result = prime * result
				+ ((motTypeInd == null) ? 0 : motTypeInd.hashCode());
		result = prime * result
				+ ((mtmFwdCurveNum == null) ? 0 : mtmFwdCurveNum.hashCode());
		result = prime * result + noteNum;
		result = prime * result + obligationMatchNum;
		result = prime
				* result
				+ ((operatorPersonNum == null) ? 0 : operatorPersonNum
						.hashCode());
		result = prime * result + ((ourRef == null) ? 0 : ourRef.hashCode());
		result = prime * result
				+ ((paymentDueDt == null) ? 0 : paymentDueDt.hashCode());
		result = prime * result
				+ ((pipelineCycleCd == null) ? 0 : pipelineCycleCd.hashCode());
		result = prime * result + ((pumpDt == null) ? 0 : pumpDt.hashCode());
		result = prime * result
				+ ((sequence == null) ? 0 : sequence.hashCode());
		result = prime * result
				+ ((theirRef == null) ? 0 : theirRef.hashCode());
		result = prime * result + titleTransferLocationNum;
		result = prime * result + ((tow == null) ? 0 : tow.hashCode());
		result = prime * result + txlPsNum;
		result = prime * result
				+ ((ventureCd == null) ? 0 : ventureCd.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		VopsObligationMatchId other = (VopsObligationMatchId) obj;
		if (applicationDt == null) {
			if (other.applicationDt != null)
				return false;
		} else if (!applicationDt.equals(other.applicationDt))
			return false;
		if (batch == null) {
			if (other.batch != null)
				return false;
		} else if (!batch.equals(other.batch))
			return false;
		if (blDt == null) {
			if (other.blDt != null)
				return false;
		} else if (!blDt.equals(other.blDt))
			return false;
		if (cmdtyCd == null) {
			if (other.cmdtyCd != null)
				return false;
		} else if (!cmdtyCd.equals(other.cmdtyCd))
			return false;
		if (commenceDischargeDt == null) {
			if (other.commenceDischargeDt != null)
				return false;
		} else if (!commenceDischargeDt.equals(other.commenceDischargeDt))
			return false;
		if (commenceLoadDt == null) {
			if (other.commenceLoadDt != null)
				return false;
		} else if (!commenceLoadDt.equals(other.commenceLoadDt))
			return false;
		if (completionDischargeDt == null) {
			if (other.completionDischargeDt != null)
				return false;
		} else if (!completionDischargeDt.equals(other.completionDischargeDt))
			return false;
		if (completionLoadDt == null) {
			if (other.completionLoadDt != null)
				return false;
		} else if (!completionLoadDt.equals(other.completionLoadDt))
			return false;
		if (counterpartContactNum != other.counterpartContactNum)
			return false;
		if (createInvoiceInd == null) {
			if (other.createInvoiceInd != null)
				return false;
		} else if (!createInvoiceInd.equals(other.createInvoiceInd))
			return false;
		if (customInvoiceFormatCd == null) {
			if (other.customInvoiceFormatCd != null)
				return false;
		} else if (!customInvoiceFormatCd.equals(other.customInvoiceFormatCd))
			return false;
		if (deliveryActiveStatusInd == null) {
			if (other.deliveryActiveStatusInd != null)
				return false;
		} else if (!deliveryActiveStatusInd
				.equals(other.deliveryActiveStatusInd))
			return false;
		if (deliveryStatusInd != other.deliveryStatusInd)
			return false;
		if (deliveryTypeInd != other.deliveryTypeInd)
			return false;
		if (dischargeCargoNum != other.dischargeCargoNum)
			return false;
		if (dischargeEquipmentNum != other.dischargeEquipmentNum)
			return false;
		if (dischargeLocationNum != other.dischargeLocationNum)
			return false;
		if (dischargeMotNum != other.dischargeMotNum)
			return false;
		if (dischargePortLocationNum != other.dischargePortLocationNum)
			return false;
		if (docTemplateCd == null) {
			if (other.docTemplateCd != null)
				return false;
		} else if (!docTemplateCd.equals(other.docTemplateCd))
			return false;
		if (docTypeCd == null) {
			if (other.docTypeCd != null)
				return false;
		} else if (!docTypeCd.equals(other.docTypeCd))
			return false;
		if (etaDischargeDt == null) {
			if (other.etaDischargeDt != null)
				return false;
		} else if (!etaDischargeDt.equals(other.etaDischargeDt))
			return false;
		if (etaLoadDt == null) {
			if (other.etaLoadDt != null)
				return false;
		} else if (!etaLoadDt.equals(other.etaLoadDt))
			return false;
		if (finalizedDt == null) {
			if (other.finalizedDt != null)
				return false;
		} else if (!finalizedDt.equals(other.finalizedDt))
			return false;
		if (hasAttachmentInd != other.hasAttachmentInd)
			return false;
		if (initiatorInd != other.initiatorInd)
			return false;
		if (internalCoNum == null) {
			if (other.internalCoNum != null)
				return false;
		} else if (!internalCoNum.equals(other.internalCoNum))
			return false;
		if (internalContactNum != other.internalContactNum)
			return false;
		if (invoiceDt == null) {
			if (other.invoiceDt != null)
				return false;
		} else if (!invoiceDt.equals(other.invoiceDt))
			return false;
		if (invoiceFormatTypeInd != other.invoiceFormatTypeInd)
			return false;
		if (languageCd == null) {
			if (other.languageCd != null)
				return false;
		} else if (!languageCd.equals(other.languageCd))
			return false;
		if (lastModifyDt == null) {
			if (other.lastModifyDt != null)
				return false;
		} else if (!lastModifyDt.equals(other.lastModifyDt))
			return false;
		if (liquidateDt == null) {
			if (other.liquidateDt != null)
				return false;
		} else if (!liquidateDt.equals(other.liquidateDt))
			return false;
		if (loadCargoNum != other.loadCargoNum)
			return false;
		if (loadEquipmentNum != other.loadEquipmentNum)
			return false;
		if (loadLocationNum != other.loadLocationNum)
			return false;
		if (loadMotNum != other.loadMotNum)
			return false;
		if (loadPortLocationNum != other.loadPortLocationNum)
			return false;
		if (lockNum != other.lockNum)
			return false;
		if (matchAtInd != other.matchAtInd)
			return false;
		if (matchDesc == null) {
			if (other.matchDesc != null)
				return false;
		} else if (!matchDesc.equals(other.matchDesc))
			return false;
		if (matchDescNl == null) {
			if (other.matchDescNl != null)
				return false;
		} else if (!matchDescNl.equals(other.matchDescNl))
			return false;
		if (matchDt == null) {
			if (other.matchDt != null)
				return false;
		} else if (!matchDt.equals(other.matchDt))
			return false;
		if (matchPrice == null) {
			if (other.matchPrice != null)
				return false;
		} else if (!matchPrice.equals(other.matchPrice))
			return false;
		if (matchPriceCurrCd == null) {
			if (other.matchPriceCurrCd != null)
				return false;
		} else if (!matchPriceCurrCd.equals(other.matchPriceCurrCd))
			return false;
		if (matchPriceUomCd == null) {
			if (other.matchPriceUomCd != null)
				return false;
		} else if (!matchPriceUomCd.equals(other.matchPriceUomCd))
			return false;
		if (matchSettlementCurrCd == null) {
			if (other.matchSettlementCurrCd != null)
				return false;
		} else if (!matchSettlementCurrCd.equals(other.matchSettlementCurrCd))
			return false;
		if (mktBasisDiff == null) {
			if (other.mktBasisDiff != null)
				return false;
		} else if (!mktBasisDiff.equals(other.mktBasisDiff))
			return false;
		if (mktPriceLockDt == null) {
			if (other.mktPriceLockDt != null)
				return false;
		} else if (!mktPriceLockDt.equals(other.mktPriceLockDt))
			return false;
		if (mktPriceLockDtInd == null) {
			if (other.mktPriceLockDtInd != null)
				return false;
		} else if (!mktPriceLockDtInd.equals(other.mktPriceLockDtInd))
			return false;
		if (modifyPersonNum != other.modifyPersonNum)
			return false;
		if (motNum != other.motNum)
			return false;
		if (motTypeInd == null) {
			if (other.motTypeInd != null)
				return false;
		} else if (!motTypeInd.equals(other.motTypeInd))
			return false;
		if (mtmFwdCurveNum == null) {
			if (other.mtmFwdCurveNum != null)
				return false;
		} else if (!mtmFwdCurveNum.equals(other.mtmFwdCurveNum))
			return false;
		if (noteNum != other.noteNum)
			return false;
		if (obligationMatchNum != other.obligationMatchNum)
			return false;
		if (operatorPersonNum == null) {
			if (other.operatorPersonNum != null)
				return false;
		} else if (!operatorPersonNum.equals(other.operatorPersonNum))
			return false;
		if (ourRef == null) {
			if (other.ourRef != null)
				return false;
		} else if (!ourRef.equals(other.ourRef))
			return false;
		if (paymentDueDt == null) {
			if (other.paymentDueDt != null)
				return false;
		} else if (!paymentDueDt.equals(other.paymentDueDt))
			return false;
		if (pipelineCycleCd == null) {
			if (other.pipelineCycleCd != null)
				return false;
		} else if (!pipelineCycleCd.equals(other.pipelineCycleCd))
			return false;
		if (pumpDt == null) {
			if (other.pumpDt != null)
				return false;
		} else if (!pumpDt.equals(other.pumpDt))
			return false;
		if (sequence == null) {
			if (other.sequence != null)
				return false;
		} else if (!sequence.equals(other.sequence))
			return false;
		if (theirRef == null) {
			if (other.theirRef != null)
				return false;
		} else if (!theirRef.equals(other.theirRef))
			return false;
		if (titleTransferLocationNum != other.titleTransferLocationNum)
			return false;
		if (tow == null) {
			if (other.tow != null)
				return false;
		} else if (!tow.equals(other.tow))
			return false;
		if (txlPsNum != other.txlPsNum)
			return false;
		if (ventureCd == null) {
			if (other.ventureCd != null)
				return false;
		} else if (!ventureCd.equals(other.ventureCd))
			return false;
		return true;
	}
	
}
