package com.mercon.entities;

// Generated Jul 30, 2014 12:30:09 PM by Hibernate Tools 3.4.0.CR1

/**
 * VopsTransferUdf generated by hbm2java
 */
public class VopsTransferUdf implements java.io.Serializable {

	private VopsTransferUdfId id;

	public VopsTransferUdf() {
	}

	public VopsTransferUdf(VopsTransferUdfId id) {
		this.id = id;
	}

	public VopsTransferUdfId getId() {
		return this.id;
	}

	public void setId(VopsTransferUdfId id) {
		this.id = id;
	}

}
