package com.mercon.entities;

// Generated Aug 7, 2014 10:54:12 AM by Hibernate Tools 3.4.0.CR1

/**
 * VopsObligationHdr generated by hbm2java
 */
public class VopsObligationHdr implements java.io.Serializable {

	/**
	 * Serial ID
	 */
	private static final long serialVersionUID = 4999912551903229563L;

	private VopsObligationHdrId id;

	public VopsObligationHdr() {
	}

	public VopsObligationHdr(VopsObligationHdrId id) {
		this.id = id;
	}

	public VopsObligationHdrId getId() {
		return this.id;
	}

	public void setId(VopsObligationHdrId id) {
		this.id = id;
	}

}
