package com.mercon.entities;

// Generated Jul 30, 2014 12:30:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * VopsTransferUdfId generated by hbm2java
 */
public class VopsTransferUdfId implements java.io.Serializable {

	private int udfNum;
	private String udfCd;
	private String udfValue;
	private int transferNum;
	private int modifyPersonNum;
	private Date lastModifyDt;
	private int lockNum;
	private int toFromInd;

	public VopsTransferUdfId() {
	}

	public VopsTransferUdfId(int udfNum, String udfCd, int transferNum,
			int modifyPersonNum, Date lastModifyDt, int lockNum, int toFromInd) {
		this.udfNum = udfNum;
		this.udfCd = udfCd;
		this.transferNum = transferNum;
		this.modifyPersonNum = modifyPersonNum;
		this.lastModifyDt = lastModifyDt;
		this.lockNum = lockNum;
		this.toFromInd = toFromInd;
	}

	public VopsTransferUdfId(int udfNum, String udfCd, String udfValue,
			int transferNum, int modifyPersonNum, Date lastModifyDt,
			int lockNum, int toFromInd) {
		this.udfNum = udfNum;
		this.udfCd = udfCd;
		this.udfValue = udfValue;
		this.transferNum = transferNum;
		this.modifyPersonNum = modifyPersonNum;
		this.lastModifyDt = lastModifyDt;
		this.lockNum = lockNum;
		this.toFromInd = toFromInd;
	}

	public int getUdfNum() {
		return this.udfNum;
	}

	public void setUdfNum(int udfNum) {
		this.udfNum = udfNum;
	}

	public String getUdfCd() {
		return this.udfCd;
	}

	public void setUdfCd(String udfCd) {
		this.udfCd = udfCd;
	}

	public String getUdfValue() {
		return this.udfValue;
	}

	public void setUdfValue(String udfValue) {
		this.udfValue = udfValue;
	}

	public int getTransferNum() {
		return this.transferNum;
	}

	public void setTransferNum(int transferNum) {
		this.transferNum = transferNum;
	}

	public int getModifyPersonNum() {
		return this.modifyPersonNum;
	}

	public void setModifyPersonNum(int modifyPersonNum) {
		this.modifyPersonNum = modifyPersonNum;
	}

	public Date getLastModifyDt() {
		return this.lastModifyDt;
	}

	public void setLastModifyDt(Date lastModifyDt) {
		this.lastModifyDt = lastModifyDt;
	}

	public int getLockNum() {
		return this.lockNum;
	}

	public void setLockNum(int lockNum) {
		this.lockNum = lockNum;
	}

	public int getToFromInd() {
		return this.toFromInd;
	}

	public void setToFromInd(int toFromInd) {
		this.toFromInd = toFromInd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VopsTransferUdfId))
			return false;
		VopsTransferUdfId castOther = (VopsTransferUdfId) other;

		return (this.getUdfNum() == castOther.getUdfNum())
				&& ((this.getUdfCd() == castOther.getUdfCd()) || (this
						.getUdfCd() != null && castOther.getUdfCd() != null && this
						.getUdfCd().equals(castOther.getUdfCd())))
				&& ((this.getUdfValue() == castOther.getUdfValue()) || (this
						.getUdfValue() != null
						&& castOther.getUdfValue() != null && this
						.getUdfValue().equals(castOther.getUdfValue())))
				&& (this.getTransferNum() == castOther.getTransferNum())
				&& (this.getModifyPersonNum() == castOther.getModifyPersonNum())
				&& ((this.getLastModifyDt() == castOther.getLastModifyDt()) || (this
						.getLastModifyDt() != null
						&& castOther.getLastModifyDt() != null && this
						.getLastModifyDt().equals(castOther.getLastModifyDt())))
				&& (this.getLockNum() == castOther.getLockNum())
				&& (this.getToFromInd() == castOther.getToFromInd());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUdfNum();
		result = 37 * result
				+ (getUdfCd() == null ? 0 : this.getUdfCd().hashCode());
		result = 37 * result
				+ (getUdfValue() == null ? 0 : this.getUdfValue().hashCode());
		result = 37 * result + this.getTransferNum();
		result = 37 * result + this.getModifyPersonNum();
		result = 37
				* result
				+ (getLastModifyDt() == null ? 0 : this.getLastModifyDt()
						.hashCode());
		result = 37 * result + this.getLockNum();
		result = 37 * result + this.getToFromInd();
		return result;
	}

}
