package com.mercon.entities;

// Generated Jan 22, 2014 3:52:54 PM by Hibernate Tools 3.4.0.CR1

/**
 * Vpermission generated by hbm2java
 */
public class Vpermission implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private VpermissionId id;

	public Vpermission() {
	}

	public Vpermission(VpermissionId id) {
		this.id = id;
	}

	public VpermissionId getId() {
		return this.id;
	}

	public void setId(VpermissionId id) {
		this.id = id;
	}

}
