package com.mercon.entities;

// Generated Apr 30, 2014 11:49:17 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.validation.constraints.Digits;

/**
 * VtradeInputId generated by hbm2java
 */
public class VtradeInputId implements java.io.Serializable {

	/**
	 * Serial ID
	 */
	private static final long serialVersionUID = -9097066713335465499L;
	
	private int tradeNum;
	private Integer traderNum;
	private Integer internalCompanyNum;
	private Integer counterpartCompanyNum;
	private Date tradeDt;
	private int brokerCompanyNum;
	private BigDecimal commissionAmt;
	private String commCurrCd;
	private String commUomCd;
	private Short buySellInd;
	private String buySell;
	private String cmdtyCd;
	private Integer cropYear;
	private BigDecimal tradeQty;
	private String contractUomCd;
	private String deliveryTermCd;
	private Integer location;
	private int destinaton;
	private int country;
	private String delivPeriodCd;
	private Integer quoteDefNum;
	private Integer exchContractNum;
	private BigDecimal fixedPrice;
	private String priceCurrCd;
	private String priceUomCd;
	private BigDecimal fobPrice;
	private String fobCurrency;
	private String fobUom;
	private String settlePaymentTermCd;
	private String settlementCurrCd;
	private String settlementUomCd;
	private Date actionDt;
	private int priceQuoteDefNum;
	private BigDecimal premium;
	private String premiumCurrCd;
	private String premiumUomCd;
	private BigDecimal actionPrice;
	private String actionPriceCurrCd;
	private String actionPriceUomCd;
	private BigDecimal actionQty;
	private BigDecimal actionLotQty;
	private String actionQtyUomCd;
	private String dealId;
	private String dealId2;
	private String noteText;
	private String notePreview;
	private String deliveryTerms;
	private String weightTerms;
	private String approvalTerms;
	private String bzCertPremium;
	private String bzCertStatus;
	private String bzChargedInterest;
	private String bzCollatScheme;
	private String bzCreditAssignee;
	private String bzExchCtrNum;
	private String bzFarmNeigh;
	private String bzFarmRegion;
	private String bzFarmState;
	private String bzFobbasis;
	private String bzFormalReturnDat;
	private String bzFrmlztRlseDate;
	private String bzFxhedgingLevel;
	private String bzGuarantor1st;
	private String bzGuarantor2nd;
	private String bzIr1recepDat;
	private String bzIr1ProductHec;
	private String bzIr1RiskSituat;
	private String bzPymtAnticip;
	private String bzShareholderdsbmt;
	private String bzTradeBasis;
	private String bzTradeType;
	private String currentPotype;
	private String fxfixedRate;
	private String potype;
	private String bzFinRatio;
	private String bzAnuentePrimario;
	private String bzAnuenteSecundario;
	private String bzFixationDeadline;
	private String bzWacc;
	private String bzLgfixedPriceSao;
	private String bzThirdpartydsbmt;
	private String bzCollatRecepDate;
	private String bzShareholDsbmtDt;
	private String bz3partyDsbmtDt;
	private String bzExpDiffFobbas;
	private String bzDrdiffvsNysao;
	private String bzActualAnticAmt;
	private String bzBcdiffTrade;
	private String bzBcdiffFob;
	private String bzDeliveryWhse;
	private String bzFxexposure;
	private String bzFxhedgingdate;
	private String bzFxverification;
	private String bzFxhedgingCounte;
	private String gtDeliveryPlace;
	private String gtLndCostFrom;
	private String gtLndCostTo;
	private String gtMgtprice;
	private String gtPreparacion;
	private String gtPymtCondition;
	private String gtShpmtCostFrom;
	private String gtShpmtCostTo;
	private String gtShpmtValue;
	private String gtTradeCost;
	private String gtRealCost;
	private String gtNetDiffBuy;
	private String gtZarCost;
	private String gtSubpCost;
	private BigDecimal multiplier;
	private String countryName;
	private String counterpart;
	private String destination;
	private String riskPeriodCd;
	private short tradeStatusInd;
	private String specCd;
	@Digits(integer = 15, fraction = 2)
	private BigDecimal openQty;
	@Digits(integer = 15, fraction = 2)
	private BigDecimal scheduledQty;
	private int obligationNum;
	private int obligationDetailNum;
	private BigDecimal strategyNum;
	private BigDecimal termNum;
	private String termSectionCd;
	private BigDecimal companyNum;
	private Date laycanStartDt;
	private Date laycanEndDt;
	private BigDecimal delivQty;
	private String delivUomCd;
	private BigDecimal price;
	private Short airVacInd;
	private Integer mtmFwdCurveNum;
	private Short customsDutyStatusInd;
	private Short schConfExecutedInd;
	private Short pricingStatusInd;
	private Short futuresPricingStatusInd;
	private Short basisPricingStatusInd;
	private Integer originLocNum;
	private Short obligationTypeInd;
	
	public VtradeInputId() {
	}

	public VtradeInputId(int tradeNum, int brokerCompanyNum,
			BigDecimal commissionAmt, String commCurrCd, String commUomCd,
			String buySell, int destinaton, int country, String delivPeriodCd,
			BigDecimal fobPrice, String fobCurrency, String fobUom,
			Date actionDt, int priceQuoteDefNum, BigDecimal premium,
			String premiumCurrCd, String premiumUomCd, BigDecimal actionPrice,
			String actionPriceCurrCd, String actionPriceUomCd,
			BigDecimal actionQty, BigDecimal actionLotQty,
			String actionQtyUomCd, String dealId, String dealId2,
			String notePreview, String deliveryTerms, String weightTerms,
			String approvalTerms, String bzCertPremium, String bzCertStatus,
			String bzChargedInterest, String bzCollatScheme,
			String bzCreditAssignee, String bzExchCtrNum, String bzFarmNeigh,
			String bzFarmRegion, String bzFarmState, String bzFobbasis,
			String bzFormalReturnDat, String bzFrmlztRlseDate,
			String bzFxhedgingLevel, String bzGuarantor1st,
			String bzGuarantor2nd, String bzIr1recepDat,
			String bzIr1ProductHec, String bzIr1RiskSituat,
			String bzPymtAnticip, String bzShareholderdsbmt,
			String bzTradeBasis, String bzTradeType, String currentPotype,
			String fxfixedRate, String potype, String bzFinRatio,
			String bzAnuentePrimario, String bzAnuenteSecundario,
			String bzFixationDeadline, String bzWacc, String bzLgfixedPriceSao,
			String bzThirdpartydsbmt, String bzCollatRecepDate,
			String bzShareholDsbmtDt, String bz3partyDsbmtDt,
			String bzExpDiffFobbas, String bzDrdiffvsNysao,
			String bzActualAnticAmt, String bzBcdiffTrade, String bzBcdiffFob,
			String bzDeliveryWhse, String bzFxexposure, String bzFxhedgingdate,
			String bzFxverification, String bzFxhedgingCounte,
			String gtDeliveryPlace, String gtLndCostFrom, String gtLndCostTo,
			String gtMgtprice, String gtPreparacion, String gtPymtCondition,
			String gtShpmtCostFrom, String gtShpmtCostTo, String gtShpmtValue,
			String gtTradeCost, String gtRealCost, String gtNetDiffBuy,
			String gtZarCost, String gtSubpCost, BigDecimal multiplier,
			String countryName, String destination, String riskPeriodCd,
			short tradeStatusInd, BigDecimal openQty) {
		this.tradeNum = tradeNum;
		this.brokerCompanyNum = brokerCompanyNum;
		this.commissionAmt = commissionAmt;
		this.commCurrCd = commCurrCd;
		this.commUomCd = commUomCd;
		this.buySell = buySell;
		this.destinaton = destinaton;
		this.country = country;
		this.delivPeriodCd = delivPeriodCd;
		this.fobPrice = fobPrice;
		this.fobCurrency = fobCurrency;
		this.fobUom = fobUom;
		this.actionDt = actionDt;
		this.priceQuoteDefNum = priceQuoteDefNum;
		this.premium = premium;
		this.premiumCurrCd = premiumCurrCd;
		this.premiumUomCd = premiumUomCd;
		this.actionPrice = actionPrice;
		this.actionPriceCurrCd = actionPriceCurrCd;
		this.actionPriceUomCd = actionPriceUomCd;
		this.actionQty = actionQty;
		this.actionLotQty = actionLotQty;
		this.actionQtyUomCd = actionQtyUomCd;
		this.dealId = dealId;
		this.dealId2 = dealId2;
		this.notePreview = notePreview;
		this.deliveryTerms = deliveryTerms;
		this.weightTerms = weightTerms;
		this.approvalTerms = approvalTerms;
		this.bzCertPremium = bzCertPremium;
		this.bzCertStatus = bzCertStatus;
		this.bzChargedInterest = bzChargedInterest;
		this.bzCollatScheme = bzCollatScheme;
		this.bzCreditAssignee = bzCreditAssignee;
		this.bzExchCtrNum = bzExchCtrNum;
		this.bzFarmNeigh = bzFarmNeigh;
		this.bzFarmRegion = bzFarmRegion;
		this.bzFarmState = bzFarmState;
		this.bzFobbasis = bzFobbasis;
		this.bzFormalReturnDat = bzFormalReturnDat;
		this.bzFrmlztRlseDate = bzFrmlztRlseDate;
		this.bzFxhedgingLevel = bzFxhedgingLevel;
		this.bzGuarantor1st = bzGuarantor1st;
		this.bzGuarantor2nd = bzGuarantor2nd;
		this.bzIr1recepDat = bzIr1recepDat;
		this.bzIr1ProductHec = bzIr1ProductHec;
		this.bzIr1RiskSituat = bzIr1RiskSituat;
		this.bzPymtAnticip = bzPymtAnticip;
		this.bzShareholderdsbmt = bzShareholderdsbmt;
		this.bzTradeBasis = bzTradeBasis;
		this.bzTradeType = bzTradeType;
		this.currentPotype = currentPotype;
		this.fxfixedRate = fxfixedRate;
		this.potype = potype;
		this.bzFinRatio = bzFinRatio;
		this.bzAnuentePrimario = bzAnuentePrimario;
		this.bzAnuenteSecundario = bzAnuenteSecundario;
		this.bzFixationDeadline = bzFixationDeadline;
		this.bzWacc = bzWacc;
		this.bzLgfixedPriceSao = bzLgfixedPriceSao;
		this.bzThirdpartydsbmt = bzThirdpartydsbmt;
		this.bzCollatRecepDate = bzCollatRecepDate;
		this.bzShareholDsbmtDt = bzShareholDsbmtDt;
		this.bz3partyDsbmtDt = bz3partyDsbmtDt;
		this.bzExpDiffFobbas = bzExpDiffFobbas;
		this.bzDrdiffvsNysao = bzDrdiffvsNysao;
		this.bzActualAnticAmt = bzActualAnticAmt;
		this.bzBcdiffTrade = bzBcdiffTrade;
		this.bzBcdiffFob = bzBcdiffFob;
		this.bzDeliveryWhse = bzDeliveryWhse;
		this.bzFxexposure = bzFxexposure;
		this.bzFxhedgingdate = bzFxhedgingdate;
		this.bzFxverification = bzFxverification;
		this.bzFxhedgingCounte = bzFxhedgingCounte;
		this.gtDeliveryPlace = gtDeliveryPlace;
		this.gtLndCostFrom = gtLndCostFrom;
		this.gtLndCostTo = gtLndCostTo;
		this.gtMgtprice = gtMgtprice;
		this.gtPreparacion = gtPreparacion;
		this.gtPymtCondition = gtPymtCondition;
		this.gtShpmtCostFrom = gtShpmtCostFrom;
		this.gtShpmtCostTo = gtShpmtCostTo;
		this.gtShpmtValue = gtShpmtValue;
		this.gtTradeCost = gtTradeCost;
		this.gtRealCost = gtRealCost;
		this.gtNetDiffBuy = gtNetDiffBuy;
		this.gtZarCost = gtZarCost;
		this.gtSubpCost = gtSubpCost;
		this.multiplier = multiplier;
		this.countryName = countryName;
		this.destination = destination;
		this.riskPeriodCd = riskPeriodCd;
		this.tradeStatusInd = tradeStatusInd;
		this.openQty = openQty;
	}

	public VtradeInputId(int tradeNum, Integer traderNum,
			Integer internalCompanyNum, Integer counterpartCompanyNum,
			Date tradeDt, int brokerCompanyNum, BigDecimal commissionAmt,
			String commCurrCd, String commUomCd, Short buySellInd,
			String buySell, String cmdtyCd, Integer cropYear,
			BigDecimal tradeQty, String contractUomCd, String deliveryTermCd,
			Integer location, int destinaton, int country,
			String delivPeriodCd, Integer quoteDefNum, Integer exchContractNum,
			BigDecimal fixedPrice, String priceCurrCd, String priceUomCd,
			BigDecimal fobPrice, String fobCurrency, String fobUom,
			String settlePaymentTermCd, String settlementCurrCd,
			String settlementUomCd, Date actionDt, int priceQuoteDefNum,
			BigDecimal premium, String premiumCurrCd, String premiumUomCd,
			BigDecimal actionPrice, String actionPriceCurrCd,
			String actionPriceUomCd, BigDecimal actionQty,
			BigDecimal actionLotQty, String actionQtyUomCd, String dealId,
			String dealId2, String noteText, String notePreview,
			String deliveryTerms, String weightTerms, String approvalTerms,
			String bzCertPremium, String bzCertStatus,
			String bzChargedInterest, String bzCollatScheme,
			String bzCreditAssignee, String bzExchCtrNum, String bzFarmNeigh,
			String bzFarmRegion, String bzFarmState, String bzFobbasis,
			String bzFormalReturnDat, String bzFrmlztRlseDate,
			String bzFxhedgingLevel, String bzGuarantor1st,
			String bzGuarantor2nd, String bzIr1recepDat,
			String bzIr1ProductHec, String bzIr1RiskSituat,
			String bzPymtAnticip, String bzShareholderdsbmt,
			String bzTradeBasis, String bzTradeType, String currentPotype,
			String fxfixedRate, String potype, String bzFinRatio,
			String bzAnuentePrimario, String bzAnuenteSecundario,
			String bzFixationDeadline, String bzWacc, String bzLgfixedPriceSao,
			String bzThirdpartydsbmt, String bzCollatRecepDate,
			String bzShareholDsbmtDt, String bz3partyDsbmtDt,
			String bzExpDiffFobbas, String bzDrdiffvsNysao,
			String bzActualAnticAmt, String bzBcdiffTrade, String bzBcdiffFob,
			String bzDeliveryWhse, String bzFxexposure, String bzFxhedgingdate,
			String bzFxverification, String bzFxhedgingCounte,
			String gtDeliveryPlace, String gtLndCostFrom, String gtLndCostTo,
			String gtMgtprice, String gtPreparacion, String gtPymtCondition,
			String gtShpmtCostFrom, String gtShpmtCostTo, String gtShpmtValue,
			String gtTradeCost, String gtRealCost, String gtNetDiffBuy,
			String gtZarCost, String gtSubpCost, BigDecimal multiplier,
			String countryName, String counterpart, String destination,
			String riskPeriodCd, short tradeStatusInd, String specCd, BigDecimal openQty) {
		this.tradeNum = tradeNum;
		this.traderNum = traderNum;
		this.internalCompanyNum = internalCompanyNum;
		this.counterpartCompanyNum = counterpartCompanyNum;
		this.tradeDt = tradeDt;
		this.brokerCompanyNum = brokerCompanyNum;
		this.commissionAmt = commissionAmt;
		this.commCurrCd = commCurrCd;
		this.commUomCd = commUomCd;
		this.buySellInd = buySellInd;
		this.buySell = buySell;
		this.cmdtyCd = cmdtyCd;
		this.cropYear = cropYear;
		this.tradeQty = tradeQty;
		this.contractUomCd = contractUomCd;
		this.deliveryTermCd = deliveryTermCd;
		this.location = location;
		this.destinaton = destinaton;
		this.country = country;
		this.delivPeriodCd = delivPeriodCd;
		this.quoteDefNum = quoteDefNum;
		this.exchContractNum = exchContractNum;
		this.fixedPrice = fixedPrice;
		this.priceCurrCd = priceCurrCd;
		this.priceUomCd = priceUomCd;
		this.fobPrice = fobPrice;
		this.fobCurrency = fobCurrency;
		this.fobUom = fobUom;
		this.settlePaymentTermCd = settlePaymentTermCd;
		this.settlementCurrCd = settlementCurrCd;
		this.settlementUomCd = settlementUomCd;
		this.actionDt = actionDt;
		this.priceQuoteDefNum = priceQuoteDefNum;
		this.premium = premium;
		this.premiumCurrCd = premiumCurrCd;
		this.premiumUomCd = premiumUomCd;
		this.actionPrice = actionPrice;
		this.actionPriceCurrCd = actionPriceCurrCd;
		this.actionPriceUomCd = actionPriceUomCd;
		this.actionQty = actionQty;
		this.actionLotQty = actionLotQty;
		this.actionQtyUomCd = actionQtyUomCd;
		this.dealId = dealId;
		this.dealId2 = dealId2;
		this.noteText = noteText;
		this.notePreview = notePreview;
		this.deliveryTerms = deliveryTerms;
		this.weightTerms = weightTerms;
		this.approvalTerms = approvalTerms;
		this.bzCertPremium = bzCertPremium;
		this.bzCertStatus = bzCertStatus;
		this.bzChargedInterest = bzChargedInterest;
		this.bzCollatScheme = bzCollatScheme;
		this.bzCreditAssignee = bzCreditAssignee;
		this.bzExchCtrNum = bzExchCtrNum;
		this.bzFarmNeigh = bzFarmNeigh;
		this.bzFarmRegion = bzFarmRegion;
		this.bzFarmState = bzFarmState;
		this.bzFobbasis = bzFobbasis;
		this.bzFormalReturnDat = bzFormalReturnDat;
		this.bzFrmlztRlseDate = bzFrmlztRlseDate;
		this.bzFxhedgingLevel = bzFxhedgingLevel;
		this.bzGuarantor1st = bzGuarantor1st;
		this.bzGuarantor2nd = bzGuarantor2nd;
		this.bzIr1recepDat = bzIr1recepDat;
		this.bzIr1ProductHec = bzIr1ProductHec;
		this.bzIr1RiskSituat = bzIr1RiskSituat;
		this.bzPymtAnticip = bzPymtAnticip;
		this.bzShareholderdsbmt = bzShareholderdsbmt;
		this.bzTradeBasis = bzTradeBasis;
		this.bzTradeType = bzTradeType;
		this.currentPotype = currentPotype;
		this.fxfixedRate = fxfixedRate;
		this.potype = potype;
		this.bzFinRatio = bzFinRatio;
		this.bzAnuentePrimario = bzAnuentePrimario;
		this.bzAnuenteSecundario = bzAnuenteSecundario;
		this.bzFixationDeadline = bzFixationDeadline;
		this.bzWacc = bzWacc;
		this.bzLgfixedPriceSao = bzLgfixedPriceSao;
		this.bzThirdpartydsbmt = bzThirdpartydsbmt;
		this.bzCollatRecepDate = bzCollatRecepDate;
		this.bzShareholDsbmtDt = bzShareholDsbmtDt;
		this.bz3partyDsbmtDt = bz3partyDsbmtDt;
		this.bzExpDiffFobbas = bzExpDiffFobbas;
		this.bzDrdiffvsNysao = bzDrdiffvsNysao;
		this.bzActualAnticAmt = bzActualAnticAmt;
		this.bzBcdiffTrade = bzBcdiffTrade;
		this.bzBcdiffFob = bzBcdiffFob;
		this.bzDeliveryWhse = bzDeliveryWhse;
		this.bzFxexposure = bzFxexposure;
		this.bzFxhedgingdate = bzFxhedgingdate;
		this.bzFxverification = bzFxverification;
		this.bzFxhedgingCounte = bzFxhedgingCounte;
		this.gtDeliveryPlace = gtDeliveryPlace;
		this.gtLndCostFrom = gtLndCostFrom;
		this.gtLndCostTo = gtLndCostTo;
		this.gtMgtprice = gtMgtprice;
		this.gtPreparacion = gtPreparacion;
		this.gtPymtCondition = gtPymtCondition;
		this.gtShpmtCostFrom = gtShpmtCostFrom;
		this.gtShpmtCostTo = gtShpmtCostTo;
		this.gtShpmtValue = gtShpmtValue;
		this.gtTradeCost = gtTradeCost;
		this.gtRealCost = gtRealCost;
		this.gtNetDiffBuy = gtNetDiffBuy;
		this.gtZarCost = gtZarCost;
		this.gtSubpCost = gtSubpCost;
		this.multiplier = multiplier;
		this.countryName = countryName;
		this.counterpart = counterpart;
		this.destination = destination;
		this.riskPeriodCd = riskPeriodCd;
		this.tradeStatusInd = tradeStatusInd;
		this.specCd = specCd;
		this.openQty = openQty;
	}
	
	

	public int getTradeNum() {
		return this.tradeNum;
	}

	public void setTradeNum(int tradeNum) {
		this.tradeNum = tradeNum;
	}

	public Integer getTraderNum() {
		return this.traderNum;
	}

	public void setTraderNum(Integer traderNum) {
		this.traderNum = traderNum;
	}

	public Integer getInternalCompanyNum() {
		return this.internalCompanyNum;
	}

	public void setInternalCompanyNum(Integer internalCompanyNum) {
		this.internalCompanyNum = internalCompanyNum;
	}

	public Integer getCounterpartCompanyNum() {
		return this.counterpartCompanyNum;
	}

	public void setCounterpartCompanyNum(Integer counterpartCompanyNum) {
		this.counterpartCompanyNum = counterpartCompanyNum;
	}

	public Date getTradeDt() {
		return this.tradeDt;
	}

	public void setTradeDt(Date tradeDt) {
		this.tradeDt = tradeDt;
	}

	public int getBrokerCompanyNum() {
		return this.brokerCompanyNum;
	}

	public void setBrokerCompanyNum(int brokerCompanyNum) {
		this.brokerCompanyNum = brokerCompanyNum;
	}

	public BigDecimal getCommissionAmt() {
		return this.commissionAmt;
	}

	public void setCommissionAmt(BigDecimal commissionAmt) {
		this.commissionAmt = commissionAmt;
	}

	public String getCommCurrCd() {
		return this.commCurrCd;
	}

	public void setCommCurrCd(String commCurrCd) {
		this.commCurrCd = commCurrCd;
	}

	public String getCommUomCd() {
		return this.commUomCd;
	}

	public void setCommUomCd(String commUomCd) {
		this.commUomCd = commUomCd;
	}

	public Short getBuySellInd() {
		return this.buySellInd;
	}

	public void setBuySellInd(Short buySellInd) {
		this.buySellInd = buySellInd;
	}

	public String getBuySell() {
		return this.buySell;
	}

	public void setBuySell(String buySell) {
		this.buySell = buySell;
	}

	public String getCmdtyCd() {
		return this.cmdtyCd;
	}

	public void setCmdtyCd(String cmdtyCd) {
		this.cmdtyCd = cmdtyCd;
	}

	public Integer getCropYear() {
		return this.cropYear;
	}

	public void setCropYear(Integer cropYear) {
		this.cropYear = cropYear;
	}

	public BigDecimal getTradeQty() {
		return this.tradeQty;
	}

	public void setTradeQty(BigDecimal tradeQty) {
		this.tradeQty = tradeQty;
	}

	public String getContractUomCd() {
		return this.contractUomCd;
	}

	public void setContractUomCd(String contractUomCd) {
		this.contractUomCd = contractUomCd;
	}

	public String getDeliveryTermCd() {
		return this.deliveryTermCd;
	}

	public void setDeliveryTermCd(String deliveryTermCd) {
		this.deliveryTermCd = deliveryTermCd;
	}

	public Integer getLocation() {
		return this.location;
	}

	public void setLocation(Integer location) {
		this.location = location;
	}

	public int getDestinaton() {
		return this.destinaton;
	}

	public void setDestinaton(int destinaton) {
		this.destinaton = destinaton;
	}

	public int getCountry() {
		return this.country;
	}

	public void setCountry(int country) {
		this.country = country;
	}

	public String getDelivPeriodCd() {
		return this.delivPeriodCd;
	}

	public void setDelivPeriodCd(String delivPeriodCd) {
		this.delivPeriodCd = delivPeriodCd;
	}

	public Integer getQuoteDefNum() {
		return this.quoteDefNum;
	}

	public void setQuoteDefNum(Integer quoteDefNum) {
		this.quoteDefNum = quoteDefNum;
	}

	public Integer getExchContractNum() {
		return this.exchContractNum;
	}

	public void setExchContractNum(Integer exchContractNum) {
		this.exchContractNum = exchContractNum;
	}

	public BigDecimal getFixedPrice() {
		return this.fixedPrice;
	}

	public void setFixedPrice(BigDecimal fixedPrice) {
		this.fixedPrice = fixedPrice;
	}

	public String getPriceCurrCd() {
		return this.priceCurrCd;
	}

	public void setPriceCurrCd(String priceCurrCd) {
		this.priceCurrCd = priceCurrCd;
	}

	public String getPriceUomCd() {
		return this.priceUomCd;
	}

	public void setPriceUomCd(String priceUomCd) {
		this.priceUomCd = priceUomCd;
	}

	public BigDecimal getFobPrice() {
		return this.fobPrice;
	}

	public void setFobPrice(BigDecimal fobPrice) {
		this.fobPrice = fobPrice;
	}

	public String getFobCurrency() {
		return this.fobCurrency;
	}

	public void setFobCurrency(String fobCurrency) {
		this.fobCurrency = fobCurrency;
	}

	public String getFobUom() {
		return this.fobUom;
	}

	public void setFobUom(String fobUom) {
		this.fobUom = fobUom;
	}

	public String getSettlePaymentTermCd() {
		return this.settlePaymentTermCd;
	}

	public void setSettlePaymentTermCd(String settlePaymentTermCd) {
		this.settlePaymentTermCd = settlePaymentTermCd;
	}

	public String getSettlementCurrCd() {
		return this.settlementCurrCd;
	}

	public void setSettlementCurrCd(String settlementCurrCd) {
		this.settlementCurrCd = settlementCurrCd;
	}

	public String getSettlementUomCd() {
		return this.settlementUomCd;
	}

	public void setSettlementUomCd(String settlementUomCd) {
		this.settlementUomCd = settlementUomCd;
	}

	public Date getActionDt() {
		return this.actionDt;
	}

	public void setActionDt(Date actionDt) {
		this.actionDt = actionDt;
	}

	public int getPriceQuoteDefNum() {
		return this.priceQuoteDefNum;
	}

	public void setPriceQuoteDefNum(int priceQuoteDefNum) {
		this.priceQuoteDefNum = priceQuoteDefNum;
	}

	public BigDecimal getPremium() {
		return this.premium;
	}

	public void setPremium(BigDecimal premium) {
		this.premium = premium;
	}

	public String getPremiumCurrCd() {
		return this.premiumCurrCd;
	}

	public void setPremiumCurrCd(String premiumCurrCd) {
		this.premiumCurrCd = premiumCurrCd;
	}

	public String getPremiumUomCd() {
		return this.premiumUomCd;
	}

	public void setPremiumUomCd(String premiumUomCd) {
		this.premiumUomCd = premiumUomCd;
	}

	public BigDecimal getActionPrice() {
		return this.actionPrice;
	}

	public void setActionPrice(BigDecimal actionPrice) {
		this.actionPrice = actionPrice;
	}

	public String getActionPriceCurrCd() {
		return this.actionPriceCurrCd;
	}

	public void setActionPriceCurrCd(String actionPriceCurrCd) {
		this.actionPriceCurrCd = actionPriceCurrCd;
	}

	public String getActionPriceUomCd() {
		return this.actionPriceUomCd;
	}

	public void setActionPriceUomCd(String actionPriceUomCd) {
		this.actionPriceUomCd = actionPriceUomCd;
	}

	public BigDecimal getActionQty() {
		return this.actionQty;
	}

	public void setActionQty(BigDecimal actionQty) {
		this.actionQty = actionQty;
	}

	public BigDecimal getActionLotQty() {
		return this.actionLotQty;
	}

	public void setActionLotQty(BigDecimal actionLotQty) {
		this.actionLotQty = actionLotQty;
	}

	public String getActionQtyUomCd() {
		return this.actionQtyUomCd;
	}

	public void setActionQtyUomCd(String actionQtyUomCd) {
		this.actionQtyUomCd = actionQtyUomCd;
	}

	public String getDealId() {
		return this.dealId;
	}

	public void setDealId(String dealId) {
		this.dealId = dealId;
	}

	public String getDealId2() {
		return this.dealId2;
	}

	public void setDealId2(String dealId2) {
		this.dealId2 = dealId2;
	}

	public String getNoteText() {
		return this.noteText;
	}

	public void setNoteText(String noteText) {
		this.noteText = noteText;
	}

	public String getNotePreview() {
		return this.notePreview;
	}

	public void setNotePreview(String notePreview) {
		this.notePreview = notePreview;
	}

	public String getDeliveryTerms() {
		return this.deliveryTerms;
	}

	public void setDeliveryTerms(String deliveryTerms) {
		this.deliveryTerms = deliveryTerms;
	}

	public String getWeightTerms() {
		return this.weightTerms;
	}

	public void setWeightTerms(String weightTerms) {
		this.weightTerms = weightTerms;
	}

	public String getApprovalTerms() {
		return this.approvalTerms;
	}

	public void setApprovalTerms(String approvalTerms) {
		this.approvalTerms = approvalTerms;
	}

	public String getBzCertPremium() {
		return this.bzCertPremium;
	}

	public void setBzCertPremium(String bzCertPremium) {
		this.bzCertPremium = bzCertPremium;
	}

	public String getBzCertStatus() {
		return this.bzCertStatus;
	}

	public void setBzCertStatus(String bzCertStatus) {
		this.bzCertStatus = bzCertStatus;
	}

	public String getBzChargedInterest() {
		return this.bzChargedInterest;
	}

	public void setBzChargedInterest(String bzChargedInterest) {
		this.bzChargedInterest = bzChargedInterest;
	}

	public String getBzCollatScheme() {
		return this.bzCollatScheme;
	}

	public void setBzCollatScheme(String bzCollatScheme) {
		this.bzCollatScheme = bzCollatScheme;
	}

	public String getBzCreditAssignee() {
		return this.bzCreditAssignee;
	}

	public void setBzCreditAssignee(String bzCreditAssignee) {
		this.bzCreditAssignee = bzCreditAssignee;
	}

	public String getBzExchCtrNum() {
		return this.bzExchCtrNum;
	}

	public void setBzExchCtrNum(String bzExchCtrNum) {
		this.bzExchCtrNum = bzExchCtrNum;
	}

	public String getBzFarmNeigh() {
		return this.bzFarmNeigh;
	}

	public void setBzFarmNeigh(String bzFarmNeigh) {
		this.bzFarmNeigh = bzFarmNeigh;
	}

	public String getBzFarmRegion() {
		return this.bzFarmRegion;
	}

	public void setBzFarmRegion(String bzFarmRegion) {
		this.bzFarmRegion = bzFarmRegion;
	}

	public String getBzFarmState() {
		return this.bzFarmState;
	}

	public void setBzFarmState(String bzFarmState) {
		this.bzFarmState = bzFarmState;
	}

	public String getBzFobbasis() {
		return this.bzFobbasis;
	}

	public void setBzFobbasis(String bzFobbasis) {
		this.bzFobbasis = bzFobbasis;
	}

	public String getBzFormalReturnDat() {
		return this.bzFormalReturnDat;
	}

	public void setBzFormalReturnDat(String bzFormalReturnDat) {
		this.bzFormalReturnDat = bzFormalReturnDat;
	}

	public String getBzFrmlztRlseDate() {
		return this.bzFrmlztRlseDate;
	}

	public void setBzFrmlztRlseDate(String bzFrmlztRlseDate) {
		this.bzFrmlztRlseDate = bzFrmlztRlseDate;
	}

	public String getBzFxhedgingLevel() {
		return this.bzFxhedgingLevel;
	}

	public void setBzFxhedgingLevel(String bzFxhedgingLevel) {
		this.bzFxhedgingLevel = bzFxhedgingLevel;
	}

	public String getBzGuarantor1st() {
		return this.bzGuarantor1st;
	}

	public void setBzGuarantor1st(String bzGuarantor1st) {
		this.bzGuarantor1st = bzGuarantor1st;
	}

	public String getBzGuarantor2nd() {
		return this.bzGuarantor2nd;
	}

	public void setBzGuarantor2nd(String bzGuarantor2nd) {
		this.bzGuarantor2nd = bzGuarantor2nd;
	}

	public String getBzIr1recepDat() {
		return this.bzIr1recepDat;
	}

	public void setBzIr1recepDat(String bzIr1recepDat) {
		this.bzIr1recepDat = bzIr1recepDat;
	}

	public String getBzIr1ProductHec() {
		return this.bzIr1ProductHec;
	}

	public void setBzIr1ProductHec(String bzIr1ProductHec) {
		this.bzIr1ProductHec = bzIr1ProductHec;
	}

	public String getBzIr1RiskSituat() {
		return this.bzIr1RiskSituat;
	}

	public void setBzIr1RiskSituat(String bzIr1RiskSituat) {
		this.bzIr1RiskSituat = bzIr1RiskSituat;
	}

	public String getBzPymtAnticip() {
		return this.bzPymtAnticip;
	}

	public void setBzPymtAnticip(String bzPymtAnticip) {
		this.bzPymtAnticip = bzPymtAnticip;
	}

	public String getBzShareholderdsbmt() {
		return this.bzShareholderdsbmt;
	}

	public void setBzShareholderdsbmt(String bzShareholderdsbmt) {
		this.bzShareholderdsbmt = bzShareholderdsbmt;
	}

	public String getBzTradeBasis() {
		return this.bzTradeBasis;
	}

	public void setBzTradeBasis(String bzTradeBasis) {
		this.bzTradeBasis = bzTradeBasis;
	}

	public String getBzTradeType() {
		return this.bzTradeType;
	}

	public void setBzTradeType(String bzTradeType) {
		this.bzTradeType = bzTradeType;
	}

	public String getCurrentPotype() {
		return this.currentPotype;
	}

	public void setCurrentPotype(String currentPotype) {
		this.currentPotype = currentPotype;
	}

	public String getFxfixedRate() {
		return this.fxfixedRate;
	}

	public void setFxfixedRate(String fxfixedRate) {
		this.fxfixedRate = fxfixedRate;
	}

	public String getPotype() {
		return this.potype;
	}

	public void setPotype(String potype) {
		this.potype = potype;
	}

	public String getBzFinRatio() {
		return this.bzFinRatio;
	}

	public void setBzFinRatio(String bzFinRatio) {
		this.bzFinRatio = bzFinRatio;
	}

	public String getBzAnuentePrimario() {
		return this.bzAnuentePrimario;
	}

	public void setBzAnuentePrimario(String bzAnuentePrimario) {
		this.bzAnuentePrimario = bzAnuentePrimario;
	}

	public String getBzAnuenteSecundario() {
		return this.bzAnuenteSecundario;
	}

	public void setBzAnuenteSecundario(String bzAnuenteSecundario) {
		this.bzAnuenteSecundario = bzAnuenteSecundario;
	}

	public String getBzFixationDeadline() {
		return this.bzFixationDeadline;
	}

	public void setBzFixationDeadline(String bzFixationDeadline) {
		this.bzFixationDeadline = bzFixationDeadline;
	}

	public String getBzWacc() {
		return this.bzWacc;
	}

	public void setBzWacc(String bzWacc) {
		this.bzWacc = bzWacc;
	}

	public String getBzLgfixedPriceSao() {
		return this.bzLgfixedPriceSao;
	}

	public void setBzLgfixedPriceSao(String bzLgfixedPriceSao) {
		this.bzLgfixedPriceSao = bzLgfixedPriceSao;
	}

	public String getBzThirdpartydsbmt() {
		return this.bzThirdpartydsbmt;
	}

	public void setBzThirdpartydsbmt(String bzThirdpartydsbmt) {
		this.bzThirdpartydsbmt = bzThirdpartydsbmt;
	}

	public String getBzCollatRecepDate() {
		return this.bzCollatRecepDate;
	}

	public void setBzCollatRecepDate(String bzCollatRecepDate) {
		this.bzCollatRecepDate = bzCollatRecepDate;
	}

	public String getBzShareholDsbmtDt() {
		return this.bzShareholDsbmtDt;
	}

	public void setBzShareholDsbmtDt(String bzShareholDsbmtDt) {
		this.bzShareholDsbmtDt = bzShareholDsbmtDt;
	}

	public String getBz3partyDsbmtDt() {
		return this.bz3partyDsbmtDt;
	}

	public void setBz3partyDsbmtDt(String bz3partyDsbmtDt) {
		this.bz3partyDsbmtDt = bz3partyDsbmtDt;
	}

	public String getBzExpDiffFobbas() {
		return this.bzExpDiffFobbas;
	}

	public void setBzExpDiffFobbas(String bzExpDiffFobbas) {
		this.bzExpDiffFobbas = bzExpDiffFobbas;
	}

	public String getBzDrdiffvsNysao() {
		return this.bzDrdiffvsNysao;
	}

	public void setBzDrdiffvsNysao(String bzDrdiffvsNysao) {
		this.bzDrdiffvsNysao = bzDrdiffvsNysao;
	}

	public String getBzActualAnticAmt() {
		return this.bzActualAnticAmt;
	}

	public void setBzActualAnticAmt(String bzActualAnticAmt) {
		this.bzActualAnticAmt = bzActualAnticAmt;
	}

	public String getBzBcdiffTrade() {
		return this.bzBcdiffTrade;
	}

	public void setBzBcdiffTrade(String bzBcdiffTrade) {
		this.bzBcdiffTrade = bzBcdiffTrade;
	}

	public String getBzBcdiffFob() {
		return this.bzBcdiffFob;
	}

	public void setBzBcdiffFob(String bzBcdiffFob) {
		this.bzBcdiffFob = bzBcdiffFob;
	}

	public String getBzDeliveryWhse() {
		return this.bzDeliveryWhse;
	}

	public void setBzDeliveryWhse(String bzDeliveryWhse) {
		this.bzDeliveryWhse = bzDeliveryWhse;
	}

	public String getBzFxexposure() {
		return this.bzFxexposure;
	}

	public void setBzFxexposure(String bzFxexposure) {
		this.bzFxexposure = bzFxexposure;
	}

	public String getBzFxhedgingdate() {
		return this.bzFxhedgingdate;
	}

	public void setBzFxhedgingdate(String bzFxhedgingdate) {
		this.bzFxhedgingdate = bzFxhedgingdate;
	}

	public String getBzFxverification() {
		return this.bzFxverification;
	}

	public void setBzFxverification(String bzFxverification) {
		this.bzFxverification = bzFxverification;
	}

	public String getBzFxhedgingCounte() {
		return this.bzFxhedgingCounte;
	}

	public void setBzFxhedgingCounte(String bzFxhedgingCounte) {
		this.bzFxhedgingCounte = bzFxhedgingCounte;
	}

	public String getGtDeliveryPlace() {
		return this.gtDeliveryPlace;
	}

	public void setGtDeliveryPlace(String gtDeliveryPlace) {
		this.gtDeliveryPlace = gtDeliveryPlace;
	}

	public String getGtLndCostFrom() {
		return this.gtLndCostFrom;
	}

	public void setGtLndCostFrom(String gtLndCostFrom) {
		this.gtLndCostFrom = gtLndCostFrom;
	}

	public String getGtLndCostTo() {
		return this.gtLndCostTo;
	}

	public void setGtLndCostTo(String gtLndCostTo) {
		this.gtLndCostTo = gtLndCostTo;
	}

	public String getGtMgtprice() {
		return this.gtMgtprice;
	}

	public void setGtMgtprice(String gtMgtprice) {
		this.gtMgtprice = gtMgtprice;
	}

	public String getGtPreparacion() {
		return this.gtPreparacion;
	}

	public void setGtPreparacion(String gtPreparacion) {
		this.gtPreparacion = gtPreparacion;
	}

	public String getGtPymtCondition() {
		return this.gtPymtCondition;
	}

	public void setGtPymtCondition(String gtPymtCondition) {
		this.gtPymtCondition = gtPymtCondition;
	}

	public String getGtShpmtCostFrom() {
		return this.gtShpmtCostFrom;
	}

	public void setGtShpmtCostFrom(String gtShpmtCostFrom) {
		this.gtShpmtCostFrom = gtShpmtCostFrom;
	}

	public String getGtShpmtCostTo() {
		return this.gtShpmtCostTo;
	}

	public void setGtShpmtCostTo(String gtShpmtCostTo) {
		this.gtShpmtCostTo = gtShpmtCostTo;
	}

	public String getGtShpmtValue() {
		return this.gtShpmtValue;
	}

	public void setGtShpmtValue(String gtShpmtValue) {
		this.gtShpmtValue = gtShpmtValue;
	}

	public String getGtTradeCost() {
		return this.gtTradeCost;
	}

	public void setGtTradeCost(String gtTradeCost) {
		this.gtTradeCost = gtTradeCost;
	}

	public String getGtRealCost() {
		return this.gtRealCost;
	}

	public void setGtRealCost(String gtRealCost) {
		this.gtRealCost = gtRealCost;
	}

	public String getGtNetDiffBuy() {
		return this.gtNetDiffBuy;
	}

	public void setGtNetDiffBuy(String gtNetDiffBuy) {
		this.gtNetDiffBuy = gtNetDiffBuy;
	}

	public String getGtZarCost() {
		return this.gtZarCost;
	}

	public void setGtZarCost(String gtZarCost) {
		this.gtZarCost = gtZarCost;
	}

	public String getGtSubpCost() {
		return this.gtSubpCost;
	}

	public void setGtSubpCost(String gtSubpCost) {
		this.gtSubpCost = gtSubpCost;
	}

	public BigDecimal getMultiplier() {
		return this.multiplier;
	}

	public void setMultiplier(BigDecimal multiplier) {
		this.multiplier = multiplier;
	}

	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	public String getCounterpart() {
		return this.counterpart;
	}

	public void setCounterpart(String counterpart) {
		this.counterpart = counterpart;
	}

	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	public String getRiskPeriodCd() {
		return this.riskPeriodCd;
	}

	public void setRiskPeriodCd(String riskPeriodCd) {
		this.riskPeriodCd = riskPeriodCd;
	}

	public short getTradeStatusInd() {
		return this.tradeStatusInd;
	}

	public void setTradeStatusInd(short tradeStatusInd) {
		this.tradeStatusInd = tradeStatusInd;
	}

	public String getSpecCd() {
		return this.specCd;
	}

	public void setSpecCd(String specCd) {
		this.specCd = specCd;
	}
	
	public BigDecimal getOpenQty() {
		return openQty;
	}

	public void setOpenQty(BigDecimal openQty) {
		this.openQty = openQty;
	}
	
	public BigDecimal getScheduledQty() {
		return scheduledQty;
	}

	public void setScheduledQty(BigDecimal scheduledQty) {
		this.scheduledQty = scheduledQty;
	}
	
	public int getObligationNum() {
		return obligationNum;
	}

	public void setObligationNum(int obligationNum) {
		this.obligationNum = obligationNum;
	}
	
	public int getObligationDetailNum() {
		return obligationDetailNum;
	}

	public void setObligationDetailNum(int obligationDetailNum) {
		this.obligationDetailNum = obligationDetailNum;
	}

	public BigDecimal getStrategyNum() {
		return strategyNum;
	}

	public void setStrategyNum(BigDecimal strategyNum) {
		this.strategyNum = strategyNum;
	}

	public BigDecimal getTermNum() {
		return termNum;
	}

	public void setTermNum(BigDecimal termNum) {
		this.termNum = termNum;
	}

	public String getTermSectionCd() {
		return termSectionCd;
	}

	public void setTermSectionCd(String termSectionCd) {
		this.termSectionCd = termSectionCd;
	}

	public BigDecimal getCompanyNum() {
		return companyNum;
	}

	public void setCompanyNum(BigDecimal companyNum) {
		this.companyNum = companyNum;
	}

	public Date getLaycanStartDt() {
		return laycanStartDt;
	}

	public void setLaycanStartDt(Date laycanStartDt) {
		this.laycanStartDt = laycanStartDt;
	}

	public Date getLaycanEndDt() {
		return laycanEndDt;
	}

	public void setLaycanEndDt(Date laycanEndDt) {
		this.laycanEndDt = laycanEndDt;
	}

	public BigDecimal getDelivQty() {
		return delivQty;
	}

	public void setDelivQty(BigDecimal delivQty) {
		this.delivQty = delivQty;
	}

	public String getDelivUomCd() {
		return delivUomCd;
	}

	public void setDelivUomCd(String delivUomCd) {
		this.delivUomCd = delivUomCd;
	}

	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}
	
	public Short getAirVacInd() {
		return airVacInd;
	}

	public void setAirVacInd(Short airVacInd) {
		this.airVacInd = airVacInd;
	}

	public Integer getMtmFwdCurveNum() {
		return mtmFwdCurveNum;
	}

	public void setMtmFwdCurveNum(Integer mtmFwdCurveNum) {
		this.mtmFwdCurveNum = mtmFwdCurveNum;
	}

	public Short getCustomsDutyStatusInd() {
		return customsDutyStatusInd;
	}

	public void setCustomsDutyStatusInd(Short customsDutyStatusInd) {
		this.customsDutyStatusInd = customsDutyStatusInd;
	}

	public Short getSchConfExecutedInd() {
		return schConfExecutedInd;
	}

	public void setSchConfExecutedInd(Short schConfExecutedInd) {
		this.schConfExecutedInd = schConfExecutedInd;
	}

	public Short getPricingStatusInd() {
		return pricingStatusInd;
	}

	public void setPricingStatusInd(Short pricingStatusInd) {
		this.pricingStatusInd = pricingStatusInd;
	}

	public Short getFuturesPricingStatusInd() {
		return futuresPricingStatusInd;
	}

	public void setFuturesPricingStatusInd(Short futuresPricingStatusInd) {
		this.futuresPricingStatusInd = futuresPricingStatusInd;
	}

	public Short getBasisPricingStatusInd() {
		return basisPricingStatusInd;
	}

	public void setBasisPricingStatusInd(Short basisPricingStatusInd) {
		this.basisPricingStatusInd = basisPricingStatusInd;
	}

	public Integer getOriginLocNum() {
		return originLocNum;
	}

	public void setOriginLocNum(Integer originLocNum) {
		this.originLocNum = originLocNum;
	}

	public Short getObligationTypeInd() {
		return obligationTypeInd;
	}

	public void setObligationTypeInd(Short obligationTypeInd) {
		this.obligationTypeInd = obligationTypeInd;
	}

	@Override
	public String toString() {
		return String.valueOf(getTradeNum());
	}
	
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VtradeInputId))
			return false;
		VtradeInputId castOther = (VtradeInputId) other;

		return (this.getTradeNum() == castOther.getTradeNum())
				&& ((this.getTraderNum() == castOther.getTraderNum()) || (this
						.getTraderNum() != null
						&& castOther.getTraderNum() != null && this
						.getTraderNum().equals(castOther.getTraderNum())))
				&& ((this.getInternalCompanyNum() == castOther
						.getInternalCompanyNum()) || (this
						.getInternalCompanyNum() != null
						&& castOther.getInternalCompanyNum() != null && this
						.getInternalCompanyNum().equals(
								castOther.getInternalCompanyNum())))
				&& ((this.getCounterpartCompanyNum() == castOther
						.getCounterpartCompanyNum()) || (this
						.getCounterpartCompanyNum() != null
						&& castOther.getCounterpartCompanyNum() != null && this
						.getCounterpartCompanyNum().equals(
								castOther.getCounterpartCompanyNum())))
				&& ((this.getTradeDt() == castOther.getTradeDt()) || (this
						.getTradeDt() != null && castOther.getTradeDt() != null && this
						.getTradeDt().equals(castOther.getTradeDt())))
				&& (this.getBrokerCompanyNum() == castOther
						.getBrokerCompanyNum())
				&& ((this.getCommissionAmt() == castOther.getCommissionAmt()) || (this
						.getCommissionAmt() != null
						&& castOther.getCommissionAmt() != null && this
						.getCommissionAmt()
						.equals(castOther.getCommissionAmt())))
				&& ((this.getCommCurrCd() == castOther.getCommCurrCd()) || (this
						.getCommCurrCd() != null
						&& castOther.getCommCurrCd() != null && this
						.getCommCurrCd().equals(castOther.getCommCurrCd())))
				&& ((this.getCommUomCd() == castOther.getCommUomCd()) || (this
						.getCommUomCd() != null
						&& castOther.getCommUomCd() != null && this
						.getCommUomCd().equals(castOther.getCommUomCd())))
				&& ((this.getBuySellInd() == castOther.getBuySellInd()) || (this
						.getBuySellInd() != null
						&& castOther.getBuySellInd() != null && this
						.getBuySellInd().equals(castOther.getBuySellInd())))
				&& ((this.getBuySell() == castOther.getBuySell()) || (this
						.getBuySell() != null && castOther.getBuySell() != null && this
						.getBuySell().equals(castOther.getBuySell())))
				&& ((this.getCmdtyCd() == castOther.getCmdtyCd()) || (this
						.getCmdtyCd() != null && castOther.getCmdtyCd() != null && this
						.getCmdtyCd().equals(castOther.getCmdtyCd())))
				&& ((this.getCropYear() == castOther.getCropYear()) || (this
						.getCropYear() != null
						&& castOther.getCropYear() != null && this
						.getCropYear().equals(castOther.getCropYear())))
				&& ((this.getTradeQty() == castOther.getTradeQty()) || (this
						.getTradeQty() != null
						&& castOther.getTradeQty() != null && this
						.getTradeQty().equals(castOther.getTradeQty())))
				&& ((this.getContractUomCd() == castOther.getContractUomCd()) || (this
						.getContractUomCd() != null
						&& castOther.getContractUomCd() != null && this
						.getContractUomCd()
						.equals(castOther.getContractUomCd())))
				&& ((this.getDeliveryTermCd() == castOther.getDeliveryTermCd()) || (this
						.getDeliveryTermCd() != null
						&& castOther.getDeliveryTermCd() != null && this
						.getDeliveryTermCd().equals(
								castOther.getDeliveryTermCd())))
				&& ((this.getLocation() == castOther.getLocation()) || (this
						.getLocation() != null
						&& castOther.getLocation() != null && this
						.getLocation().equals(castOther.getLocation())))
				&& (this.getDestinaton() == castOther.getDestinaton())
				&& (this.getCountry() == castOther.getCountry())
				&& ((this.getDelivPeriodCd() == castOther.getDelivPeriodCd()) || (this
						.getDelivPeriodCd() != null
						&& castOther.getDelivPeriodCd() != null && this
						.getDelivPeriodCd()
						.equals(castOther.getDelivPeriodCd())))
				&& ((this.getQuoteDefNum() == castOther.getQuoteDefNum()) || (this
						.getQuoteDefNum() != null
						&& castOther.getQuoteDefNum() != null && this
						.getQuoteDefNum().equals(castOther.getQuoteDefNum())))
				&& ((this.getExchContractNum() == castOther
						.getExchContractNum()) || (this.getExchContractNum() != null
						&& castOther.getExchContractNum() != null && this
						.getExchContractNum().equals(
								castOther.getExchContractNum())))
				&& ((this.getFixedPrice() == castOther.getFixedPrice()) || (this
						.getFixedPrice() != null
						&& castOther.getFixedPrice() != null && this
						.getFixedPrice().equals(castOther.getFixedPrice())))
				&& ((this.getPriceCurrCd() == castOther.getPriceCurrCd()) || (this
						.getPriceCurrCd() != null
						&& castOther.getPriceCurrCd() != null && this
						.getPriceCurrCd().equals(castOther.getPriceCurrCd())))
				&& ((this.getPriceUomCd() == castOther.getPriceUomCd()) || (this
						.getPriceUomCd() != null
						&& castOther.getPriceUomCd() != null && this
						.getPriceUomCd().equals(castOther.getPriceUomCd())))
				&& ((this.getFobPrice() == castOther.getFobPrice()) || (this
						.getFobPrice() != null
						&& castOther.getFobPrice() != null && this
						.getFobPrice().equals(castOther.getFobPrice())))
				&& ((this.getFobCurrency() == castOther.getFobCurrency()) || (this
						.getFobCurrency() != null
						&& castOther.getFobCurrency() != null && this
						.getFobCurrency().equals(castOther.getFobCurrency())))
				&& ((this.getFobUom() == castOther.getFobUom()) || (this
						.getFobUom() != null && castOther.getFobUom() != null && this
						.getFobUom().equals(castOther.getFobUom())))
				&& ((this.getSettlePaymentTermCd() == castOther
						.getSettlePaymentTermCd()) || (this
						.getSettlePaymentTermCd() != null
						&& castOther.getSettlePaymentTermCd() != null && this
						.getSettlePaymentTermCd().equals(
								castOther.getSettlePaymentTermCd())))
				&& ((this.getSettlementCurrCd() == castOther
						.getSettlementCurrCd()) || (this.getSettlementCurrCd() != null
						&& castOther.getSettlementCurrCd() != null && this
						.getSettlementCurrCd().equals(
								castOther.getSettlementCurrCd())))
				&& ((this.getSettlementUomCd() == castOther
						.getSettlementUomCd()) || (this.getSettlementUomCd() != null
						&& castOther.getSettlementUomCd() != null && this
						.getSettlementUomCd().equals(
								castOther.getSettlementUomCd())))
				&& ((this.getActionDt() == castOther.getActionDt()) || (this
						.getActionDt() != null
						&& castOther.getActionDt() != null && this
						.getActionDt().equals(castOther.getActionDt())))
				&& (this.getPriceQuoteDefNum() == castOther
						.getPriceQuoteDefNum())
				&& ((this.getPremium() == castOther.getPremium()) || (this
						.getPremium() != null && castOther.getPremium() != null && this
						.getPremium().equals(castOther.getPremium())))
				&& ((this.getPremiumCurrCd() == castOther.getPremiumCurrCd()) || (this
						.getPremiumCurrCd() != null
						&& castOther.getPremiumCurrCd() != null && this
						.getPremiumCurrCd()
						.equals(castOther.getPremiumCurrCd())))
				&& ((this.getPremiumUomCd() == castOther.getPremiumUomCd()) || (this
						.getPremiumUomCd() != null
						&& castOther.getPremiumUomCd() != null && this
						.getPremiumUomCd().equals(castOther.getPremiumUomCd())))
				&& ((this.getActionPrice() == castOther.getActionPrice()) || (this
						.getActionPrice() != null
						&& castOther.getActionPrice() != null && this
						.getActionPrice().equals(castOther.getActionPrice())))
				&& ((this.getActionPriceCurrCd() == castOther
						.getActionPriceCurrCd()) || (this
						.getActionPriceCurrCd() != null
						&& castOther.getActionPriceCurrCd() != null && this
						.getActionPriceCurrCd().equals(
								castOther.getActionPriceCurrCd())))
				&& ((this.getActionPriceUomCd() == castOther
						.getActionPriceUomCd()) || (this.getActionPriceUomCd() != null
						&& castOther.getActionPriceUomCd() != null && this
						.getActionPriceUomCd().equals(
								castOther.getActionPriceUomCd())))
				&& ((this.getActionQty() == castOther.getActionQty()) || (this
						.getActionQty() != null
						&& castOther.getActionQty() != null && this
						.getActionQty().equals(castOther.getActionQty())))
				&& ((this.getActionLotQty() == castOther.getActionLotQty()) || (this
						.getActionLotQty() != null
						&& castOther.getActionLotQty() != null && this
						.getActionLotQty().equals(castOther.getActionLotQty())))
				&& ((this.getActionQtyUomCd() == castOther.getActionQtyUomCd()) || (this
						.getActionQtyUomCd() != null
						&& castOther.getActionQtyUomCd() != null && this
						.getActionQtyUomCd().equals(
								castOther.getActionQtyUomCd())))
				&& ((this.getDealId() == castOther.getDealId()) || (this
						.getDealId() != null && castOther.getDealId() != null && this
						.getDealId().equals(castOther.getDealId())))
				&& ((this.getDealId2() == castOther.getDealId2()) || (this
						.getDealId2() != null && castOther.getDealId2() != null && this
						.getDealId2().equals(castOther.getDealId2())))
				&& ((this.getNoteText() == castOther.getNoteText()) || (this
						.getNoteText() != null
						&& castOther.getNoteText() != null && this
						.getNoteText().equals(castOther.getNoteText())))
				&& ((this.getNotePreview() == castOther.getNotePreview()) || (this
						.getNotePreview() != null
						&& castOther.getNotePreview() != null && this
						.getNotePreview().equals(castOther.getNotePreview())))
				&& ((this.getDeliveryTerms() == castOther.getDeliveryTerms()) || (this
						.getDeliveryTerms() != null
						&& castOther.getDeliveryTerms() != null && this
						.getDeliveryTerms()
						.equals(castOther.getDeliveryTerms())))
				&& ((this.getWeightTerms() == castOther.getWeightTerms()) || (this
						.getWeightTerms() != null
						&& castOther.getWeightTerms() != null && this
						.getWeightTerms().equals(castOther.getWeightTerms())))
				&& ((this.getApprovalTerms() == castOther.getApprovalTerms()) || (this
						.getApprovalTerms() != null
						&& castOther.getApprovalTerms() != null && this
						.getApprovalTerms()
						.equals(castOther.getApprovalTerms())))
				&& ((this.getBzCertPremium() == castOther.getBzCertPremium()) || (this
						.getBzCertPremium() != null
						&& castOther.getBzCertPremium() != null && this
						.getBzCertPremium()
						.equals(castOther.getBzCertPremium())))
				&& ((this.getBzCertStatus() == castOther.getBzCertStatus()) || (this
						.getBzCertStatus() != null
						&& castOther.getBzCertStatus() != null && this
						.getBzCertStatus().equals(castOther.getBzCertStatus())))
				&& ((this.getBzChargedInterest() == castOther
						.getBzChargedInterest()) || (this
						.getBzChargedInterest() != null
						&& castOther.getBzChargedInterest() != null && this
						.getBzChargedInterest().equals(
								castOther.getBzChargedInterest())))
				&& ((this.getBzCollatScheme() == castOther.getBzCollatScheme()) || (this
						.getBzCollatScheme() != null
						&& castOther.getBzCollatScheme() != null && this
						.getBzCollatScheme().equals(
								castOther.getBzCollatScheme())))
				&& ((this.getBzCreditAssignee() == castOther
						.getBzCreditAssignee()) || (this.getBzCreditAssignee() != null
						&& castOther.getBzCreditAssignee() != null && this
						.getBzCreditAssignee().equals(
								castOther.getBzCreditAssignee())))
				&& ((this.getBzExchCtrNum() == castOther.getBzExchCtrNum()) || (this
						.getBzExchCtrNum() != null
						&& castOther.getBzExchCtrNum() != null && this
						.getBzExchCtrNum().equals(castOther.getBzExchCtrNum())))
				&& ((this.getBzFarmNeigh() == castOther.getBzFarmNeigh()) || (this
						.getBzFarmNeigh() != null
						&& castOther.getBzFarmNeigh() != null && this
						.getBzFarmNeigh().equals(castOther.getBzFarmNeigh())))
				&& ((this.getBzFarmRegion() == castOther.getBzFarmRegion()) || (this
						.getBzFarmRegion() != null
						&& castOther.getBzFarmRegion() != null && this
						.getBzFarmRegion().equals(castOther.getBzFarmRegion())))
				&& ((this.getBzFarmState() == castOther.getBzFarmState()) || (this
						.getBzFarmState() != null
						&& castOther.getBzFarmState() != null && this
						.getBzFarmState().equals(castOther.getBzFarmState())))
				&& ((this.getBzFobbasis() == castOther.getBzFobbasis()) || (this
						.getBzFobbasis() != null
						&& castOther.getBzFobbasis() != null && this
						.getBzFobbasis().equals(castOther.getBzFobbasis())))
				&& ((this.getBzFormalReturnDat() == castOther
						.getBzFormalReturnDat()) || (this
						.getBzFormalReturnDat() != null
						&& castOther.getBzFormalReturnDat() != null && this
						.getBzFormalReturnDat().equals(
								castOther.getBzFormalReturnDat())))
				&& ((this.getBzFrmlztRlseDate() == castOther
						.getBzFrmlztRlseDate()) || (this.getBzFrmlztRlseDate() != null
						&& castOther.getBzFrmlztRlseDate() != null && this
						.getBzFrmlztRlseDate().equals(
								castOther.getBzFrmlztRlseDate())))
				&& ((this.getBzFxhedgingLevel() == castOther
						.getBzFxhedgingLevel()) || (this.getBzFxhedgingLevel() != null
						&& castOther.getBzFxhedgingLevel() != null && this
						.getBzFxhedgingLevel().equals(
								castOther.getBzFxhedgingLevel())))
				&& ((this.getBzGuarantor1st() == castOther.getBzGuarantor1st()) || (this
						.getBzGuarantor1st() != null
						&& castOther.getBzGuarantor1st() != null && this
						.getBzGuarantor1st().equals(
								castOther.getBzGuarantor1st())))
				&& ((this.getBzGuarantor2nd() == castOther.getBzGuarantor2nd()) || (this
						.getBzGuarantor2nd() != null
						&& castOther.getBzGuarantor2nd() != null && this
						.getBzGuarantor2nd().equals(
								castOther.getBzGuarantor2nd())))
				&& ((this.getBzIr1recepDat() == castOther.getBzIr1recepDat()) || (this
						.getBzIr1recepDat() != null
						&& castOther.getBzIr1recepDat() != null && this
						.getBzIr1recepDat()
						.equals(castOther.getBzIr1recepDat())))
				&& ((this.getBzIr1ProductHec() == castOther
						.getBzIr1ProductHec()) || (this.getBzIr1ProductHec() != null
						&& castOther.getBzIr1ProductHec() != null && this
						.getBzIr1ProductHec().equals(
								castOther.getBzIr1ProductHec())))
				&& ((this.getBzIr1RiskSituat() == castOther
						.getBzIr1RiskSituat()) || (this.getBzIr1RiskSituat() != null
						&& castOther.getBzIr1RiskSituat() != null && this
						.getBzIr1RiskSituat().equals(
								castOther.getBzIr1RiskSituat())))
				&& ((this.getBzPymtAnticip() == castOther.getBzPymtAnticip()) || (this
						.getBzPymtAnticip() != null
						&& castOther.getBzPymtAnticip() != null && this
						.getBzPymtAnticip()
						.equals(castOther.getBzPymtAnticip())))
				&& ((this.getBzShareholderdsbmt() == castOther
						.getBzShareholderdsbmt()) || (this
						.getBzShareholderdsbmt() != null
						&& castOther.getBzShareholderdsbmt() != null && this
						.getBzShareholderdsbmt().equals(
								castOther.getBzShareholderdsbmt())))
				&& ((this.getBzTradeBasis() == castOther.getBzTradeBasis()) || (this
						.getBzTradeBasis() != null
						&& castOther.getBzTradeBasis() != null && this
						.getBzTradeBasis().equals(castOther.getBzTradeBasis())))
				&& ((this.getBzTradeType() == castOther.getBzTradeType()) || (this
						.getBzTradeType() != null
						&& castOther.getBzTradeType() != null && this
						.getBzTradeType().equals(castOther.getBzTradeType())))
				&& ((this.getCurrentPotype() == castOther.getCurrentPotype()) || (this
						.getCurrentPotype() != null
						&& castOther.getCurrentPotype() != null && this
						.getCurrentPotype()
						.equals(castOther.getCurrentPotype())))
				&& ((this.getFxfixedRate() == castOther.getFxfixedRate()) || (this
						.getFxfixedRate() != null
						&& castOther.getFxfixedRate() != null && this
						.getFxfixedRate().equals(castOther.getFxfixedRate())))
				&& ((this.getPotype() == castOther.getPotype()) || (this
						.getPotype() != null && castOther.getPotype() != null && this
						.getPotype().equals(castOther.getPotype())))
				&& ((this.getBzFinRatio() == castOther.getBzFinRatio()) || (this
						.getBzFinRatio() != null
						&& castOther.getBzFinRatio() != null && this
						.getBzFinRatio().equals(castOther.getBzFinRatio())))
				&& ((this.getBzAnuentePrimario() == castOther
						.getBzAnuentePrimario()) || (this
						.getBzAnuentePrimario() != null
						&& castOther.getBzAnuentePrimario() != null && this
						.getBzAnuentePrimario().equals(
								castOther.getBzAnuentePrimario())))
				&& ((this.getBzAnuenteSecundario() == castOther
						.getBzAnuenteSecundario()) || (this
						.getBzAnuenteSecundario() != null
						&& castOther.getBzAnuenteSecundario() != null && this
						.getBzAnuenteSecundario().equals(
								castOther.getBzAnuenteSecundario())))
				&& ((this.getBzFixationDeadline() == castOther
						.getBzFixationDeadline()) || (this
						.getBzFixationDeadline() != null
						&& castOther.getBzFixationDeadline() != null && this
						.getBzFixationDeadline().equals(
								castOther.getBzFixationDeadline())))
				&& ((this.getBzWacc() == castOther.getBzWacc()) || (this
						.getBzWacc() != null && castOther.getBzWacc() != null && this
						.getBzWacc().equals(castOther.getBzWacc())))
				&& ((this.getBzLgfixedPriceSao() == castOther
						.getBzLgfixedPriceSao()) || (this
						.getBzLgfixedPriceSao() != null
						&& castOther.getBzLgfixedPriceSao() != null && this
						.getBzLgfixedPriceSao().equals(
								castOther.getBzLgfixedPriceSao())))
				&& ((this.getBzThirdpartydsbmt() == castOther
						.getBzThirdpartydsbmt()) || (this
						.getBzThirdpartydsbmt() != null
						&& castOther.getBzThirdpartydsbmt() != null && this
						.getBzThirdpartydsbmt().equals(
								castOther.getBzThirdpartydsbmt())))
				&& ((this.getBzCollatRecepDate() == castOther
						.getBzCollatRecepDate()) || (this
						.getBzCollatRecepDate() != null
						&& castOther.getBzCollatRecepDate() != null && this
						.getBzCollatRecepDate().equals(
								castOther.getBzCollatRecepDate())))
				&& ((this.getBzShareholDsbmtDt() == castOther
						.getBzShareholDsbmtDt()) || (this
						.getBzShareholDsbmtDt() != null
						&& castOther.getBzShareholDsbmtDt() != null && this
						.getBzShareholDsbmtDt().equals(
								castOther.getBzShareholDsbmtDt())))
				&& ((this.getBz3partyDsbmtDt() == castOther
						.getBz3partyDsbmtDt()) || (this.getBz3partyDsbmtDt() != null
						&& castOther.getBz3partyDsbmtDt() != null && this
						.getBz3partyDsbmtDt().equals(
								castOther.getBz3partyDsbmtDt())))
				&& ((this.getBzExpDiffFobbas() == castOther
						.getBzExpDiffFobbas()) || (this.getBzExpDiffFobbas() != null
						&& castOther.getBzExpDiffFobbas() != null && this
						.getBzExpDiffFobbas().equals(
								castOther.getBzExpDiffFobbas())))
				&& ((this.getBzDrdiffvsNysao() == castOther
						.getBzDrdiffvsNysao()) || (this.getBzDrdiffvsNysao() != null
						&& castOther.getBzDrdiffvsNysao() != null && this
						.getBzDrdiffvsNysao().equals(
								castOther.getBzDrdiffvsNysao())))
				&& ((this.getBzActualAnticAmt() == castOther
						.getBzActualAnticAmt()) || (this.getBzActualAnticAmt() != null
						&& castOther.getBzActualAnticAmt() != null && this
						.getBzActualAnticAmt().equals(
								castOther.getBzActualAnticAmt())))
				&& ((this.getBzBcdiffTrade() == castOther.getBzBcdiffTrade()) || (this
						.getBzBcdiffTrade() != null
						&& castOther.getBzBcdiffTrade() != null && this
						.getBzBcdiffTrade()
						.equals(castOther.getBzBcdiffTrade())))
				&& ((this.getBzBcdiffFob() == castOther.getBzBcdiffFob()) || (this
						.getBzBcdiffFob() != null
						&& castOther.getBzBcdiffFob() != null && this
						.getBzBcdiffFob().equals(castOther.getBzBcdiffFob())))
				&& ((this.getBzDeliveryWhse() == castOther.getBzDeliveryWhse()) || (this
						.getBzDeliveryWhse() != null
						&& castOther.getBzDeliveryWhse() != null && this
						.getBzDeliveryWhse().equals(
								castOther.getBzDeliveryWhse())))
				&& ((this.getBzFxexposure() == castOther.getBzFxexposure()) || (this
						.getBzFxexposure() != null
						&& castOther.getBzFxexposure() != null && this
						.getBzFxexposure().equals(castOther.getBzFxexposure())))
				&& ((this.getBzFxhedgingdate() == castOther
						.getBzFxhedgingdate()) || (this.getBzFxhedgingdate() != null
						&& castOther.getBzFxhedgingdate() != null && this
						.getBzFxhedgingdate().equals(
								castOther.getBzFxhedgingdate())))
				&& ((this.getBzFxverification() == castOther
						.getBzFxverification()) || (this.getBzFxverification() != null
						&& castOther.getBzFxverification() != null && this
						.getBzFxverification().equals(
								castOther.getBzFxverification())))
				&& ((this.getBzFxhedgingCounte() == castOther
						.getBzFxhedgingCounte()) || (this
						.getBzFxhedgingCounte() != null
						&& castOther.getBzFxhedgingCounte() != null && this
						.getBzFxhedgingCounte().equals(
								castOther.getBzFxhedgingCounte())))
				&& ((this.getGtDeliveryPlace() == castOther
						.getGtDeliveryPlace()) || (this.getGtDeliveryPlace() != null
						&& castOther.getGtDeliveryPlace() != null && this
						.getGtDeliveryPlace().equals(
								castOther.getGtDeliveryPlace())))
				&& ((this.getGtLndCostFrom() == castOther.getGtLndCostFrom()) || (this
						.getGtLndCostFrom() != null
						&& castOther.getGtLndCostFrom() != null && this
						.getGtLndCostFrom()
						.equals(castOther.getGtLndCostFrom())))
				&& ((this.getGtLndCostTo() == castOther.getGtLndCostTo()) || (this
						.getGtLndCostTo() != null
						&& castOther.getGtLndCostTo() != null && this
						.getGtLndCostTo().equals(castOther.getGtLndCostTo())))
				&& ((this.getGtMgtprice() == castOther.getGtMgtprice()) || (this
						.getGtMgtprice() != null
						&& castOther.getGtMgtprice() != null && this
						.getGtMgtprice().equals(castOther.getGtMgtprice())))
				&& ((this.getGtPreparacion() == castOther.getGtPreparacion()) || (this
						.getGtPreparacion() != null
						&& castOther.getGtPreparacion() != null && this
						.getGtPreparacion()
						.equals(castOther.getGtPreparacion())))
				&& ((this.getGtPymtCondition() == castOther
						.getGtPymtCondition()) || (this.getGtPymtCondition() != null
						&& castOther.getGtPymtCondition() != null && this
						.getGtPymtCondition().equals(
								castOther.getGtPymtCondition())))
				&& ((this.getGtShpmtCostFrom() == castOther
						.getGtShpmtCostFrom()) || (this.getGtShpmtCostFrom() != null
						&& castOther.getGtShpmtCostFrom() != null && this
						.getGtShpmtCostFrom().equals(
								castOther.getGtShpmtCostFrom())))
				&& ((this.getGtShpmtCostTo() == castOther.getGtShpmtCostTo()) || (this
						.getGtShpmtCostTo() != null
						&& castOther.getGtShpmtCostTo() != null && this
						.getGtShpmtCostTo()
						.equals(castOther.getGtShpmtCostTo())))
				&& ((this.getGtShpmtValue() == castOther.getGtShpmtValue()) || (this
						.getGtShpmtValue() != null
						&& castOther.getGtShpmtValue() != null && this
						.getGtShpmtValue().equals(castOther.getGtShpmtValue())))
				&& ((this.getGtTradeCost() == castOther.getGtTradeCost()) || (this
						.getGtTradeCost() != null
						&& castOther.getGtTradeCost() != null && this
						.getGtTradeCost().equals(castOther.getGtTradeCost())))
				&& ((this.getGtRealCost() == castOther.getGtRealCost()) || (this
						.getGtRealCost() != null
						&& castOther.getGtRealCost() != null && this
						.getGtRealCost().equals(castOther.getGtRealCost())))
				&& ((this.getGtNetDiffBuy() == castOther.getGtNetDiffBuy()) || (this
						.getGtNetDiffBuy() != null
						&& castOther.getGtNetDiffBuy() != null && this
						.getGtNetDiffBuy().equals(castOther.getGtNetDiffBuy())))
				&& ((this.getGtZarCost() == castOther.getGtZarCost()) || (this
						.getGtZarCost() != null
						&& castOther.getGtZarCost() != null && this
						.getGtZarCost().equals(castOther.getGtZarCost())))
				&& ((this.getGtSubpCost() == castOther.getGtSubpCost()) || (this
						.getGtSubpCost() != null
						&& castOther.getGtSubpCost() != null && this
						.getGtSubpCost().equals(castOther.getGtSubpCost())))
				&& ((this.getMultiplier() == castOther.getMultiplier()) || (this
						.getMultiplier() != null
						&& castOther.getMultiplier() != null && this
						.getMultiplier().equals(castOther.getMultiplier())))
				&& ((this.getCountryName() == castOther.getCountryName()) || (this
						.getCountryName() != null
						&& castOther.getCountryName() != null && this
						.getCountryName().equals(castOther.getCountryName())))
				&& ((this.getCounterpart() == castOther.getCounterpart()) || (this
						.getCounterpart() != null
						&& castOther.getCounterpart() != null && this
						.getCounterpart().equals(castOther.getCounterpart())))
				&& ((this.getDestination() == castOther.getDestination()) || (this
						.getDestination() != null
						&& castOther.getDestination() != null && this
						.getDestination().equals(castOther.getDestination())))
				&& ((this.getRiskPeriodCd() == castOther.getRiskPeriodCd()) || (this
						.getRiskPeriodCd() != null
						&& castOther.getRiskPeriodCd() != null && this
						.getRiskPeriodCd().equals(castOther.getRiskPeriodCd())))
				&& (this.getTradeStatusInd() == castOther.getTradeStatusInd())
				&& ((this.getSpecCd() == castOther.getSpecCd()) || (this
						.getSpecCd() != null && castOther.getSpecCd() != null && this
						.getSpecCd().equals(castOther.getSpecCd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTradeNum();
		result = 37 * result
				+ (getTraderNum() == null ? 0 : this.getTraderNum().hashCode());
		result = 37
				* result
				+ (getInternalCompanyNum() == null ? 0 : this
						.getInternalCompanyNum().hashCode());
		result = 37
				* result
				+ (getCounterpartCompanyNum() == null ? 0 : this
						.getCounterpartCompanyNum().hashCode());
		result = 37 * result
				+ (getTradeDt() == null ? 0 : this.getTradeDt().hashCode());
		result = 37 * result + this.getBrokerCompanyNum();
		result = 37
				* result
				+ (getCommissionAmt() == null ? 0 : this.getCommissionAmt()
						.hashCode());
		result = 37
				* result
				+ (getCommCurrCd() == null ? 0 : this.getCommCurrCd()
						.hashCode());
		result = 37 * result
				+ (getCommUomCd() == null ? 0 : this.getCommUomCd().hashCode());
		result = 37
				* result
				+ (getBuySellInd() == null ? 0 : this.getBuySellInd()
						.hashCode());
		result = 37 * result
				+ (getBuySell() == null ? 0 : this.getBuySell().hashCode());
		result = 37 * result
				+ (getCmdtyCd() == null ? 0 : this.getCmdtyCd().hashCode());
		result = 37 * result
				+ (getCropYear() == null ? 0 : this.getCropYear().hashCode());
		result = 37 * result
				+ (getTradeQty() == null ? 0 : this.getTradeQty().hashCode());
		result = 37
				* result
				+ (getContractUomCd() == null ? 0 : this.getContractUomCd()
						.hashCode());
		result = 37
				* result
				+ (getDeliveryTermCd() == null ? 0 : this.getDeliveryTermCd()
						.hashCode());
		result = 37 * result
				+ (getLocation() == null ? 0 : this.getLocation().hashCode());
		result = 37 * result + this.getDestinaton();
		result = 37 * result + this.getCountry();
		result = 37
				* result
				+ (getDelivPeriodCd() == null ? 0 : this.getDelivPeriodCd()
						.hashCode());
		result = 37
				* result
				+ (getQuoteDefNum() == null ? 0 : this.getQuoteDefNum()
						.hashCode());
		result = 37
				* result
				+ (getExchContractNum() == null ? 0 : this.getExchContractNum()
						.hashCode());
		result = 37
				* result
				+ (getFixedPrice() == null ? 0 : this.getFixedPrice()
						.hashCode());
		result = 37
				* result
				+ (getPriceCurrCd() == null ? 0 : this.getPriceCurrCd()
						.hashCode());
		result = 37
				* result
				+ (getPriceUomCd() == null ? 0 : this.getPriceUomCd()
						.hashCode());
		result = 37 * result
				+ (getFobPrice() == null ? 0 : this.getFobPrice().hashCode());
		result = 37
				* result
				+ (getFobCurrency() == null ? 0 : this.getFobCurrency()
						.hashCode());
		result = 37 * result
				+ (getFobUom() == null ? 0 : this.getFobUom().hashCode());
		result = 37
				* result
				+ (getSettlePaymentTermCd() == null ? 0 : this
						.getSettlePaymentTermCd().hashCode());
		result = 37
				* result
				+ (getSettlementCurrCd() == null ? 0 : this
						.getSettlementCurrCd().hashCode());
		result = 37
				* result
				+ (getSettlementUomCd() == null ? 0 : this.getSettlementUomCd()
						.hashCode());
		result = 37 * result
				+ (getActionDt() == null ? 0 : this.getActionDt().hashCode());
		result = 37 * result + this.getPriceQuoteDefNum();
		result = 37 * result
				+ (getPremium() == null ? 0 : this.getPremium().hashCode());
		result = 37
				* result
				+ (getPremiumCurrCd() == null ? 0 : this.getPremiumCurrCd()
						.hashCode());
		result = 37
				* result
				+ (getPremiumUomCd() == null ? 0 : this.getPremiumUomCd()
						.hashCode());
		result = 37
				* result
				+ (getActionPrice() == null ? 0 : this.getActionPrice()
						.hashCode());
		result = 37
				* result
				+ (getActionPriceCurrCd() == null ? 0 : this
						.getActionPriceCurrCd().hashCode());
		result = 37
				* result
				+ (getActionPriceUomCd() == null ? 0 : this
						.getActionPriceUomCd().hashCode());
		result = 37 * result
				+ (getActionQty() == null ? 0 : this.getActionQty().hashCode());
		result = 37
				* result
				+ (getActionLotQty() == null ? 0 : this.getActionLotQty()
						.hashCode());
		result = 37
				* result
				+ (getActionQtyUomCd() == null ? 0 : this.getActionQtyUomCd()
						.hashCode());
		result = 37 * result
				+ (getDealId() == null ? 0 : this.getDealId().hashCode());
		result = 37 * result
				+ (getDealId2() == null ? 0 : this.getDealId2().hashCode());
		result = 37 * result
				+ (getNoteText() == null ? 0 : this.getNoteText().hashCode());
		result = 37
				* result
				+ (getNotePreview() == null ? 0 : this.getNotePreview()
						.hashCode());
		result = 37
				* result
				+ (getDeliveryTerms() == null ? 0 : this.getDeliveryTerms()
						.hashCode());
		result = 37
				* result
				+ (getWeightTerms() == null ? 0 : this.getWeightTerms()
						.hashCode());
		result = 37
				* result
				+ (getApprovalTerms() == null ? 0 : this.getApprovalTerms()
						.hashCode());
		result = 37
				* result
				+ (getBzCertPremium() == null ? 0 : this.getBzCertPremium()
						.hashCode());
		result = 37
				* result
				+ (getBzCertStatus() == null ? 0 : this.getBzCertStatus()
						.hashCode());
		result = 37
				* result
				+ (getBzChargedInterest() == null ? 0 : this
						.getBzChargedInterest().hashCode());
		result = 37
				* result
				+ (getBzCollatScheme() == null ? 0 : this.getBzCollatScheme()
						.hashCode());
		result = 37
				* result
				+ (getBzCreditAssignee() == null ? 0 : this
						.getBzCreditAssignee().hashCode());
		result = 37
				* result
				+ (getBzExchCtrNum() == null ? 0 : this.getBzExchCtrNum()
						.hashCode());
		result = 37
				* result
				+ (getBzFarmNeigh() == null ? 0 : this.getBzFarmNeigh()
						.hashCode());
		result = 37
				* result
				+ (getBzFarmRegion() == null ? 0 : this.getBzFarmRegion()
						.hashCode());
		result = 37
				* result
				+ (getBzFarmState() == null ? 0 : this.getBzFarmState()
						.hashCode());
		result = 37
				* result
				+ (getBzFobbasis() == null ? 0 : this.getBzFobbasis()
						.hashCode());
		result = 37
				* result
				+ (getBzFormalReturnDat() == null ? 0 : this
						.getBzFormalReturnDat().hashCode());
		result = 37
				* result
				+ (getBzFrmlztRlseDate() == null ? 0 : this
						.getBzFrmlztRlseDate().hashCode());
		result = 37
				* result
				+ (getBzFxhedgingLevel() == null ? 0 : this
						.getBzFxhedgingLevel().hashCode());
		result = 37
				* result
				+ (getBzGuarantor1st() == null ? 0 : this.getBzGuarantor1st()
						.hashCode());
		result = 37
				* result
				+ (getBzGuarantor2nd() == null ? 0 : this.getBzGuarantor2nd()
						.hashCode());
		result = 37
				* result
				+ (getBzIr1recepDat() == null ? 0 : this.getBzIr1recepDat()
						.hashCode());
		result = 37
				* result
				+ (getBzIr1ProductHec() == null ? 0 : this.getBzIr1ProductHec()
						.hashCode());
		result = 37
				* result
				+ (getBzIr1RiskSituat() == null ? 0 : this.getBzIr1RiskSituat()
						.hashCode());
		result = 37
				* result
				+ (getBzPymtAnticip() == null ? 0 : this.getBzPymtAnticip()
						.hashCode());
		result = 37
				* result
				+ (getBzShareholderdsbmt() == null ? 0 : this
						.getBzShareholderdsbmt().hashCode());
		result = 37
				* result
				+ (getBzTradeBasis() == null ? 0 : this.getBzTradeBasis()
						.hashCode());
		result = 37
				* result
				+ (getBzTradeType() == null ? 0 : this.getBzTradeType()
						.hashCode());
		result = 37
				* result
				+ (getCurrentPotype() == null ? 0 : this.getCurrentPotype()
						.hashCode());
		result = 37
				* result
				+ (getFxfixedRate() == null ? 0 : this.getFxfixedRate()
						.hashCode());
		result = 37 * result
				+ (getPotype() == null ? 0 : this.getPotype().hashCode());
		result = 37
				* result
				+ (getBzFinRatio() == null ? 0 : this.getBzFinRatio()
						.hashCode());
		result = 37
				* result
				+ (getBzAnuentePrimario() == null ? 0 : this
						.getBzAnuentePrimario().hashCode());
		result = 37
				* result
				+ (getBzAnuenteSecundario() == null ? 0 : this
						.getBzAnuenteSecundario().hashCode());
		result = 37
				* result
				+ (getBzFixationDeadline() == null ? 0 : this
						.getBzFixationDeadline().hashCode());
		result = 37 * result
				+ (getBzWacc() == null ? 0 : this.getBzWacc().hashCode());
		result = 37
				* result
				+ (getBzLgfixedPriceSao() == null ? 0 : this
						.getBzLgfixedPriceSao().hashCode());
		result = 37
				* result
				+ (getBzThirdpartydsbmt() == null ? 0 : this
						.getBzThirdpartydsbmt().hashCode());
		result = 37
				* result
				+ (getBzCollatRecepDate() == null ? 0 : this
						.getBzCollatRecepDate().hashCode());
		result = 37
				* result
				+ (getBzShareholDsbmtDt() == null ? 0 : this
						.getBzShareholDsbmtDt().hashCode());
		result = 37
				* result
				+ (getBz3partyDsbmtDt() == null ? 0 : this.getBz3partyDsbmtDt()
						.hashCode());
		result = 37
				* result
				+ (getBzExpDiffFobbas() == null ? 0 : this.getBzExpDiffFobbas()
						.hashCode());
		result = 37
				* result
				+ (getBzDrdiffvsNysao() == null ? 0 : this.getBzDrdiffvsNysao()
						.hashCode());
		result = 37
				* result
				+ (getBzActualAnticAmt() == null ? 0 : this
						.getBzActualAnticAmt().hashCode());
		result = 37
				* result
				+ (getBzBcdiffTrade() == null ? 0 : this.getBzBcdiffTrade()
						.hashCode());
		result = 37
				* result
				+ (getBzBcdiffFob() == null ? 0 : this.getBzBcdiffFob()
						.hashCode());
		result = 37
				* result
				+ (getBzDeliveryWhse() == null ? 0 : this.getBzDeliveryWhse()
						.hashCode());
		result = 37
				* result
				+ (getBzFxexposure() == null ? 0 : this.getBzFxexposure()
						.hashCode());
		result = 37
				* result
				+ (getBzFxhedgingdate() == null ? 0 : this.getBzFxhedgingdate()
						.hashCode());
		result = 37
				* result
				+ (getBzFxverification() == null ? 0 : this
						.getBzFxverification().hashCode());
		result = 37
				* result
				+ (getBzFxhedgingCounte() == null ? 0 : this
						.getBzFxhedgingCounte().hashCode());
		result = 37
				* result
				+ (getGtDeliveryPlace() == null ? 0 : this.getGtDeliveryPlace()
						.hashCode());
		result = 37
				* result
				+ (getGtLndCostFrom() == null ? 0 : this.getGtLndCostFrom()
						.hashCode());
		result = 37
				* result
				+ (getGtLndCostTo() == null ? 0 : this.getGtLndCostTo()
						.hashCode());
		result = 37
				* result
				+ (getGtMgtprice() == null ? 0 : this.getGtMgtprice()
						.hashCode());
		result = 37
				* result
				+ (getGtPreparacion() == null ? 0 : this.getGtPreparacion()
						.hashCode());
		result = 37
				* result
				+ (getGtPymtCondition() == null ? 0 : this.getGtPymtCondition()
						.hashCode());
		result = 37
				* result
				+ (getGtShpmtCostFrom() == null ? 0 : this.getGtShpmtCostFrom()
						.hashCode());
		result = 37
				* result
				+ (getGtShpmtCostTo() == null ? 0 : this.getGtShpmtCostTo()
						.hashCode());
		result = 37
				* result
				+ (getGtShpmtValue() == null ? 0 : this.getGtShpmtValue()
						.hashCode());
		result = 37
				* result
				+ (getGtTradeCost() == null ? 0 : this.getGtTradeCost()
						.hashCode());
		result = 37
				* result
				+ (getGtRealCost() == null ? 0 : this.getGtRealCost()
						.hashCode());
		result = 37
				* result
				+ (getGtNetDiffBuy() == null ? 0 : this.getGtNetDiffBuy()
						.hashCode());
		result = 37 * result
				+ (getGtZarCost() == null ? 0 : this.getGtZarCost().hashCode());
		result = 37
				* result
				+ (getGtSubpCost() == null ? 0 : this.getGtSubpCost()
						.hashCode());
		result = 37
				* result
				+ (getMultiplier() == null ? 0 : this.getMultiplier()
						.hashCode());
		result = 37
				* result
				+ (getCountryName() == null ? 0 : this.getCountryName()
						.hashCode());
		result = 37
				* result
				+ (getCounterpart() == null ? 0 : this.getCounterpart()
						.hashCode());
		result = 37
				* result
				+ (getDestination() == null ? 0 : this.getDestination()
						.hashCode());
		result = 37
				* result
				+ (getRiskPeriodCd() == null ? 0 : this.getRiskPeriodCd()
						.hashCode());
		result = 37 * result + this.getTradeStatusInd();
		result = 37 * result
				+ (getSpecCd() == null ? 0 : this.getSpecCd().hashCode());
		return result;
	}

}
