package com.mercon.entities;

// Generated Apr 30, 2014 11:49:17 AM by Hibernate Tools 4.0.0

/**
 * VtradeInput generated by hbm2java
 */
public class VtradeInput implements java.io.Serializable {

	/**
	 * Serial ID
	 */
	private static final long serialVersionUID = 2669876680617266555L;
	
	private VtradeInputId id;

	public VtradeInput() {
	}

	public VtradeInput(VtradeInputId id) {
		this.id = id;
	}

	public VtradeInputId getId() {
		return this.id;
	}

	public void setId(VtradeInputId id) {
		this.id = id;
	}

}
