package com.mercon.entities;

// Generated Nov 12, 2014 2:45:57 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * VtradeHdrId generated by hbm2java
 */
public class VtradeHdrId implements java.io.Serializable {

	/**
	 * Serial ID
	 */
	private static final long serialVersionUID = -3869535009191830535L;

	private Integer internalCompanyNum;
	private Integer counterpartCompanyNum;
	private int tradeNum;
	private Integer termNum;
	private Short buySellInd;
	private String cmdtyCd;
	private Integer strategyNum;
	private String settlementCurrCd;
	private String qtyUomCd;
	private String settlementUomCd;
	private BigDecimal tradeQty;
	private BigDecimal openQty;

	public VtradeHdrId() {
	}

	public VtradeHdrId(int tradeNum) {
		this.tradeNum = tradeNum;
	}

	public VtradeHdrId(Integer internalCompanyNum,
			Integer counterpartCompanyNum, int tradeNum, Integer termNum,
			Short buySellInd, String cmdtyCd, Integer strategyNum,
			String settlementCurrCd, String qtyUomCd, String settlementUomCd,
			BigDecimal tradeQty, BigDecimal openQty) {
		this.internalCompanyNum = internalCompanyNum;
		this.counterpartCompanyNum = counterpartCompanyNum;
		this.tradeNum = tradeNum;
		this.termNum = termNum;
		this.buySellInd = buySellInd;
		this.cmdtyCd = cmdtyCd;
		this.strategyNum = strategyNum;
		this.settlementCurrCd = settlementCurrCd;
		this.qtyUomCd = qtyUomCd;
		this.settlementUomCd = settlementUomCd;
		this.tradeQty = tradeQty;
		this.openQty = openQty;
	}

	public Integer getInternalCompanyNum() {
		return this.internalCompanyNum;
	}

	public void setInternalCompanyNum(Integer internalCompanyNum) {
		this.internalCompanyNum = internalCompanyNum;
	}

	public Integer getCounterpartCompanyNum() {
		return this.counterpartCompanyNum;
	}

	public void setCounterpartCompanyNum(Integer counterpartCompanyNum) {
		this.counterpartCompanyNum = counterpartCompanyNum;
	}

	public int getTradeNum() {
		return this.tradeNum;
	}

	public void setTradeNum(int tradeNum) {
		this.tradeNum = tradeNum;
	}

	public Integer getTermNum() {
		return this.termNum;
	}

	public void setTermNum(Integer termNum) {
		this.termNum = termNum;
	}

	public Short getBuySellInd() {
		return this.buySellInd;
	}

	public void setBuySellInd(Short buySellInd) {
		this.buySellInd = buySellInd;
	}

	public String getCmdtyCd() {
		return this.cmdtyCd;
	}

	public void setCmdtyCd(String cmdtyCd) {
		this.cmdtyCd = cmdtyCd;
	}

	public Integer getStrategyNum() {
		return this.strategyNum;
	}

	public void setStrategyNum(Integer strategyNum) {
		this.strategyNum = strategyNum;
	}

	public String getSettlementCurrCd() {
		return this.settlementCurrCd;
	}

	public void setSettlementCurrCd(String settlementCurrCd) {
		this.settlementCurrCd = settlementCurrCd;
	}

	public String getQtyUomCd() {
		return this.qtyUomCd;
	}

	public void setQtyUomCd(String qtyUomCd) {
		this.qtyUomCd = qtyUomCd;
	}

	public String getSettlementUomCd() {
		return this.settlementUomCd;
	}

	public void setSettlementUomCd(String settlementUomCd) {
		this.settlementUomCd = settlementUomCd;
	}

	public BigDecimal getTradeQty() {
		return this.tradeQty;
	}

	public void setTradeQty(BigDecimal tradeQty) {
		this.tradeQty = tradeQty;
	}

	public BigDecimal getOpenQty() {
		return this.openQty;
	}

	public void setOpenQty(BigDecimal openQty) {
		this.openQty = openQty;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VtradeHdrId))
			return false;
		VtradeHdrId castOther = (VtradeHdrId) other;

		return ((this.getInternalCompanyNum() == castOther
				.getInternalCompanyNum()) || (this.getInternalCompanyNum() != null
				&& castOther.getInternalCompanyNum() != null && this
				.getInternalCompanyNum().equals(
						castOther.getInternalCompanyNum())))
				&& ((this.getCounterpartCompanyNum() == castOther
						.getCounterpartCompanyNum()) || (this
						.getCounterpartCompanyNum() != null
						&& castOther.getCounterpartCompanyNum() != null && this
						.getCounterpartCompanyNum().equals(
								castOther.getCounterpartCompanyNum())))
				&& (this.getTradeNum() == castOther.getTradeNum())
				&& ((this.getTermNum() == castOther.getTermNum()) || (this
						.getTermNum() != null && castOther.getTermNum() != null && this
						.getTermNum().equals(castOther.getTermNum())))
				&& ((this.getBuySellInd() == castOther.getBuySellInd()) || (this
						.getBuySellInd() != null
						&& castOther.getBuySellInd() != null && this
						.getBuySellInd().equals(castOther.getBuySellInd())))
				&& ((this.getCmdtyCd() == castOther.getCmdtyCd()) || (this
						.getCmdtyCd() != null && castOther.getCmdtyCd() != null && this
						.getCmdtyCd().equals(castOther.getCmdtyCd())))
				&& ((this.getStrategyNum() == castOther.getStrategyNum()) || (this
						.getStrategyNum() != null
						&& castOther.getStrategyNum() != null && this
						.getStrategyNum().equals(castOther.getStrategyNum())))
				&& ((this.getSettlementCurrCd() == castOther
						.getSettlementCurrCd()) || (this.getSettlementCurrCd() != null
						&& castOther.getSettlementCurrCd() != null && this
						.getSettlementCurrCd().equals(
								castOther.getSettlementCurrCd())))
				&& ((this.getQtyUomCd() == castOther.getQtyUomCd()) || (this
						.getQtyUomCd() != null
						&& castOther.getQtyUomCd() != null && this
						.getQtyUomCd().equals(castOther.getQtyUomCd())))
				&& ((this.getSettlementUomCd() == castOther
						.getSettlementUomCd()) || (this.getSettlementUomCd() != null
						&& castOther.getSettlementUomCd() != null && this
						.getSettlementUomCd().equals(
								castOther.getSettlementUomCd())))
				&& ((this.getTradeQty() == castOther.getTradeQty()) || (this
						.getTradeQty() != null
						&& castOther.getTradeQty() != null && this
						.getTradeQty().equals(castOther.getTradeQty())))
				&& ((this.getOpenQty() == castOther.getOpenQty()) || (this
						.getOpenQty() != null && castOther.getOpenQty() != null && this
						.getOpenQty().equals(castOther.getOpenQty())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getInternalCompanyNum() == null ? 0 : this
						.getInternalCompanyNum().hashCode());
		result = 37
				* result
				+ (getCounterpartCompanyNum() == null ? 0 : this
						.getCounterpartCompanyNum().hashCode());
		result = 37 * result + this.getTradeNum();
		result = 37 * result
				+ (getTermNum() == null ? 0 : this.getTermNum().hashCode());
		result = 37
				* result
				+ (getBuySellInd() == null ? 0 : this.getBuySellInd()
						.hashCode());
		result = 37 * result
				+ (getCmdtyCd() == null ? 0 : this.getCmdtyCd().hashCode());
		result = 37
				* result
				+ (getStrategyNum() == null ? 0 : this.getStrategyNum()
						.hashCode());
		result = 37
				* result
				+ (getSettlementCurrCd() == null ? 0 : this
						.getSettlementCurrCd().hashCode());
		result = 37 * result
				+ (getQtyUomCd() == null ? 0 : this.getQtyUomCd().hashCode());
		result = 37
				* result
				+ (getSettlementUomCd() == null ? 0 : this.getSettlementUomCd()
						.hashCode());
		result = 37 * result
				+ (getTradeQty() == null ? 0 : this.getTradeQty().hashCode());
		result = 37 * result
				+ (getOpenQty() == null ? 0 : this.getOpenQty().hashCode());
		return result;
	}

}
