package com.mercon.entities;

// Generated Nov 12, 2014 2:45:57 PM by Hibernate Tools 4.0.0

/**
 * VtradeHdr generated by hbm2java
 */
public class VtradeHdr implements java.io.Serializable {

	/**
	 * Serial ID
	 */
	private static final long serialVersionUID = 3953897781710647164L;

	private VtradeHdrId id;

	public VtradeHdr() {
	}

	public VtradeHdr(VtradeHdrId id) {
		this.id = id;
	}

	public VtradeHdrId getId() {
		return this.id;
	}

	public void setId(VtradeHdrId id) {
		this.id = id;
	}

}
